package br.com.xbrain.autenticacao.modules.usuario.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum CanalNetSales {

    D2D_ACOES_ESPECIAIS("D2D-ACOES ESPECIAIS"),
    D2D_CLARO_PESSOAL("D2D-CLARO PESSOAL"),
    D2D_CONDOMINIO("D2D-CONDOMINIO"),
    D2D_CONVERSAO_MDU("D2D-CONVERSAO MDU"),
    D2D_ESPECIALISTA("D2D-ESPECIALISTA"),
    D2D_INDIRETO("D2D-INDIRETO"),
    D2D_PESSOA_JURIDICA("D2D-PESSOA JURIDICA"),
    D2D_PME("D2D-PME"),
    D2D_TECNICO("D2D-TECNICO"),
    D2D_VENDAS_PESSOAIS("D2D-VENDAS PESSOAIS"),
    PROP_TECNICO("PROP-TECNICO"),
    PROP_CONDOMINIO_NET_CURITIBA("PROP-CONDOMINIO-NET CURITIBA"),
    PROP_VENDAS_MDU_NET_FLO("PROP-VENDAS MDU-NET FLO"),
    PROP_VENDAS_PESSOAIS_NET_ANA("PROP-VENDAS PESSOAIS-NET ANA"),
    PROP_VENDAS_PESSOAIS_NET_BLU("PROP-VENDAS PESSOAIS-NET BLU"),
    PROP_VENDAS_PESSOAIS_NET_CGR("PROP-VENDAS PESSOAIS-NET CGR"),
    PROP_VENDAS_PESSOAIS_NET_RIB("PROP-VENDAS PESSOAIS-NET RIB"),
    PROP_VENDAS_PESSOAIS_NET_RIO("PROP-VENDAS PESSOAIS-NET RIO"),
    PROP_VENDAS_PESSOAIS_NET_SAN("PROP-VENDAS PESSOAIS-NET SAN"),
    VENDAS_CORPORATIVAS("VENDAS CORPORATIVAS"),
    VENDAS_PARA_FUNCIONARIO("VENDAS PARA FUNCIONARIO"),
    VENDAS_PDV("VENDAS PDV"),
    VENDAS_POR_FORNECEDOR("VENDAS POR FORNECEDOR"),
    VENDAS_POR_PARCEIROS("VENDAS POR PARCEIROS"),
    VENDAS_PORTA_A_PORTA("VENDAS PORTA A PORTA"),
    VENDAS_VIA_NOVITECH("VENDAS VIA NOVITECH"),
    VENDAS_VIA_PORTAL("VENDAS VIA PORTAL");

    private final String descricao;
}
