package br.com.xbrain.autenticacao.modules.usuario.enums;

/**
 * Created by rafaelzeffa on 03/11/16.
 */
public enum CodigoFuncionalidade {
    AUT_GER_USUARIO,
    AUT_VISUALIZAR_GERAL,
    AUT_VISUALIZAR_EMPRESA_UNIDADE,
    AUT_VISUALIZAR_CARTEIRA_HIERARQUIA,
    AUT_VISUALIZAR_CIDADE,
    AUT_VISUALIZAR_CARTEIRA,

    POL_VISUALIZAR_DOCUMENTOS_AA,
    POL_GERENCIAR_AA,
    POL_VISUALIZAR_AA_GERAL,
    POL_VISUALIZAR_AA_EMPRESA_UNIDADE,
    POL_VISUALIZAR_AA_CARTEIRA,
    POL_VISUALIZAR_AA_CIDADE,
    POL_GERENCIAR_COMUNICADO_GERAL,
    POL_AGENTE_AUTORIZADO_APROVACAO_MSO,
    POL_AGENTE_AUTORIZADO_APROVACAO_MSO_NOVO_CADASTRO,
    POL_AGENTE_AUTORIZADO_APROVACAO_MSO_DESCREDENCIAMENTO_NAC,
    POL_PROJTOP_VISUALIZAR_METAS,
    POL_GERENCIAR_USUARIOS_EXECUTIVO,
    POL_EQUIPE_VENDA_EDITAR_LIDER
}
