package br.com.xbrain.autenticacao.modules.usuario.enums;

/**
 * Created by rafaelzeffa on 03/11/16.
 */
public enum CodigoFuncionalidade {
    VISUALIZAR_DOCUMENTOS_AA,
    GERENCIAR_AA,
    VISUALIZAR_AA_GERAL,
    VISUALIZAR_AA_EMPRESA_UNIDADE,
    VISUALIZAR_AA_CARTEIRA,
    VISUALIZAR_AA_CIDADE,
    GERENCIAR_COMUNICADO_GERAL,
    AGENTE_AUTORIZADO_APROVACAO_MSO,
    AGENTE_AUTORIZADO_APROVACAO_MSO_NOVO_CADASTRO,
    AGENTE_AUTORIZADO_APROVACAO_MSO_DESCREDENCIAMENTO_NAC,
    PROJTOP_VISUALIZAR_METAS,
    GERENCIAR_USUARIOS_EXECUTIVO,
    EQUIPE_VENDA_EDITAR_LIDER
}
