package br.com.xbrain.autenticacao.modules.usuario.enums;

public enum CodigoDepartamento {

    AGENTE_AUTORIZADO,
    COMERCIAL,
    HELP_DESK,
    ADMINISTRADOR,
    VAREJO,
    ATENDIMENTO_JEC,
    FEEDER,
    OUVIDORIA,
    INTEGRACAO,
    TREINAMENTO,
    ADMINISTRATIVO,
    AUDITORIA,
    COMUNICACAO,
    ENDOMARKETING,
    FINANCEIRO,
    MARKETING,
    PLANEJAMENTO_COMERCIAL,
    PROCESSOS_COMERCIAL,
    PROJETOS,
    SUPORTE_COMERCIAL,
    TRADE_MARKETING,
    TECNICO,
    CREDITO,
    ANTI_FRAUDE,
    ENDERECOS
}
