package br.com.xbrain.autenticacao.modules.usuario.enums;

public enum CodigoCargo {
    AGENTE_AUTORIZADO_ACEITE,
    AGENTE_AUTORIZADO_SOCIO,
    AGENTE_AUTORIZADO_SOCIO_SECUNDARIO,
    AGENTE_AUTORIZADO_SUPERVISOR,
    AGENTE_AUTORIZADO_GERENTE,
    AGENTE_AUTORIZADO_VENDEDOR_TELEVENDAS,
    AGENTE_AUTORIZADO_VENDEDOR_D2D,
    AGENTE_AUTORIZADO_VENDEDOR_HIBRIDO,
    AGENTE_AUTORIZADO_BACKOFFICE,
    MSO_CONSULTOR,
    GERENTE_OPERACAO,
    COORDENADOR_OPERACAO,
    EXECUTIVO,
    ASSISTENTE_OPERACAO,
    AGENTE_AUTORIZADO_SUPERVISOR_XBRAIN,
    VAREJO_SUPERVISOR,
    VAREJO_GERENTE,
    VAREJO_VENDEDOR,
    ADMINISTRADOR;
}