package br.com.xbrain.autenticacao.modules.usuario.enums;

import java.util.List;

public enum CodigoNivel {
    AGENTE_AUTORIZADO,
    AGENTE_AUTORIZADO_NACIONAL,
    MSO,
    OPERACAO,
    XBRAIN,
    VAREJO,
    ATP,
    LOJAS,
    RECEPTIVO,
    RECEPTIVO_SEGMENTADO,
    ATIVO_LOCAL_PROPRIO,
    ATIVO_LOCAL_TERCEIRO,
    ATIVO_NACIONAL_TERCEIRO,
    ATIVO_NACIONAL_TERCEIRO_SEGMENTADO,
    ATIVO_RENTABILIZACAO,
    ATIVO_LOCAL_COLABORADOR,
    BACKOFFICE,
    BACKOFFICE_CENTRALIZADO,
    OUVIDORIA,
    INTEGRACAO,
    GERADOR_LEADS,
    FEEDER,
    COBRANCA,
    BACKOFFICE_SUPORTE_VENDAS;

    public static boolean isNivelObirgatorioDadosNetSales(CodigoNivel codigoNivel) {
        var niveisObrigatorios = List.of(AGENTE_AUTORIZADO_NACIONAL, OPERACAO, VAREJO, ATP, LOJAS, RECEPTIVO,
            RECEPTIVO_SEGMENTADO, ATIVO_LOCAL_PROPRIO, ATIVO_LOCAL_TERCEIRO, ATIVO_RENTABILIZACAO,
            ATIVO_LOCAL_COLABORADOR, ATIVO_NACIONAL_TERCEIRO, ATIVO_NACIONAL_TERCEIRO_SEGMENTADO, OUVIDORIA, COBRANCA);

        return niveisObrigatorios.contains(codigoNivel);
    }
}
