package br.com.xbrain.autenticacao.modules.usuario.enums;

public enum CodigoNivel {
    AGENTE_AUTORIZADO,
    MSO,
    OPERACAO,
    XBRAIN,
    VAREJO,
    ATP,
    LOJAS,
    RECEPTIVO,
    RECEPTIVO_SEGMENTADO,
    ATIVO_LOCAL_PROPRIO,
    ATIVO_LOCAL_TERCEIRO,
    ATIVO_NACIONAL_TERCEIRO,
    ATIVO_NACIONAL_TERCEIRO_SEGMENTADO,
    ATIVO_RENTABILIZACAO;
}
