spring:

  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.1.6:1521/DEV
    username: AUTENTICACAO
    password: py12nrk7

app-config:
  services:
    parceiros-online:
      url: https://parceiros-dev.conexaoclarobrasil.com.br/

  email:
    enviar: true
    emails: andre@xbrain.com.br
