app-config:
  url-origin-cors: dev.conexaoclarobrasil.com.br,http://localhost
  timer-usuario:
    data-hora-inativar-usuario-a-partir-de: 2021-05-30T00:00:00.000
    email-usuario-viabilidade: INTEGRACAOMOTIVA@XBRAIN.COM.BR,INTEGRACAODDCOM@XBRAIN.COM.BR,INTEGRACAOCREDITCASH@XBRAIN.COM.BR

  services:
    autenticacao:
      url: http://172.10.10.33:8096
    parceiros-online:
      url: http://172.10.10.36:8099
    call:
      url: http://172.10.10.38:8094
    vendas:
      url: http://172.10.10.34:8097
    mailing:
      url: http://172.10.10.37:8095
    equipe-venda:
      url: http://172.10.10.22:8089
    contato-crn:
      url: http://172.10.10.65:8084
    comunicados:
      url: http://172.10.10.51:6549
    claro-indico:
      url: http://172.10.10.54:8055
    gestao:
      url: http://172.10.10.21:8091
    notificacao:
      url: http://172.10.10.95:8081
    agente-autorizado:
      url: http://172.10.10.105:8300
    emails:
      url: http://api-hom.conexaoclarobrasil.com.br/email
    integracao-vendas:
      url: http://172.10.10.45:8086
    mailing-importacao:
      url: http://172.10.10.32:8087
    lei-nao-perturbe:
      url: http://lei-nao-perturbe-api:8109
    extrato-comissao:
      url: http://extrato-comissao-api:8309
    funil-prospeccao:
      url: http://172.10.10.109:8304
    ata-reuniao:
      url: http://ata-reuniao-api:8308

logging:
  file: /home/xbrain/dev/autenticacao/dev.log
  level:
    org.springframework: 'ERROR'
    org.hibernate: 'ERROR'

spring:
  redis:
    host: 172.10.10.40
    port: 6379

  datasource:
    hikari:
      maximumPoolSize: 10

  rabbitmq:
    host: 172.10.10.30
    port: 5672
    username: xbrain
    password: xbrain

xbrain:
  logging:
    level: INFO
    appender: JSON
