app-config:
  url-origin-cors: dev.conexaoclarobrasil.com.br,http://localhost,http://192.168.50.1
  timer-usuario:
    data-hora-inativar-usuario-a-partir-de: 2021-05-30T00:00:00.000
    email-usuario-viabilidade: INTEGRACAOMOTIVA@XBRAIN.COM.BR,INTEGRACAODDCOM@XBRAIN.COM.BR,INTEGRACAOCREDITCASH@XBRAIN.COM.BR

  services:
    autenticacao:
      url: http://autenticacao-api-dev:8096
    parceiros-online:
      url: http://172.10.10.36:8099
    call:
      url: http://call-api-dev:8094
    vendas:
      url: http://vendas-api-dev:8097
    mailing:
      url: http://mailing-api-dev:8095
    equipe-venda:
      url: http://equipe-venda-api-dev:8089
    contato-crn:
      url: http://contato-crn-api-dev:8084
    comunicados:
      url: http://172.10.10.51:6549
    claro-indico:
      url: http://claro-indico-api-dev:8055
    gestao:
      url: http://conexao-gestao-api-dev:8091
    notificacao:
      url: http://172.10.10.95:8081
    agente-autorizado:
      url: http://agente-autorizado-api-dev:8300
    emails:
      url: https://api-hom.conexaoclarobrasil.com.br/email
    integracao-vendas:
      url: http://172.10.10.45:8086
    mailing-importacao:
      url: http://mailing-importacao-api-dev:8087
    lei-nao-perturbe:
      url: http://lei-nao-perturbe-api:8109
    extrato-comissao:
      url: http://extrato-comissao-api:8309
    funil-prospeccao:
      url: http://172.10.10.109:8304
    localizacao:
      url: http://localizacao-api:8039
    gestao-colaborador-pol:
      url: http://gestao-colaborador-pol-api:8310
    integracao-claro-net:
      url: http://integracao-claro-net-api:8505
    suporte-vendas-bko:
      url: http://suporte-vendas-bko-api:8050
    checagem-credito:
      url: http://checagem-credito-api:8037
    backoffice:
      url: http://backoffice-api-dev:8101
    feriado-automacao:
      url: http://192.168.50.4:8078

logging:
  file: /home/xbrain/dev/autenticacao/dev.log
  level:
    org.springframework: 'ERROR'
    org.hibernate: 'ERROR'

spring:
  redis:
    host: 172.10.10.40
    port: 6379

  datasource:
    hikari:
      maximumPoolSize: 10

  rabbitmq:
    host: 172.10.10.30
    port: 5672
    username: xbrain
    password: xbrain

xbrain:
  logging:
    level: INFO
    appender: JSON
