spring:
  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.1.7:1521/hmlg
    username: AUTENTICACAO
    password: py12nrk7
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 2

  rabbitmq:
    host: 172.10.10.70
    port: 5672
    username: xbrain
    password: xbrain

app-config:
  url: https://autenticacao-hom.conexaoclarobrasil.com.br
  url-estatico-upload: ${app-config.url-estatico}/homologacao/autenticacao
  upload-dir: ${app-config.estatico-dir}/homologacao/autenticacao
  
  services:
    parceiros-online:
      url: http://172.10.10.76:8099
    call:
      url: http://172.10.10.78:8094

  email:
    enviar: true
    emails:

logging:
  level:
      org.springframework: 'ERROR'
      org.hibernate: 'ERROR'
