spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.1.7:1521/hmlg
    username: AUTENTICACAO
    password: py12nrk7
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 2

  rabbitmq:
    host: 172.10.10.70
    port: 5672
    username: xbrain
    password: xbrain

logging:
  level:
      org.springframework: 'ERROR'
      org.hibernate: 'ERROR'
