spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:oracle:thin:@//192.168.1.6:1521/DEV
    username: AUTENTICACAO_TEST
    password: py12nrk7
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 2