spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.1.7:1521/hmlg
    username: AUTENTICACAO
    password: py12nrk7
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 2

logging:
  file: /var/log/autenticacao/application.log
  level:
      org.springframework: 'ERROR'
      org.hibernate: 'ERROR'
