spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    jdbcUrl: jdbc:oracle:thin:@//192.168.1.6:1521/DEV
    username: AUTENTICACAO
    password: py12nrk7
    driverClassName: oracle.jdbc.OracleDriver

  datasource-parceiros:
    jdbcUrl: jdbc:oracle:thin:@//192.168.1.6:1521/DEV
    username: homologacao
    password: c1t1gu1zes
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 1