app-config:
  timer-usuario:
    data-hora-inativar-usuario-a-partir-de: 2021-07-30T00:00:00.000
    email-usuario-viabilidade: LUIZ@XBRAIN.COM.BR

  services:
    autenticacao:
      url: http://172.10.10.33:8096
    parceiros-online:
      url: http://172.10.10.36:8099
    call:
      url: http://172.10.10.38:8094
    vendas:
      url: http://172.10.10.34:8097
    mailing:
      url: http://172.10.10.37:8095
    equipe-venda:
      url: http://172.10.10.22:8089
    contato-crn:
      url: http://172.10.10.65:8084
    comunicados:
      url: http://172.10.10.51:6549
    claro-indico:
      url: http://172.10.10.54:8055
    gestao:
      url: http://172.10.10.21:8091
    notificacao:
      url: http://172.10.10.95:8081
    agente-autorizado:
      url: http://172.10.10.105:8300
    emails:
      url: http://api-hom.conexaoclarobrasil.com.br/email

logging:
  file: /home/xbrain/dev/autenticacao/dev.log
  level:
    org.springframework: 'ERROR'
    org.hibernate: 'ERROR'

spring:
  redis:
    host: 172.10.10.40
    port: 6379

  rabbitmq:
    host: 172.10.10.30
    port: 5672
    username: xbrain
    password: xbrain
