spring:
  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.1.16:1521/hmlg
    username: AUTENTICACAO
    password: 4ut3nt1c4c40
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximumPoolSize: 10

  redis:
    host: 172.10.10.80
    port: 6379

  rabbitmq:
    host: 172.10.10.70
    port: 5672
    username: xbrain
    password: xbrain

app-config:
  url: https://autenticacao-hom.conexaoclarobrasil.com.br
  url-servico-email: http://172.10.10.41:8080/emails/
  url-estatico-upload: ${app-config.url-estatico}/homologacao/autenticacao
  upload-dir: ${app-config.estatico-dir}/homologacao/autenticacao

  services:
    autenticacao:
      url: http://172.10.10.73:8096
    vendas:
      url: http://172.10.10.74:8097
    parceiros-online:
      url: http://172.10.10.76:8099
    call:
      url: http://172.10.10.78:8094
    mailing:
      url: http://172.10.10.77:8095
    equipe-venda:
      url: http://172.10.10.82:8089
    contato-crn:
      url: http://172.10.10.64:8084

  email:
    enviar: true
    empresa-alias: XBRAIN
    emails: angelica@xbrain.com.br,valdecir@xbrain.com.br,higor@xbrain.com.br
    emails-solicitacao-ramal: angelica@xbrain.com.br, higor@xbrain.com.br, valdecir@xbrain.com.br

logging:
  level:
    org.springframework: 'ERROR'
    org.hibernate: 'ERROR'
