spring:
  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.50.2:1521/certificacao
    username: AUTENTICACAO
    password: 4ut3nt1c4c40
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximumPoolSize: 2

  redis:
    host: 172.10.10.2
    port: 6379

  rabbitmq:
    host: 172.10.10.3
    port: 5672
    username: xbrain
    password: xbrain

app-config:
  timer-usuario:
    data-hora-inativar-usuario-a-partir-de: 2021-05-30T00:00:00.000
    email-usuario-viabilidade: INTEGRACAOMOTIVA@XBRAIN.COM.BR,INTEGRACAODDCOM@XBRAIN.COM.BR,INTEGRACAOCREDITCASH@XBRAIN.COM.BR

  url: https://autenticacao-crt.conexaoclarobrasil.com.br
  url-estatico-upload: ${app-config.url-estatico}/certificacao/autenticacao
  upload-dir: ${app-config.estatico-dir}/certificacao/autenticacao

  services:
    autenticacao:
      url: http://172.10.10.73:8096
    vendas:
      url: http://172.10.10.74:8097
    parceiros-online:
      url: http://172.10.10.76:8099
    call:
      url: http://172.10.10.78:8094
    mailing:
      url: http://172.10.10.77:8095
    mailing-importacao:
      url: http://172.10.10.86:8087
    equipe-venda:
      url: http://172.10.10.82:8089
    contato-crn:
      url: http://172.10.10.64:8084
    comunicados:
      url: http://172.10.10.53:6553
    claro-indico:
      url: http://172.10.10.55:8055
    agente-autorizado:
      url: http://172.10.10.106:8300
    gestao:
      url: http://172.10.10.71:8091
    notificacao:
      url: http://172.10.10.98:8081
    emails:
      url: http://email-hom:8080
    integracao-vendas:
      url: http://172.10.10.85:8086
    lei-nao-perturbe:
      url: http://lei-nao-perturbe-api:8107
    gestao-colaborador-pol:
      url: http://gestao-colaborador-pol-api:8310
    extrato-comissao:
      url: http://extrato-comissao-api:8309

  email:
    enviar: true
    empresa-alias: XBRAIN
    emails:
    emails-solicitacao-ramal:

logging:
  level:
    org.springframework: 'ERROR'
    org.hibernate: 'ERROR'
