spring:

  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@//192.168.1.6:1521/DEV
    username: AUTENTICACAO
    password: py12nrk7

app-config:
  email:
    enviar: true
    emails: andre@xbrain.com.br