spring:
  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.50.2:1521/certificacao
    username: AUTENTICACAO
    password: 4ut3nt1c4c40
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximumPoolSize: 2

  redis:
    host: 172.10.10.2
    port: 6379

  rabbitmq:
    host: 172.10.10.3
    port: 5672
    username: xbrain
    password: xbrain

app-config:
  url-origin-cors: crt.conexaoclarobrasil.com.br,http://localhost
  timer-usuario:
    data-hora-inativar-usuario-a-partir-de: 2021-05-30T00:00:00.000
    email-usuario-viabilidade: INTEGRACAOMOTIVA@XBRAIN.COM.BR,INTEGRACAODDCOM@XBRAIN.COM.BR,INTEGRACAOCREDITCASH@XBRAIN.COM.BR

  url: https://autenticacao-crt.conexaoclarobrasil.com.br
  upload-foto-usuario: public/certificacao/autenticacao/usuario/foto/
  url-foto-usuario: ${app-config.minio.public}/certificacao/autenticacao/usuario/foto/

  services:
    autenticacao:
      url: http://autenticacao-api-crt:8096
    vendas:
      url: http://vendas-api-crt:8097
    parceiros-online:
      url: http://parceiros-online-api-crt:8099
    call:
      url: http://call-api-crt:8094
    mailing:
      url: http://mailing-api-crt:8095
    mailing-importacao:
      url: http://mailing-importacao-api-crt:8087
    equipe-venda:
      url: http://equipe-venda-api-crt:8089
    contato-crn:
      url: http://contato-crn-api-crt:8084
    comunicados:
      url: http://172.10.10.53:6553
    claro-indico:
      url: http://claro-indico-api-crt:8055
    agente-autorizado:
      url: http://agente-autorizado-api-crt:8300
    gestao:
      url: http://conexao-gestao-api-crt:8091
    notificacao:
      url: http://172.10.10.98:8081
    emails:
      url: http://192.168.50.4:6541
    integracao-vendas:
      url: http://integracao-vendas-api-crt:8086
    lei-nao-perturbe:
      url: http://lei-nao-perturbe-api:8109
    gestao-colaborador-pol:
      url: http://gestao-colaborador-pol-api:8310
    extrato-comissao:
      url: http://extrato-comissao-api:8309
    funil-prospeccao:
      url: http://funil-prospeccao-api-crt:8304
    localizacao:
      url: http://localizacao-api:8039
    integracao-claro-net:
      url: http://integracao-claro-net-api:8505
    suporte-vendas-bko:
      url: http://suporte-vendas-bko-api:8050
    checagem-credito:
      url: http://checagem-credito-api:8037
    backoffice:
      url: http://backoffice-api-crt:8101
    feriado-automacao:
      url: http://192.168.50.4:8078
    ata-reuniao:
      url: http://ata-reuniao-api:8308
    comunicados-pol:
      url: http://comunicados-pol-api:8312
    pgaa:
      url: http://pgaa-api:8354

  email:
    enviar: true
    empresa-alias: XBRAIN
    emails:
    emails-solicitacao-ramal:

logging:
  level:
    org.springframework: 'ERROR'
    org.hibernate: 'ERROR'

xbrain:
  logging:
    level: INFO
    appender: JSON
