spring:
  jpa:
    database: ORACLE
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:oracle:thin:@//192.168.50.2:1521/hmlg
    username: AUTENTICACAO
    password: 4ut3nt1c4c40
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximumPoolSize: 10

  redis:
    host: 172.10.10.80
    port: 6379

  rabbitmq:
    host: 172.10.10.70
    port: 5672
    username: xbrain
    password: xbrain

app-config:
  url-origin-cors: hom.conexaoclarobrasil.com.br,http://localhost,https://editor.swagger.io
  timer-usuario:
    data-hora-inativar-usuario-a-partir-de: 2021-05-30T00:00:00.000
    email-usuario-viabilidade: INTEGRACAOMOTIVA@XBRAIN.COM.BR,INTEGRACAODDCOM@XBRAIN.COM.BR,INTEGRACAOCREDITCASH@XBRAIN.COM.BR

  url: https://autenticacao-hom.conexaoclarobrasil.com.br
  upload-foto-usuario: public/homologacao/autenticacao/usuario/foto/
  url-foto-usuario: ${app-config.minio.public}/homologacao/autenticacao/usuario/foto/

  services:
    autenticacao:
      url: http://autenticacao-api-hom:8096
    vendas:
      url: http://vendas-api-hom:8097
    parceiros-online:
      url: http://172.10.10.76:8099
    call:
      url: http://call-api-hom:8094
    mailing:
      url: http://172.10.10.77:8095
    equipe-venda:
      url: http://equipe-venda-api-hom:8089
    contato-crn:
      url: http://contato-crn-api-hom:8084
    comunicados:
      url: http://172.10.10.53:6553
    claro-indico:
      url: http://172.10.10.55:8055
    agente-autorizado:
      url: http://agente-autorizado-api-hom:8300
    gestao:
      url: http://conexao-gestao-api-hom:8091
    notificacao:
      url: http://172.10.10.98:8081
    emails:
      url: http://email-hom:8080
    integracao-vendas:
      url: http://172.10.10.85:8086
    mailing-importacao:
      url: http://172.10.10.86:8087
    lei-nao-perturbe:
      url: http://lei-nao-perturbe-api:8109
    extrato-comissao:
      url: http://extrato-comissao-api:8309
    funil-prospeccao:
      url: http://172.10.10.113:8304
    localizacao:
      url: http://localizacao-api:8039
    gestao-colaborador-pol:
      url: http://gestao-colaborador-pol-api:8310
    integracao-claro-net:
      url: http://integracao-claro-net-api:8505
    suporte-vendas-bko:
      url: http://suporte-vendas-bko-api:8050
    checagem-credito:
      url: http://checagem-credito-api:8037
    backoffice:
      url: http://backoffice-api-hom:8101
    feriado-automacao:
      url: http://192.168.50.4:8078

  email:
    enviar: true
    empresa-alias: XBRAIN
    emails: angelica@xbrain.com.br,higor@xbrain.com.br,jose@xbrain.com.br,gabrielpuschel@xbrain.com.br,joaobarion@xbrain.com.br,matheusyoshiaki@xbrain.com.br,mirianynunes@xbrain.com.br,yurivieira@xbrain.com.br,lucassouza@xbrain.com.br
    emails-solicitacao-ramal: angelica@xbrain.com.br,higor@xbrain.com.br,valdecir@xbrain.com.br,jose@xbrain.com.br,gabrielpuschel@xbrain.com.br,joaobarion@xbrain.com.br,matheusyoshiaki@xbrain.com.br,mirianynunes@xbrain.com.br,yurivieira@xbrain.com.br,lucassouza@xbrain.com.br

logging:
  level:
    org.springframework: 'ERROR'
    org.hibernate: 'ERROR'

xbrain:
  logging:
    level: INFO
    appender: JSON
