logging:
  file: /home/xbrain/dev/autenticacao/dev.log
  level:
      org.springframework: 'ERROR'
      org.hibernate: 'ERROR'

spring:
  rabbitmq:
      host: 172.10.10.30
      port: 5671
      username: xbrain
      password: xbrain