spring:
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    jdbcUrl: jdbc:oracle:thin:@//192.168.1.6:1521/DEV
    username: AUTENTICACAO_TEST
    password: py12nrk7
    driverClassName: oracle.jdbc.OracleDriver

  datasource-parceiros:
    jdbcUrl: jdbc:oracle:thin:@//192.168.2.16:1521/XPROD
    username: parceiros_online
    password: jtr4ovhw
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 1

