app-config:
  url-servico-email: http://172.10.10.41:8080/emails/
  services:
    autenticacao:
      url: http://172.10.10.33:8096
    parceiros-online:
      url: http://172.10.10.36:8099
    call:
      url: http://172.10.10.38:8094
    vendas:
      url: http://172.10.10.34:8097

logging:
  file: /home/xbrain/dev/autenticacao/dev.log
  level:
      org.springframework: 'ERROR'
      org.hibernate: 'ERROR'

spring:
  rabbitmq:
      host: 172.10.10.30
      port: 5672
      username: xbrain
      password: xbrain