-- https://api.calendario.com.br/?ano=2018&token=RElPR09NQVJRVUVTQFhCUkFJTi5DT00uQlImaGFzaD0yNDI3NDgxMDc&json=true --
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (1, 'Ano Novo', '2018-01-01',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (2, 'Sexta-Feira Santa', '2018-03-30',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (3, 'Dia de Tiradentes', '2018-04-21',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (4, 'Dia do Trabalho', '2018-05-01',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (5, 'Independência do Brasil', '2018-09-07',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (6, 'Nossa Senhora Aparecida', '2018-10-12',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (7, 'Dia de Finados', '2018-11-02',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (8, 'Proclamação da República', '2018-11-15',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (9, 'Natal', '2018-12-25',  CURRENT_TIMESTAMP, 'V');
