-- FUNCIONALIDADES - PARCEIROS ONLINE --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (1, 'Visualizar Agentes Autorizados Geral', 'VISUALIZAR_AA_GERAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2, 'Visualizar Agentes Autorizados da própria Empresa e unidade', 'VISUALIZAR_AA_EMPRESA_UNIDADE', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3, 'Visualizar Agentes Autorizados Carteira', 'VISUALIZAR_AA_CARTEIRA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (4, 'Visualizar Agentes Autorizados Próprio', 'VISUALIZAR_AA_PROPRIO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (5, 'Gerenciar Equipe Venda', 'GERENCIAR_EQUIPE_VENDA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (6, 'Gerenciar Equipe Técnica', 'GERENCIAR_EQUIPE_TECNICA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (7, 'Gerenciar Usuários', 'GERENCIAR_USUARIOS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8, 'Emular Usuários', 'EMULAR_USUARIOS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (9, 'Gerenciar Perfis de Usuário', 'GERENCIAR_PERFIS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (10, 'Gerenciar Contratos', 'GERENCIAR_CONTRATOS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (11, 'Visualizar Notícias', 'VISUALIZAR_NOTICIAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (12, 'Agente Autorizado Aprovação Operação', 'AGENTE_AUTORIZADO_APROVACAO_OPERACAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (13, 'Agente Autorizado Aprovação MSO', 'AGENTE_AUTORIZADO_APROVACAO_MSO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (14, 'Aceite Agente Autorizado', 'ACEITE_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15, 'Visualizar Documentos do Agente Autorizado', 'VISUALIZAR_DOCUMENTOS_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16, 'Gerenciar Agentes Autorizados', 'GERENCIAR_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (17, 'Descredenciamento de Agente Autorizado', 'DESCREDENCIAR_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (18, 'Visualizar Comissionamento', 'VISUALIZAR_COMISSAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (19, 'PGAA Editar CheckList', 'PGAA_EDITAR_CHECKLIST', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20, 'PGAA Editar CheckList Observação AA', 'PGAA_EDITAR_CHECKLIST_OBSERVACAO_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (21, 'PGAA Aprovar CheckList', 'PGAA_APROVAR_CHECKLIST', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (22, 'PGAA Aceitar CheckList', 'PGAA_ACEITAR_CHECKLIST', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (23, 'Visualizar Agentes Autorizados Cidade', 'VISUALIZAR_AA_CIDADE', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (26, 'Agente Autorizado Aprovação MSO Novos Cadastros', 'AGENTE_AUTORIZADO_APROVACAO_MSO_NOVO_CADASTRO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (27, 'Agente Autorizado Aprovação MSO Descredenciamento Nacional', 'AGENTE_AUTORIZADO_APROVACAO_MSO_DESCREDENCIAMENTO_NAC', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (28, 'Captação de AA Extração', 'CAPTACAO_AA_EXTRACAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (29, 'Projeto Top Extração', 'PROJETO_TOP_EXTRACAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (30, 'Extração Simplificada', 'EXTRACAO_SIMPLIFICADA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (31, 'Extração de Categorias', 'EXTRACAO_CATEGORIAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (32, 'Viabilidade Consulta', 'VIABILIDADE_CONSULTA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (33, 'Projeto Top Upload', 'PROJETO_TOP_UPLOAD', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (34, 'Equipe Vendas Editar Líder', 'EQUIPE_VENDA_EDITAR_LIDER', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (37, 'Carteira Upload', 'CARTEIRA_UPLOAD', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (109, 'Gerenciar Comunicado Geral', 'GERENCIAR_COMUNICADO_GERAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (110, 'Gerenciar Comunicado Canal', 'GERENCIAR_COMUNICADO_CANAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (111, 'Gerenciar Canal Incentivos e Endomarketing', 'GERENCIAR_CANAL_INCENTIVOS_ENDOMARKETING', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (112, 'Gerenciar Canal Central de Notícias', 'GERENCIAR_CANAL_CENTRAL_NOTICIAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (113, 'Gerenciar Canal Informa', 'GERENCIAR_CANAL_INFORMA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (114, 'Gerenciar Canal Comunicação/Trade', 'GERENCIAR_CANAL_COMUNICACAO_TRADE', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (115, 'Gerenciar Canal Qualidade e Prt6ocessos', 'GERENCIAR_CANAL_QUALIDADE_PROCESSOS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (116, 'Gerenciar Canal Area do parceiro', 'GERENCIAR_CANAL_AREA_PARCEIRO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (117, 'Gerenciar Canal Produtos e ofertas', 'GERENCIAR_CANAL_PRODUTOS_OFERTAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (118, 'Gerenciar Canal Suporte Comercial', 'GERENCIAR_CANAL_SUPORTE_COMERCIAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (119, 'Gerenciar Canal Central Arquivos', 'GERENCIAR_CANAL_CENTRAL_ARQUIVOS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (121, 'Gerenciar Canal Treinamento', 'GERENCIAR_CANAL_TREINAMENTO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (120, 'Projeto Top Visualizar Planilha Metas', 'PROJTOP_VISUALIZAR_METAS', 2);

-- FUNCIONALIDADES - AUTENTICACAO --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2000, 'Gerenciar Usuários', 'AUT_GER_USUARIO', 1);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2001, 'Emular Usuários', 'AUT_EMULAR_USUARIO', 1);

-- FUNCIONALIDADES - VENDAS --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3000, 'Gerenciar Vendas', 'VDS_CAD_VENDA', 3);

-- FUNCIONALIDADES - SIMULADOR --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (4000, 'Gerenciar Produtos', 'SPR_GER_PRODUTO', 5);

-- XBRAIN  ADMIN --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 2000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 2001);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 3000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 4000);