-- FUNCIONALIDADES - PARCEIROS ONLINE --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (1, 'Visualizar Geral', 'POL_VISUALIZAR_GERAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2, 'Visualizar a própria Empresa e unidade', 'POL_VISUALIZAR_EMPRESA_UNIDADE', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3, 'Visualizar Carteira Hierarquia', 'POL_VISUALIZAR_CARTEIRA_HIERARQUIA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (4, 'Visualizar Próprio', 'POL_VISUALIZAR_PROPRIO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (5, 'Gerenciar Equipe Venda', 'POL_GERENCIAR_EQUIPE_VENDA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (6, 'Gerenciar Equipe Técnica', 'POL_GERENCIAR_EQUIPE_TECNICA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (11, 'Visualizar Notícias', 'POL_VISUALIZAR_NOTICIAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (12, 'Agente Autorizado Aprovação Operação', 'POL_AGENTE_AUTORIZADO_APROVACAO_OPERACAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (13, 'Agente Autorizado Aprovação MSO', 'POL_AGENTE_AUTORIZADO_APROVACAO_MSO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (14, 'Aceite Agente Autorizado', 'POL_ACEITE_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15, 'Visualizar Documentos do Agente Autorizado', 'POL_VISUALIZAR_DOCUMENTOS_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16, 'Gerenciar Agentes Autorizados', 'POL_GERENCIAR_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (17, 'Descredenciamento de Agente Autorizado', 'POL_DESCREDENCIAR_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (18, 'Visualizar Comissionamento', 'POL_VISUALIZAR_COMISSAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (23, 'Visualizar Cidade', 'POL_VISUALIZAR_CIDADE', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (26, 'Agente Autorizado Aprovação MSO Novos Cadastros', 'POL_AGENTE_AUTORIZADO_APROVACAO_MSO_NOVO_CADASTRO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (27, 'Agente Autorizado Aprovação MSO Descredenciamento Nacional', 'POL_AGENTE_AUTORIZADO_APROVACAO_MSO_DESCREDENCIAMENTO_NAC', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (28, 'Captação de AA Extração', 'POL_CAPTACAO_AA_EXTRACAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (29, 'Projeto Extração', 'POL_PROJETO_EXTRACAO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (31, 'Extração Simplificada', 'POL_EXTRACAO_SIMPLIFICADA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (32, 'Viabilidade Consulta', 'POL_VIABILIDADE_CONSULTA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (33, 'Extração de Categorias', 'POL_EXTRACAO_CATEGORIAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (34, 'Equipe Vendas Editar Líder', 'POL_EQUIPE_VENDA_EDITAR_LIDER', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (35, 'Extração Base AMX', 'POL_EXTRACAO_BASE_AMX', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (36, 'Projeto Upload', 'POL_PROJETO_UPLOAD', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (37, 'Carteira Upload', 'POL_CARTEIRA_UPLOAD', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (39, 'Remover Agente Autorizado Prospect', 'POL_REMOVER_AA_PROSPECT', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (40, 'Extração televendas agente autorizado', 'POL_EXTRACAO_TELEVENDAS_AA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (41, 'Gerenciar parceiro nacional', 'POL_GERENCIAR_PARCEIRO_NACIONAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (109, 'Gerenciar Comunicado Geral', 'POL_GERENCIAR_COMUNICADO_GERAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (110, 'Gerenciar Comunicado Canal', 'POL_GERENCIAR_COMUNICADO_CANAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (111, 'Gerenciar Canal Incentivos e Endomarketing', 'POL_GERENCIAR_CANAL_INCENTIVOS_ENDOMARKETING', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (112, 'Gerenciar Canal Central de Notícias', 'POL_GERENCIAR_CANAL_CENTRAL_NOTICIAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (113, 'Gerenciar Canal Informa', 'POL_GERENCIAR_CANAL_INFORMA', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (114, 'Gerenciar Canal Comunicação/Trade', 'POL_GERENCIAR_CANAL_COMUNICACAO_TRADE', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (115, 'Gerenciar Canal Qualidade e Processos', 'POL_GERENCIAR_CANAL_QUALIDADE_PROCESSOS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (116, 'Gerenciar Canal Area do parceiro', 'POL_GERENCIAR_CANAL_AREA_PARCEIRO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (117, 'Gerenciar Canal Produtos e ofertas', 'POL_GERENCIAR_CANAL_PRODUTOS_OFERTAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (118, 'Gerenciar Canal Suporte Comercial', 'POL_GERENCIAR_CANAL_SUPORTE_COMERCIAL', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (119, 'Gerenciar Canal Central Arquivos', 'POL_GERENCIAR_CANAL_CENTRAL_ARQUIVOS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (120, 'Projeto Visualizar Metas', 'POL_PROJETO_VISUALIZAR_METAS', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (121, 'Gerenciar Canal Treinamento', 'POL_GERENCIAR_CANAL_TREINAMENTO', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (122, 'Criar mensagem para Ouvidoria', 'POL_OUVIDORIA_ENVIAR_MENSAGEM', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (123, 'Responder a Mensagens da Ouvidoria', 'POL_OUVIDORIA_RESPONDER', 2);


-- FUNCIONALIDADES - AUTENTICACAO --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2000, 'Gerenciar Usuários', 'AUT_GER_USUARIO', 1);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2001, 'Emular Usuários', 'AUT_EMULAR_USUARIO', 1);

-- FUNCIONALIDADES - VENDAS --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3000, 'Gerenciar Vendas', 'VDS_CAD_VENDA', 3);

-- FUNCIONALIDADES - SIMULADOR --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (4000, 'Gerenciar Produtos', 'SPR_GER_PRODUTO', 5);

-- XBRAIN  ADMIN --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 2000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 2001);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 3000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 4000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 5);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 6);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 11);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 12);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 13);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 16);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 17);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 18);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 28);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 29);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 31);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 32);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 33);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 34);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 35);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 36);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 37);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 39);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 40);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 41);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 109);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 122);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 123);


-- AGENTE AUTORIZADO --
-- SOCIO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 41, 40, 3000);