//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.10.29 at 09:49:12 AM BRST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.mensagem.xbrain.com.br/")
package br.com.xbrain.autenticacao.infra.mensagemWs.wsdl;
