CREATE SEQUENCE SEQ_ESPECIALIDADE START WITH 1 INCREMENT BY 1;

CREATE TABLE ESPECIALIDADE (
    ID INTEGER NOT NULL,
    NOME_ESPECIALIDADE VARCHAR(255) NOT NULL,
    CODIGO_ESPECIALIDADE VARCHAR(255) NOT NULL,
    STATUS_ESPECIALIDADE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
)