CREATE SEQUENCE SEQ_ESTUDANTE START WITH 1 INCREMENT BY 1;

CREATE TABLE ESTUDANTE (
    ID INTEGER PRIMARY KEY,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,

    -- Campos de Endereco
    CEP VARCHAR(10) NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,

    -- Campos de Contato
    TELEFONE_CELULAR VARCHAR(20),
    WHATSAPP VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100)
);
