CREATE SEQUENCE SEQ_AGENDAMENTO START WITH 1 INCREMENT BY 1;

CREATE TABLE AGENDAMENTO (
    ID INTEGER NOT NULL,
    DATA_AGENDAMENTO TIMESTAMP NOT NULL,
    FK_ESTUDANTE INTEGER NOT NULL,
    FK_PROFESSOR INTEGER NOT NULL,
    CONTEUDO VARCHAR(255) NOT NULL,
    STATUS_AGENDAMENTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_ESTUDANTE) REFERENCES ESTUDANTE (ID),
    FOREIGN KEY (FK_PROFESSOR) REFERENCES PROFESSOR (ID)
)