CREATE SEQUENCE SEQ_NIVEL START WITH 1 INCREMENT BY 1;

CREATE TABLE NIVEL (
    ID INTEGER NOT NULL,
    NOME_NIVEL VARCHAR(255) NOT NULL,
    CODIGO_NIVEL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
)