INSERT INTO NIVEL (ID, NOME_NIVEL, CODIGO_NIVEL) VALUES (nextval('SEQ_NIVEL'), 'Admin', 'ADMIN');
INSERT INTO NIVEL (ID, NOME_NIVEL, CODIGO_NIVEL) VALUES (nextval('SEQ_NIVEL'), 'Professor', 'PROFESSOR' );
INSERT INTO NIVEL (ID, NOME_NIVEL, CODIGO_NIVEL) VALUES (nextval('SEQ_NIVEL'), 'Estudante', 'ESTUDANTE');
