CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE USUARIO (
    ID INTEGER NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    ESPECIALIDADE VARCHAR(255),
    FK_NIVEL INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CEP VARCHAR(10),
    LOGRADOURO VARCHAR(255),
    NUMERO VARCHAR(20),
    BAIRRO VARCHAR(100),
    ESTADO VARCHAR(50),
    CIDADE VARCHAR(100),
    TELEFONE_CELULAR VARCHAR(20),
    WHATSAPP VARCHAR(20),
    EMAIL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_NIVEL) REFERENCES NIVEL (ID)

)