package br.com.xbrain.autenticacao.modules.feeder.service;

import br.com.xbrain.autenticacao.modules.usuario.enums.CodigoCargo;

import java.util.List;

import static br.com.xbrain.autenticacao.modules.usuario.enums.CodigoCargo.*;

public class FeederUtil {

    public static final Integer FUNCIONALIDADE_GERENCIAR_LEAD_ID = 15000;
    public static final Integer FUNCIONALIDADE_TRATAR_LEAD_ID = 3046;
    public static final String OBSERVACAO_FEEDER =
        "AGENTE AUTORIZADO COM PERMISSÃO DE FEEDER.";
    public static final String OBSERVACAO_NAO_FEEDER =
        "AGENTE AUTORIZADO SEM PERMISSÃO DE FEEDER.";
    public static final String ALTERACAO_CPF_E_EMAIL_FEEDER = "Usuário excluído do Feeder. CPF e Email alterados automaticamente";
    public static final List<Integer> FUNCIONALIDADES_FEEDER_PARA_AA = List.of(15000, 15005, 15012, 3046);
    public static final List<Integer> FUNCIONALIDADES_FEEDER_PARA_MSO_EMPRESARIAL = List.of(15000, 15007, 15012);
    public static final List<Integer> FUNCIONALIDADES_FEEDER_PARA_MSO_RESIDENCIAL = List.of(15000, 15001, 15002, 15003,
        15006, 15007, 15008, 15009, 15010, 15011, 15012, 15013, 15014, 20007);

    public static final List<Integer> FUNCIONALIDADES_FEEDER = List.of(15000, 15005, 15012);
    public static final List<CodigoCargo> CARGOS_BACKOFFICE_E_SOCIO_SECUNDARIO = List.of(AGENTE_AUTORIZADO_BACKOFFICE_TELEVENDAS,
        AGENTE_AUTORIZADO_BACKOFFICE_D2D, AGENTE_AUTORIZADO_BACKOFFICE_TEMP, AGENTE_AUTORIZADO_BACKOFFICE_TELEVENDAS_RECEPTIVO,
        AGENTE_AUTORIZADO_GERENTE, AGENTE_AUTORIZADO_COORDENADOR, AGENTE_AUTORIZADO_SOCIO_SECUNDARIO);
    public static final List<CodigoCargo> CARGOS_BACKOFFICE_AND_SOCIO_PRINCIPAL_AA = List.of(
        AGENTE_AUTORIZADO_BACKOFFICE_TELEVENDAS, AGENTE_AUTORIZADO_BACKOFFICE_D2D,
        AGENTE_AUTORIZADO_BACKOFFICE_TEMP, AGENTE_AUTORIZADO_BACKOFFICE_TELEVENDAS_RECEPTIVO,
        AGENTE_AUTORIZADO_SOCIO);
    public static final List<CodigoCargo> CODIGOS_CARGOS_VENDEDORES_FEEDER_E_SOCIO_PRINCIPAL =
        List.of(AGENTE_AUTORIZADO_VENDEDOR_D2D, AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D, AGENTE_AUTORIZADO_SOCIO);
    public static final List<CodigoCargo> CODIGOS_CARGOS_VENDEDORES_FEEDER =
        List.of(AGENTE_AUTORIZADO_VENDEDOR_D2D, AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D);

    public static final List<Integer> FUNCIONALIDADES_FEEDER_PARA_REPROCESSAR_COORD_GER = List.of(15000, 15005, 15012);
}
