package br.com.xbrain.autenticacao.modules.usuario.helpers;

import br.com.xbrain.autenticacao.modules.usuario.dto.CidadesUfsRequest;

import java.util.List;

public class CidadeUfHelper {

    public static CidadesUfsRequest cidadesUfs() {
        return CidadesUfsRequest.builder()
            .cidades(umaListaCidades())
            .ufs(umaListaUfs())
            .build();
    }

    public static List<String> umaListaCidades() {
        return List.of("LONDRINA", "MARINGA", "CURITIBA", "CARAUBAS");
    }

    public static List<String> umaListaUfs() {
        return List.of("PR", "PB", "RN");
    }

    public static CidadesUfsRequest cidadesUfsParaTestePartition() {
        return CidadesUfsRequest.builder()
            .cidades(umaListaCom1200Cidades())
            .ufs(umaListaCompletaUfs())
            .build();
    }

    public static List<String> umaListaCompletaUfs() {
        return List.of(
            "AC",
            "AL",
            "AM",
            "AP",
            "BA",
            "CE",
            "DF",
            "ES",
            "GO",
            "MA",
            "MG",
            "MS",
            "MT",
            "PA",
            "PB",
            "PE",
            "PI",
            "PR",
            "RJ",
            "RN",
            "RO",
            "RR",
            "RS",
            "SC",
            "SE",
            "SP",
            "TO"
        );
    }

    public static List<String> umaListaCom1200Cidades() {
        return List.of(
            "AXIXA",
            "AXIXA DO TOCANTINS",
            "BABACULANDIA",
            "BACABEIRA",
            "BACURI",
            "BACURITUBA",
            "BADY BASSITT",
            "BAEPENDI",
            "BAGE",
            "BAIA DA TRAICAO",
            "BAIA FORMOSA",
            "BAIANOPOLIS",
            "BAIAO",
            "BAIXA GRANDE",
            "BAIXA GRANDE DO RIBEIRO",
            "BAIXIO",
            "BAIXO GUANDU",
            "BALDIM",
            "BALIZA",
            "BALNEARIO ARROIO DO SILVA",
            "BALNEARIO BARRA DO SUL",
            "BALNEARIO CAMBORIU",
            "BALNEARIO GAIVOTA",
            "BALNEARIO PINHAL",
            "BALNEARIO RINCAO",
            "BALSAMO",
            "BALSAS",
            "BAMBUI",
            "BANABUIU",
            "BANANAL",
            "BANANEIRAS",
            "BANDEIRA",
            "BANDEIRA DO SUL",
            "BANDEIRANTE",
            "BANDEIRANTES",
            "BANDEIRANTES",
            "BANDEIRANTES DO TOCANTINS",
            "BANZAE",
            "BARAO DE COCAIS",
            "BARAO DE COTEGIPE",
            "BARAO DE GRAJAU",
            "BARAO DE MELGACO",
            "BARAO DE MONTE ALTO",
            "BARAO DO TRIUNFO",
            "BARAUNA",
            "BARAUNA",
            "BARBACENA",
            "BARBALHA",
            "BARBOSA",
            "BARBOSA FERRAZ",
            "BARCARENA",
            "BARCELONA",
            "BARCELOS",
            "BARIRI",
            "BARRA",
            "BARRA BONITA",
            "BARRA D ALCANTARA",
            "BARRA DA ESTIVA",
            "BARRA DE GUABIRABA",
            "BARRA DE SANTA ROSA",
            "BARRA DE SANTANA",
            "BARRA DE SANTO ANTONIO",
            "BARRA DE SAO FRANCISCO",
            "BARRA DE SAO MIGUEL",
            "BARRA DE SAO MIGUEL",
            "BARRA DO BUGRES",
            "BARRA DO CHAPEU",
            "BARRA DO CHOCA",
            "BARRA DO GARCAS",
            "BARRA DO GUARITA",
            "BARRA DO JACARE",
            "BARRA DO MENDES",
            "BARRA DO OURO",
            "BARRA DO RIO AZUL",
            "BARRA DO ROCHA",
            "BARRA DOS COQUEIROS",
            "BARRA FUNDA",
            "BARRA LONGA",
            "BARRA MANSA",
            "BARRA VELHA",
            "BARRACAO",
            "BARRACAO",
            "BARRAS",
            "BARREIRA",
            "BARREIRAS",
            "BARREIRAS DO PIAUI",
            "BARREIRINHA",
            "BARREIRINHAS",
            "BARREIROS",
            "BARRETOS",
            "BARRINHA",
            "BARRO",
            "BARRO ALTO",
            "BARRO ALTO",
            "BARRO DURO",
            "BARRO PRETO",
            "BARROCAS",
            "BARROLANDIA",
            "BARROQUINHA",
            "BARROSO",
            "BARUERI",
            "BASTOS",
            "BATAGUACU",
            "BATAGUASSU",
            "BATAIPORA",
            "BATALHA",
            "BATAYPORA",
            "BATURITE",
            "BAURU",
            "BEBEDOURO",
            "BEBERIBE",
            "BELA CRUZ",
            "BELA VISTA",
            "BELA VISTA DE GOIAS",
            "BELA VISTA DE MINAS",
            "BELA VISTA DO MARANHAO",
            "BELA VISTA DO PIAUI",
            "BELA VISTA DO TOLDO",
            "BELEM",
            "BELEM",
            "BELEM",
            "BELEM DE MARIA",
            "BELEM DO BREJO DO CRUZ",
            "BELEM DO PIAUI",
            "BELMIRO BRAGA",
            "BELMONTE",
            "BELMONTE",
            "BELO CAMPO",
            "BELO HORIZONTE",
            "BELO JARDIM",
            "BELO MONTE",
            "BELO ORIENTE",
            "CASTRO ALVES",
            "CATAGUASES",
            "CATALAO",
            "CATANDUVA",
            "CATANDUVAS",
            "CATANDUVAS",
            "CATARINA",
            "CATAS ALTAS",
            "CATAS ALTAS DA NORUEGA",
            "CATINGUEIRA",
            "CATOLANDIA",
            "CATOLE DO ROCHA",
            "CATU",
            "CATUIPE",
            "CATUJI",
            "CATURAI",
            "CATURAMA",
            "CATURITE",
            "CATUTI",
            "CAUCAIA",
            "CAVALCANTE",
            "CAXAMBU",
            "CAXIAS",
            "CAXIAS DO SUL",
            "CAXINGO",
            "CEDRAL",
            "CEDRO",
            "CEDRO",
            "CEDRO DE SAO JOAO",
            "CEDRO DO ABAETE",
            "CEILANDIA",
            "CELSO RAMOS",
            "CENTENARIO",
            "CENTENARIO",
            "CENTENARIO DO SUL",
            "CENTRAL",
            "CENTRAL DE MINAS",
            "CENTRAL DO MARANHAO",
            "CENTRALINA",
            "CENTRO DO GUILHERME",
            "CEREJEIRAS",
            "CERES",
            "CERQUEIRA CESAR",
            "CERQUILHO",
            "CERRITO",
            "BELO VALE",
            "BELTERRA",
            "BENEDITINOS",
            "BENEDITO NOVO",
            "BENEVIDES",
            "BENJAMIN CONSTANT",
            "BENJAMIN CONSTANT DO SUL",
            "BENTO FERNANDES",
            "BENTO GONCALVES",
            "BEQUIMAO",
            "BERILO",
            "BERIZAL",
            "BERNARDINO BATISTA",
            "BERNARDINO DE CAMPOS",
            "BERNARDO DO MEARIM",
            "BERNARDO SAYAO",
            "BERTIOGA",
            "BERTOLINIA",
            "BERTOPOLIS",
            "BETANIA",
            "BETANIA DO PIAUI",
            "BETIM",
            "BEZERROS",
            "BIAS FORTES",
            "BICAS",
            "BIGUACU",
            "BILAC",
            "BIQUINHAS",
            "BIRITIBA-MIRIM",
            "BIRITINGA",
            "BITURUNA",
            "BOA ESPERANCA",
            "BOA ESPERANCA DO IGUACU",
            "BOA ESPERANCA DO SUL",
            "BOA HORA",
            "BOA NOVA",
            "BOA VENTURA",
            "BOA VIAGEM",
            "BOA VISTA",
            "BOA VISTA",
            "BOA VISTA DA APARECIDA",
            "BOA VISTA DO BURICA",
            "BOA VISTA DO CADEADO",
            "BOA VISTA DO GURUPI",
            "BOA VISTA DO INCRA",
            "BOA VISTA DO SUL",
            "BOA VISTA DO TUPIM",
            "BOCA DA MATA",
            "BOCA DO ACRE",
            "BOCAINA",
            "BOCAINA",
            "BOCAINA DE MINAS",
            "BOCAINA DO SUL",
            "BOCAIUVA",
            "BOCAIUVA DO SUL",
            "BODO",
            "BODOCO",
            "BODOQUENA",
            "BOITUVA",
            "BOM CONSELHO",
            "BOM DESPACHO",
            "BOM JARDIM",
            "BOM JARDIM",
            "BOM JARDIM",
            "BOM JARDIM DA SERRA",
            "BOM JARDIM DE GOIAS",
            "BOM JARDIM DE MINAS",
            "BOM JESUS",
            "BOM JESUS",
            "BOM JESUS",
            "BOM JESUS",
            "BOM JESUS",
            "BOM JESUS DA LAPA",
            "BOM JESUS DA PENHA",
            "BOM JESUS DA SERRA",
            "BOM JESUS DAS SELVAS",
            "BOM JESUS DE GOIAS",
            "BOM JESUS DO AMPARO",
            "BOM JESUS DO ARAGUAIA",
            "BOM JESUS DO GALHO",
            "BOM JESUS DO ITABAPOANA",
            "BOM JESUS DO NORTE",
            "BOM JESUS DO SUL",
            "BOM JESUS DO TOCANTINS",
            "BOM JESUS DO TOCANTINS",
            "BOM JESUS DOS PERDOES",
            "BOM PRINCIPIO DO PIAUI",
            "BOM PROGRESSO",
            "BOM REPOUSO",
            "BOM RETIRO",
            "BOM RETIRO DO SUL",
            "BOM SUCESSO",
            "BOM SUCESSO",
            "BOM SUCESSO",
            "BOM SUCESSO DO SUL",
            "BONFIM",
            "BONFIM",
            "BONFIM DO PIAUI",
            "BONFINOPOLIS",
            "BONFINOPOLIS DE MINAS",
            "BONINAL",
            "BONITO",
            "BONITO",
            "BONITO",
            "BONITO",
            "BONITO DE MINAS",
            "BONITO DE SANTA FE",
            "BONOPOLIS",
            "BOQUEIRAO",
            "BOQUEIRAO DO LEAO",
            "BOQUEIRAO DO PIAUI",
            "BOQUIM",
            "BOQUIRA",
            "BORA",
            "BORACEIA",
            "BORBA",
            "BORBOREMA",
            "BORBOREMA",
            "BORDA DA MATA",
            "BOREBI",
            "BORRAZOPOLIS",
            "BOTELHOS",
            "BOTUCATU",
            "BOTUMIRIM",
            "BOTUPORA",
            "BOTUVERA",
            "BOZANO",
            "BRACO DO NORTE",
            "BRAGA",
            "BRAGANEY",
            "BRANQUINHA",
            "BRAS PIRES",
            "BRASIL NOVO",
            "BRASILANDIA",
            "BRASILANDIA DE MINAS",
            "BRASILANDIA DO SUL",
            "BRASILANDIA DO TOCANTINS",
            "BRASILEIA",
            "BRASILEIRA",
            "BRASILIA",
            "BRASILIA DE MINAS",
            "BRASNORTE",
            "BRASOPOLIS",
            "BRAUNA",
            "BRAUNAS",
            "BRAZABRANTES",
            "BRAZLANDIA",
            "BREJAO",
            "BREJINHO",
            "BREJINHO DE NAZARE",
            "BREJO",
            "BREJO ALEGRE",
            "BREJO DA MADRE DE DEUS",
            "BREJO DE AREIA",
            "BREJO DO CRUZ",
            "BREJO DOS SANTOS",
            "BREJO GRANDE",
            "BREJO SANTO",
            "BREJOES",
            "BREJOLANDIA",
            "BREU BRANCO",
            "BREVES",
            "BRITANIA",
            "BRODOSQUI",
            "BRODOWSKI",
            "BROTAS DE MACAUBAS",
            "BRUMADINHO",
            "BRUMADO",
            "BRUNOPOLIS",
            "BRUSQUE",
            "BUENO BRANDAO",
            "BUENOPOLIS",
            "BUENOS AIRES",
            "BUERAREMA",
            "BUGRE",
            "BUIQUE",
            "BUJARI",
            "BUJARU",
            "BURITAMA",
            "BURITI",
            "BURITI ALEGRE",
            "BURITI DE GOIAS",
            "BURITI DO TOCANTINS",
            "BURITI DOS LOPES",
            "BURITI DOS MONTES",
            "BURITICUPU",
            "BURITINOPOLIS",
            "BURITIRAMA",
            "BURITIRANA",
            "BURITIS",
            "BURITIS",
            "BURITIZAL",
            "BURITIZEIRO",
            "BUTIA",
            "CAAPIRANGA",
            "CAAPORA",
            "CAARAPO",
            "CAATIBA",
            "CABACEIRAS",
            "CABACEIRAS DO PARAGUACU",
            "CABECEIRA GRANDE",
            "CABECEIRAS",
            "CABECEIRAS DO PIAUI",
            "CABEDELO",
            "CABIXI",
            "CABO DE SANTO AGOSTINHO",
            "CABO FRIO",
            "CABO VERDE",
            "CABREUVA",
            "CABROBO",
            "CACADOR",
            "CACAPAVA",
            "CACAPAVA DO SUL",
            "CACAULANDIA",
            "CACERES",
            "CACHOEIRA",
            "CACHOEIRA ALTA",
            "CACHOEIRA DA PRATA",
            "CACHOEIRA DE GOIAS",
            "CACHOEIRA DE MINAS",
            "CACHOEIRA DE PAJEU",
            "CACHOEIRA DO PIRIA",
            "CACHOEIRA DO SUL",
            "CACHOEIRA DOS INDIOS",
            "CACHOEIRA DOURADA",
            "CACHOEIRA DOURADA",
            "CACHOEIRA GRANDE",
            "CACHOEIRINHA",
            "CACHOEIRINHA",
            "CACHOEIRO DE ITAPEMIRIM",
            "CACIMBA DE AREIA",
            "CACIMBA DE DENTRO",
            "CACIMBAS",
            "CACOAL",
            "CACONDE",
            "CACU",
            "CACULE",
            "CAEM",
            "CAETANOPOLIS",
            "CAETANOS",
            "CAETE",
            "CAETES",
            "CAETITE",
            "CAFARNAUM",
            "CAFEARA",
            "CAFELANDIA",
            "CAFELANDIA",
            "CAFEZAL DO SUL",
            "CAIANA",
            "CAIAPONIA",
            "CAIBATE",
            "CAICARA",
            "CAICARA",
            "CAICARA DO NORTE",
            "CAICO",
            "CAIEIRAS",
            "CAIRU",
            "CAIUA",
            "CAJAMAR",
            "CAJAPIO",
            "CAJARI",
            "CAJAZEIRAS",
            "CAJAZEIRAS DO PIAUI",
            "CAJAZEIRINHAS",
            "CAJOBI",
            "CAJUEIRO",
            "CAJURI",
            "CAJURU",
            "CALCADO",
            "CALDAS",
            "CALDAS BRANDAO",
            "CALDAS NOVAS",
            "CALDAZINHA",
            "CALDEIRAO GRANDE",
            "CALDEIRAO GRANDE DO PIAUI",
            "CALIFORNIA",
            "CALMON",
            "CALUMBI",
            "CAMACAN",
            "CAMACARI",
            "CAMACHO",
            "CAMAMU",
            "CAMANDUCAIA",
            "CAMAPUA",
            "CAMAQUA",
            "CAMARAGIBE",
            "CAMARGO",
            "CAMBE",
            "CAMBIRA",
            "CAMBORIU",
            "CAMBUCI",
            "CAMBUI",
            "CAMBUQUIRA",
            "CAMETA",
            "CAMOCIM",
            "CAMPANARIO",
            "CAMPANHA",
            "CAMPESTRE",
            "CAMPESTRE",
            "CAMPESTRE DE GOIAS",
            "CAMPESTRE DO MARANHAO",
            "CAMPINA DAS MISSOES",
            "CAMPINA DO SIMAO",
            "CAMPINA GRANDE",
            "CAMPINA GRANDE DO SUL",
            "CAMPINA VERDE",
            "CAMPINACU",
            "CAMPINAPOLIS",
            "CAMPINAS",
            "CAMPINAS DO PIAUI",
            "CAMPINAS DO SUL",
            "CAMPINORTE",
            "CAMPO ALEGRE",
            "CAMPO ALEGRE",
            "CAMPO ALEGRE DE GOIAS",
            "CAMPO ALEGRE DE LOURDES",
            "CAMPO AZUL",
            "CAMPO BELO",
            "CAMPO BELO DO SUL",
            "CAMPO BOM",
            "CAMPO DE SANTANA",
            "CAMPO DO BRITO",
            "CAMPO DO MEIO",
            "CAMPO ERE",
            "CAMPO FLORIDO",
            "CAMPO FORMOSO",
            "CAMPO GRANDE",
            "CAMPO GRANDE",
            "CAMPO GRANDE",
            "CAMPO GRANDE DO PIAUI",
            "CAMPO LARGO",
            "CAMPO LARGO DO PIAUI",
            "CAMPO LIMPO DE GOIAS",
            "CAMPO LIMPO PAULISTA",
            "CAMPO MAGRO",
            "ABADIA DE GOIAS",
            "ABADIA DOS DOURADOS",
            "ABADIANIA",
            "ABAETE",
            "ABAETETUBA",
            "ABAIARA",
            "ABAIRA",
            "ABARE",
            "ABATIA",
            "ABDON BATISTA",
            "ABELARDO LUZ",
            "ABRE CAMPO",
            "ABREU E LIMA",
            "ABREULANDIA",
            "ACAIACA",
            "ACAJUTIBA",
            "ACARA",
            "ACARAPE",
            "ACARAU",
            "ACARI",
            "ACAUA",
            "ACOPIARA",
            "ACORIZAL",
            "ACRELANDIA",
            "ACREUNA",
            "ACU",
            "ACUCENA",
            "ADAMANTINA",
            "ADELANDIA",
            "ADOLFO",
            "ADRIANOPOLIS",
            "ADUSTINA",
            "AFOGADOS DA INGAZEIRA",
            "AFONSO BEZERRA",
            "AFONSO CLAUDIO",
            "AFONSO CUNHA",
            "AFRANIO",
            "AFUA",
            "AGRESTINA",
            "AGRICOLANDIA",
            "AGRONOMICA",
            "AGUA BOA",
            "AGUA BOA",
            "AGUA BRANCA",
            "AGUA BRANCA",
            "AGUA CLARA",
            "AGUA COMPRIDA",
            "AGUA DOCE",
            "AGUA DOCE DO MARANHAO",
            "AGUA FRIA",
            "AGUA FRIA DE GOIAS",
            "AGUA LIMPA",
            "AGUA NOVA",
            "AGUA PRETA",
            "AGUA SANTA",
            "AGUAI",
            "AGUANIL",
            "AGUAS BELAS",
            "AGUAS CLARAS",
            "AGUAS DA PRATA",
            "AGUAS DE SANTA BARBARA",
            "AGUAS DE SAO PEDRO",
            "AGUAS FORMOSAS",
            "AGUAS FRIAS",
            "AGUAS LINDAS",
            "AGUAS LINDAS DE GOIAS",
            "AGUAS VERMELHAS",
            "AGUDO",
            "AGUDOS",
            "AGUDOS DO SUL",
            "AGUIA BRANCA",
            "AGUIAR",
            "AGUIARNOPOLIS",
            "AIMORES",
            "AIQUARA",
            "AIUABA",
            "AIURUOCA",
            "ALAGOA",
            "ALAGOA GRANDE",
            "ALAGOINHA",
            "ALAGOINHA",
            "ALAGOINHA",
            "ALAGOINHAS",
            "ALBERTINA",
            "ALCANTARA",
            "ALCANTARAS",
            "ALCANTIL",
            "ALCINOPOLIS",
            "ALCOBACA",
            "ALDEIAS ALTAS",
            "ALECRIM",
            "ALEGRE",
            "ALEGRETE",
            "ALEGRETE DO PIAUI",
            "ALEGRIA",
            "ALEM PARAIBA",
            "ALENQUER",
            "ALEXANDRIA",
            "ALEXANIA",
            "ALFENAS",
            "ALFREDO CHAVES",
            "ALFREDO MARCONDES",
            "ALFREDO VASCONCELOS",
            "ALHANDRA",
            "ALIANCA",
            "ALIANCA DO TOCANTINS",
            "ALMADINA",
            "ALMAS",
            "ALMENARA",
            "ALMINO AFONSO",
            "ALMIRANTE TAMANDARE",
            "ALOANDIA",
            "ALPERCATA",
            "ALPESTRE",
            "ALPINOPOLIS",
            "ALTA FLORESTA",
            "ALTA FLORESTA D OESTE",
            "ALTAIR",
            "ALTAMIRA",
            "ALTAMIRA DO MARANHAO",
            "ALTAMIRA DO PARANA",
            "ALTANEIRA",
            "ALTEROSA",
            "ALTINOPOLIS",
            "ALTO ALEGRE",
            "ALTO ALEGRE",
            "ALTO ALEGRE DO PINDARE",
            "ALTO ALEGRE DOS PARECIS",
            "ALTO ARAGUAIA",
            "ALTO BOA VISTA",
            "ALTO CAPARAO",
            "ALTO DA BOA VISTA",
            "ALTO DO RODRIGUES",
            "ALTO FELIZ",
            "ALTO GARCAS",
            "ALTO HORIZONTE",
            "ALTO JEQUITIBA",
            "ALTO LONGA",
            "ALTO PARAGUAI",
            "ALTO PARAISO",
            "ALTO PARAISO",
            "ALTO PARAISO DE GOIAS",
            "ALTO PARNAIBA",
            "ALTO PIQUIRI",
            "ALTO RIO DOCE",
            "ALTO RIO NOVO",
            "ALTO SANTO",
            "ALTO TAQUARI",
            "ALTONIA",
            "ALUMINIO",
            "ALVARAES",
            "ALVARENGA",
            "ALVARES FLORENCE",
            "ALVARES MACHADO",
            "ALVINLANDIA",
            "ALVINOPOLIS",
            "ALVORADA",
            "ALVORADA",
            "ALVORADA D OESTE",
            "ALVORADA DE MINAS",
            "ALVORADA DO GURGUEIA",
            "ALVORADA DO NORTE",
            "ALVORADA DO SUL",
            "AMAJARI",
            "AMAMBAI",
            "AMAPA DO MARANHAO",
            "AMAPARI",
            "AMARAJI",
            "AMARAL FERRADOR",
            "AMARALINA",
            "AMARANTE DO MARANHAO",
            "AMARGOSA",
            "AMELIA RODRIGUES",
            "AMERICA DOURADA",
            "AMERICANA",
            "AMERICANO DO BRASIL",
            "AMERICO BRASILIENSE",
            "AMERICO DE CAMPOS",
            "AMONTADA",
            "AMORINOPOLIS",
            "AMPARO",
            "AMPARO DE SAO FRANCISCO",
            "AMPARO DA SERRA",
            "AMPERE",
            "ANADIA",
            "ANAGE",
            "ANAHY",
            "ANAJAS",
            "ANAJATUBA",
            "ANALANDIA",
            "ANAMA",
            "ANANAS",
            "ANANINDEUA",
            "ANAPOLIS",
            "ANAPURUS",
            "ANASTACIO",
            "ANAURILANDIA",
            "ANCHIETA",
            "ANDARAI",
            "ANDIRA",
            "ANDORINHA",
            "ANDRADAS",
            "ANDRELANDIA",
            "ANGATUBA",
            "ANGELANDIA",
            "ANGELICA",
            "ANGELIM",
            "ANGELINA",
            "ANGICAL",
            "ANGICAL DO PIAUI",
            "ANGICO",
            "ANGICOS",
            "ANGRA DOS REIS",
            "ANGUERA",
            "ANGULO",
            "ANHANGUERA",
            "ANHEMBI",
            "ANHUMAS",
            "ANICUNS",
            "ANISIO DE ABREU",
            "ANITAPOLIS",
            "ANORI",
            "ANTA GORDA",
            "ANTAS",
            "ANTONINA",
            "ANTONINA DO NORTE",
            "ANTONIO CARDOSO",
            "ANTONIO CARLOS",
            "ANTONIO CARLOS",
            "ANTONIO DIAS",
            "ANTONIO GONCALVES",
            "ANTONIO JOAO",
            "ANTONIO MARTINS",
            "ANTONIO PRADO",
            "ANTONIO PRADO DE MINAS",
            "APARECIDA",
            "APARECIDA D OESTE",
            "APARECIDA DE GOIANIA",
            "APARECIDA DO RIO DOCE",
            "APARECIDA DO RIO NEGRO",
            "APARECIDA DO TABOADO",
            "APERIBE",
            "APIACA",
            "APIACAS",
            "APIAI",
            "APICUM-ACU",
            "APIUNA",
            "APODI",
            "APORA",
            "APORE",
            "APUAREMA",
            "APUIARES",
            "AQUIDABA",
            "AQUIDAUANA",
            "ARABUTA",
            "ARACAGI",
            "ARACAI",
            "ARACAJU",
            "ARACARIGUAMA",
            "ARACAS",
            "ARACATI",
            "ARACATU",
            "ARACI",
            "ARACITABA",
            "ARACOIABA",
            "ARACOIABA DA SERRA",
            "ARACU",
            "ARACUAI",
            "ARAGARCAS",
            "ARAGOIANIA",
            "ARAGOMINAS",
            "ARAGUACEMA",
            "ARAGUACU",
            "ARAGUAIANA",
            "ARAGUAINA",
            "ARAGUAINHA",
            "ARAGUANA",
            "ARAGUANA",
            "ARAGUAPAZ",
            "ARAGUATINS",
            "ARAIOSES",
            "ARAL MOREIRA",
            "ARAMARI",
            "ARAMINA",
            "ARANTINA",
            "ARAPEI",
            "ARAPIRACA",
            "ARAPOEMA",
            "ARAPONGA",
            "ARAPONGAS",
            "ARAPORA",
            "ARAPUA",
            "ARAPUA",
            "ARAPUTANGA",
            "ARAQUARI",
            "ARARA",
            "ARARANGUA",
            "ARARAQUARA",
            "ARARAS",
            "ARARI",
            "ARARICA",
            "ARARIPE",
            "ARARIPINA",
            "ARARUAMA",
            "ARARUNA",
            "ARATACA",
            "ARATIBA",
            "ARATUIPE",
            "ARAUA",
            "ARAUCARIA",
            "ARAUJOS",
            "ARAXA",
            "ARCEBURGO",
            "ARCOS",
            "ARCOVERDE",
            "AREADO",
            "AREAL",
            "AREALVA",
            "AREIA",
            "AREIA BRANCA",
            "AREIA BRANCA",
            "AREIAL",
            "AREIAS",
            "AREIOPOLIS",
            "ARENAPOLIS",
            "ARENOPOLIS",
            "AREZ",
            "ARGIRITA",
            "ARICANDUVA",
            "ARINOS",
            "ARIPUANA",
            "ARIQUEMES",
            "ARMAZEM",
            "ARNEIROZ",
            "AROAZES",
            "AROEIRAS DO ITAIM",
            "ARRAIAL",
            "ARRAIAL DO CABO",
            "ARRAIAS",
            "ARROIO DO MEIO",
            "ARROIO DO SAL",
            "ARROIO DO TIGRE",
            "ARROIO DOS RATOS",
            "ARROIO GRANDE",
            "ARTUR NOGUEIRA",
            "ARUANA",
            "ARUJA",
            "ARVOREDO",
            "ASPASIA",
            "ASSAI",
            "ASSIS BRASIL",
            "ASSIS CHATEAUBRIAND",
            "ASSUNCAO",
            "ASSUNCAO DO PIAUI",
            "ASTOLFO DUTRA",
            "ATALAIA",
            "ATALAIA",
            "ATALAIA DO NORTE",
            "ATALANTA",
            "ATALEIA",
            "ATIBAIA",
            "ATILIO VIVACQUA",
            "AUGUSTINOPOLIS",
            "AUGUSTO DE LIMA",
            "AUGUSTO PESTANA",
            "AUREA",
            "AURELINO LEAL",
            "AURIFLAMA",
            "AURILANDIA",
            "AURORA",
            "AURORA",
            "AURORA DO TOCANTINS",
            "AUTAZES",
            "AVANHANDAVA",
            "AVARE",
            "AVEIRO",
            "AVELINO LOPES",
            "AVELINOPOLIS",
            "HIDROLANDIA",
            "HIDROLINA",
            "HONORIO SERPA",
            "HORIZONTE",
            "HORIZONTINA",
            "HORTOLANDIA",
            "HUGO NAPOLEAO",
            "HULHA NEGRA",
            "HUMAITA",
            "HUMBERTO DE CAMPOS",
            "IACANGA",
            "IACIARA",
            "IACRI",
            "IACU",
            "IAPU",
            "IATI",
            "IBARETAMA",
            "IBATE",
            "IBATEGUARA",
            "IBATIBA",
            "IBEMA",
            "IBERTIOGA",
            "IBIA",
            "IBIACA",
            "IBIAI",
            "IBIAM",
            "IBIAPINA",
            "IBIASSUCE",
            "IBICARAI",
            "IBICOARA",
            "IBICUI",
            "IBICUITINGA",
            "IBIMIRIM",
            "IBIPEBA",
            "IBIPITANGA",
            "IBIPORA",
            "IBIQUERA",
            "IBIRA",
            "IBIRACATU",
            "IBIRACI",
            "IBIRAMA",
            "IBIRAPITANGA",
            "IBIRAPUA",
            "IBIRAPUITA",
            "IBIRATAIA",
            "IBIRITE",
            "IBIRUBA",
            "IBITIARA",
            "IBITINGA",
            "IBITIRAMA",
            "IBITITA",
            "IBITIURA DE MINAS",
            "IBITURUNA",
            "IBIUNA",
            "IBOTIRAMA",
            "ICAPUI",
            "ICARA",
            "ICARAI DE MINAS",
            "ICEM",
            "ICHU",
            "ICO",
            "ICONHA",
            "IELMO MARINHO",
            "IGAPORA",
            "IGARACI",
            "IGARACU DO TIETE",
            "IGARACY",
            "IGARAPAVA",
            "IGARAPE",
            "IGARAPE-ACU",
            "IGARAPE DO MEIO",
            "IGARAPE MIRIM",
            "IGARAPE-MIRI",
            "IGARASSU",
            "IGARATA",
            "IGARATINGA",
            "IGRAPIUNA",
            "IGUABA GRANDE",
            "IGUAI",
            "COQUEIRO BAIXO",
            "COQUEIRO SECO",
            "COQUEIROS DO SUL",
            "CORACAO DE JESUS",
            "CORACAO DE MARIA",
            "CORBELIA",
            "CORDEIROS",
            "CORDILHEIRA ALTA",
            "CORDISBURGO",
            "CORDISLANDIA",
            "COREAU",
            "COREMAS",
            "CORGUINHO",
            "CORIBE",
            "CORINTO",
            "CORNELIO PROCOPIO",
            "COROACI",
            "COROADOS",
            "COROATA",
            "COROMANDEL",
            "CORONEL BARROS",
            "CORONEL FABRICIANO",
            "CORONEL FREITAS",
            "CORONEL JOAO PESSOA",
            "CORONEL JOAO SA",
            "CORONEL JOSE DIAS",
            "CORONEL MACEDO",
            "CORONEL MARTINS",
            "CORONEL MURTA",
            "CORONEL PACHECO",
            "CORONEL PILAR",
            "CORONEL SAPUCAIA",
            "CORONEL VIVIDA",
            "CORONEL XAVIER CHAVES",
            "CORREGO DANTA",
            "CORREGO DO BOM JESUS",
            "CORREGO DO OURO",
            "CORREGO FUNDO",
            "CORREGO NOVO",
            "CORREIA PINTO",
            "CORRENTE",
            "CORRENTINA",
            "CORTES",
            "CORUMBA",
            "CORUMBA DE GOIAS",
            "CORUMBAIBA",
            "CORUMBIARA",
            "CORUPA",
            "CORURIPE",
            "COSMOPOLIS",
            "COSMORAMA",
            "COSTA MARQUES",
            "COSTA RICA",
            "COTEGIPE",
            "COTIA",
            "COTIPORA",
            "COTRIGUACU",
            "COUTO DE MAGALHAES",
            "COUTO DE MAGALHAES DE MINAS",
            "COXILHA",
            "COXIM",
            "COXIXOLA",
            "CRATEUS",
            "CRATO",
            "CRAVOLANDIA",
            "CRICIUMA",
            "CRISOLITA",
            "CRISOPOLIS",
            "CRISTAIS",
            "CRISTAIS PAULISTA",
            "CRISTAL DO SUL",
            "CRISTALANDIA",
            "CRISTALANDIA DO PIAUI",
            "CRISTALIA",
            "CRISTALINA",
            "CRISTIANO OTONI",
            "CRISTIANOPOLIS",
            "CRISTINA",
            "CRISTINAPOLIS",
            "CRISTOPOLIS",
            "CRIXAS",
            "CRIXAS DO TOCANTINS",
            "CROATA",
            "CROMINIA",
            "CRUCILANDIA",
            "CRUZ",
            "CRUZ ALTA",
            "CRUZ DAS ALMAS",
            "CRUZ DO ESPIRITO SANTO",
            "CRUZ MACHADO",
            "CRUZALIA",
            "CRUZALTENSE",
            "CRUZEIRO",
            "CRUZEIRO",
            "CRUZEIRO DA FORTALEZA",
            "CRUZEIRO DO IGUACU",
            "CRUZEIRO DO SUL",
            "CRUZEIRO DO SUL",
            "CRUZETA",
            "CRUZILIA",
            "CUBATI",
            "CUIABA",
            "CUITE",
            "CUITE DE MAMANGUAPE",
            "CUITEGI",
            "CUJUBIM",
            "CUMARI",
            "CUMARU DO NORTE",
            "CUMBE",
            "CUNHA",
            "CUNHA PORA",
            "CUNHATAI",
            "CUPARAQUE",
            "CUPIRA",
            "CURACA",
            "CURIMATA",
            "CURIONOPOLIS",
            "CURITIBA",
            "CURIUVA",
            "CURRAIS",
            "CURRAL DE CIMA",
            "CURRAL DE DENTRO",
            "CURRAL NOVO DO PIAUI",
            "CURRAL VELHO",
            "CURRALINHO",
            "CURUCA",
            "CURURUPU",
            "CURVELANDIA",
            "CURVELO",
            "CUSTODIA",
            "DAMIANOPOLIS",
            "DAMIAO",
            "DAMOLANDIA",
            "DARCINOPOLIS",
            "DARIO MEIRA",
            "DATAS",
            "DAVID CANABARRO",
            "DAVINOPOLIS",
            "DAVINOPOLIS",
            "DELFIM MOREIRA",
            "DELFINOPOLIS",
            "DELMIRO GOUVEIA",
            "DELTA",
            "DENISE",
            "DEODAPOLIS",
            "DEPUTADO IRAPUAN PINHEIRO",
            "DERRUBADAS",
            "DESCALVADO",
            "DESCANSO",
            "DESCOBERTO",
            "DESTERRO",
            "DESTERRO DE ENTRE RIOS",
            "DESTERRO DO MELO",
            "DIAMANTE",
            "DIAMANTE D OESTE",
            "DIAMANTE DO SUL",
            "DIAMANTINA",
            "DIAMANTINO",
            "DIANOPOLIS",
            "DIAS D AVILA",
            "DILERMANDO DE AGUIAR",
            "DIOGO DE VASCONCELOS",
            "DIONISIO",
            "DIONISIO CERQUEIRA",
            "DIORAMA",
            "DIRCE REIS",
            "DIRCEU ARCOVERDE",
            "DIVINA PASTORA",
            "DIVINESIA",
            "DIVINO",
            "CAMPO NOVO",
            "CAMPO NOVO DE RONDONIA",
            "CAMPO NOVO DO PARECIS",
            "CAMPO VERDE",
            "CAMPOS ALTOS",
            "CAMPOS BELOS",
            "CAMPOS DE JULIO",
            "CAMPOS DO JORDAO",
            "CAMPOS DOS GOYTACAZES",
            "CAMPOS GERAIS",
            "CAMPOS LINDOS",
            "CAMPOS NOVOS",
            "CAMPOS NOVOS PAULISTA",
            "CAMPOS SALES",
            "CAMPOS VERDES",
            "CAMUTANGA",
            "CANA VERDE",
            "CANAA",
            "CANAA DOS CARAJAS",
            "CANABRAVA DO NORTE",
            "CANAPI",
            "CANAPOLIS",
            "CANAPOLIS",
            "CANARANA",
            "CANARANA",
            "CANAS",
            "CANAVIEIRAS",
            "CANDANGOLANDIA",
            "CANDEAL",
            "CANDEIAS",
            "CANDEIAS",
            "CANDEIAS DO JAMARI",
            "CANDELARIA",
            "CANDIBA",
            "CANDIDO DE ABREU",
            "CANDIDO GODOI",
            "CANDIDO MOTA",
            "CANDIDO RODRIGUES",
            "CANDIDO SALES",
            "CANDIOTA",
            "CANELINHA",
            "CANGUARETAMA",
            "CANGUCU",
            "CANHOBA",
            "CANHOTINHO",
            "CANINDE",
            "CANINDE DE SAO FRANCISCO",
            "CANOAS",
            "CANOINHAS",
            "CANSANCAO",
            "CANTA",
            "CANTAGALO",
            "CANTAGALO",
            "CANTANHEDE",
            "CANUDOS",
            "CANUTAMA",
            "CAPANEMA",
            "CAPANEMA",
            "CAPAO ALTO",
            "CAPAO BONITO",
            "CAPAO BONITO DO SUL"
        );
    }
}
