INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, CANAL, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(1, 15, 'A', 'AGENTE_AUTORIZADO', 'CANAL', to_date('2024-01-01 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, CANAL, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(2, 30, 'I', 'AGENTE_AUTORIZADO', 'CANAL', to_date('2024-01-02 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, NIVEL, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(3, 20, 'A', 'RECEPTIVO', 'NIVEL', to_date('2024-01-03 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, NIVEL, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(4, 500, 'I', 'RECEPTIVO', 'NIVEL', to_date('2024-01-04 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, ESTRUTURA_AA, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(5, 25, 'A', 'AGENTE_AUTORIZADO', 'ESTRUTURA', to_date('2024-01-05 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, ESTRUTURA_AA, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(6, 5, 'I', 'AGENTE_AUTORIZADO', 'ESTRUTURA', to_date('2024-01-06 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, SUBCANAL_ID, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(7, 30, 'A', 1, 'SUBCANAL', to_date('2024-01-07 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, SUBCANAL_ID, TIPO_CONFIGURACAO, DATA_CADASTRO)
VALUES(8, 60, 'I', 4, 'SUBCANAL', to_date('2024-01-08 12:30:00', 'yyyy-MM-dd hh24:mi:ss'));

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, TIPO_CONFIGURACAO) VALUES(9, 24, 'A', 'PADRAO');
