INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, CANAL, TIPO_CONFIGURACAO) VALUES(1, 15, 'A', 'AGENTE_AUTORIZADO', 'CANAL');
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, CANAL, TIPO_CONFIGURACAO) VALUES(2, 30, 'I', 'AGENTE_AUTORIZADO', 'CANAL');

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, NIVEL, TIPO_CONFIGURACAO) VALUES(3, 20, 'A', 'RECEPTIVO', 'NIVEL');
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, NIVEL, TIPO_CONFIGURACAO) VALUES(4, 500, 'I', 'RECEPTIVO', 'NIVEL');

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, ESTRUTURA_AA, TIPO_CONFIGURACAO) VALUES(5, 25, 'A', 'AGENTE_AUTORIZADO', 'ESTRUTURA');
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, ESTRUTURA_AA, TIPO_CONFIGURACAO) VALUES(6, 5, 'I', 'AGENTE_AUTORIZADO', 'ESTRUTURA');

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, SUBCANAL_ID, TIPO_CONFIGURACAO) VALUES(7, 30, 'A', 1, 'SUBCANAL');
INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, SUBCANAL_ID, TIPO_CONFIGURACAO) VALUES(8, 60, 'I', 4, 'SUBCANAL');

INSERT INTO CONFIGURACAO_AGENDA_REAL(ID, QTD_HORAS, SITUACAO, TIPO_CONFIGURACAO) VALUES(9, 24, 'A', 'PADRAO');
