INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, CANAL) VALUES(1, 15, 'DESC', 'A', 'AGENTE_AUTORIZADO');
INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, CANAL) VALUES(2, 30, 'DESC', 'I', 'AGENTE_AUTORIZADO');

INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, NIVEL) VALUES(3, 20, 'DESC', 'A', 'RECEPTIVO');
INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, NIVEL) VALUES(4, 500, 'DESC', 'I', 'RECEPTIVO');

INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, ESTRUTURA_AA) VALUES(5, 25, 'DESC', 'A', 'AGENTE_AUTORIZADO');
INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, ESTRUTURA_AA) VALUES(6, 5, 'DESC', 'I', 'AGENTE_AUTORIZADO');

INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, SUBCANAL) VALUES(7, 30, 'DESC', 'A', 'PAP');
INSERT INTO CONFIGURACAO_AGENDA(ID, QTD_HORAS, DESCRICAO, SITUACAO, SUBCANAL) VALUES(8, 60, 'DESC', 'I', 'PAP');