INSERT INTO UF(ID, NOME, UF) VALUES (666, 'PARANA', 'PR');
Insert into CIDADE (ID,CODIGO_IBGE,NOME,FK_SUB_CLUSTER,FK_UF,NET_UNO) values (1,'4101507','ARAPONGAS',NULL,666,'F');
Insert into CIDADE (ID,CODIGO_IBGE,NOME,FK_SUB_CLUSTER,FK_UF,NET_UNO) values (2,'4113700','LONDRINA',NULL,666,'F');
Insert into CIDADE (ID,CODIGO_IBGE,NOME,FK_SUB_CLUSTER,FK_UF,NET_UNO) values (3,'4115200','MARINGA',NULL,666,'F');



INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE)
VALUES (100, SYSDATE, '30-JUL-19', 'V', 'Feriado Nacional do Luis', null);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE)
VALUES (101, SYSDATE, '28-JUL-19', 'V', 'Feriado de Londrina do Luis', 2);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE)
VALUES (102, SYSDATE, '29-JUL-19', 'V', 'Feriado de Maringá do Luis', 3);