INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE)
VALUES (100, SYSDATE, '30-JUL-19', 'V', 'Feriado Nacional do Luis', null);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE)
VALUES (101, SYSDATE, '28-JUL-19', 'F', 'Feriado de Londrina do Luis', 5578); -- Londrina
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE)
VALUES (102, SYSDATE, '29-JUL-19', 'F', 'Feriado de Maringá do Luis', 3426); -- Maringá