INSERT INTO USUARIO (ID, NOME, EMAIL_01, SITUACAO, TELEFONE_01, CPF, FK_CARGO, FK_DEPARTAMENTO, ALTERAR_SENHA, SENHA, DATA_CADASTRO)
VALUES (1111, 'USUARIO TESTE', 'USUARIO_TESTE@GMAIL.COM', 'A', '43 3333-5555', '75952969874', 8, 50, 'F', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', CURRENT_DATE);


INSERT INTO IMPORTACAO_FERIADO(ID, DATA_CADASTRO, SITUACAO, USUARIO_CADASTRO_ID, USUARIO_CADASTRO_NOME, DESCRICAO)
VALUES (1, SYSDATE, 'IMPORTADO', 1, 'Fiorillo', 'DESCRICAO');

INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (100, SYSDATE, '30-JUL-19', 'V', 'Feriado Nacional do Luis', null, 'ATIVO', null, 'NACIONAL', NULL, NULL);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (101, SYSDATE, '28-JUL-19', 'F', 'Feriado de Londrina do Luis', 5578, 'ATIVO', 1, 'MUNICIPAL', NULL, NULL); -- Londrina
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (102, SYSDATE, '29-JUL-19', 'F', 'Feriado de Maringá do Luis', 3426, 'ATIVO', 1, 'MUNICIPAL', NULL, NULL); -- Maringá
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (103, SYSDATE, '29-JUN-19', 'F', 'Feriado de Maringá da Viola', 3426, 'EXCLUIDO', 1, 'MUNICIPAL', NULL, NULL); -- Maringá excluido
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (104, SYSDATE, '23-SEP-19', 'F', 'Feriado de Santa Catarina', null, 'ATIVO', 22, 'ESTADUAL', 1111, NULL); -- Santa Catarina
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (105, SYSDATE, '23-SEP-19', 'F', 'Feriado de Santa Catarina', 4505, 'ATIVO', 22, 'ESTADUAL', 1111, 104); -- Santa Catarina filho
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (106, SYSDATE, '23-SEP-19', 'F', 'Feriado de Santa Catarina', 4498, 'ATIVO', 22, 'ESTADUAL', 1111, 104); -- Santa Catarina filho
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (107, SYSDATE, '22-SEP-19', 'F', 'Feriado de Chapeco', 4498, 'ATIVO', 22, 'MUNICIPAL', 1111, null); -- Chapeco
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (108, SYSDATE, '23-SEP-19', 'F', 'Feriado Alisson', 4498, 'ATIVO', 1, 'ESTADUAL', 1111, null);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (109, SYSDATE, '23-SEP-19', 'F', 'Feriado Alisson', 3426, 'ATIVO', 1, 'MUNICIPAL', 1111, null);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (199, SYSDATE, '23-SEP-19', 'F', 'Feriado Alisson', 5578, 'ATIVO', 1, 'MUNICIPAL', 1111, null);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI, FK_IMPORTACAO)
VALUES (200, SYSDATE, '20-SEP-23', 'F', 'Feriado Fiorillo', 5578, 'ATIVO', 1, 'MUNICIPAL', 1111, null, 1);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (201, SYSDATE, '28-JUL-23', 'F', 'Feriado Fiorillo', 5578, 'ATIVO', 1, 'ESTADUAL', 1111, null);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, SITUACAO, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI, FK_IMPORTACAO)
VALUES (202, SYSDATE, '25-DEC-23', 'V', 'Natal', 'ATIVO', 'NACIONAL', 1111, null, 1);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI, FK_IMPORTACAO)
VALUES (203, SYSDATE, '23-JUL-23', 'F', 'Feriado Fiorillo', 5578, 'ATIVO', 1, 'MUNICIPAL', 1111, null, 1);
INSERT INTO FERIADO(ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE, SITUACAO, FK_UF, TIPO_FERIADO, FK_USUARIO_CADASTRO, FK_FERIADO_PAI)
VALUES (300, SYSDATE, SYSDATE, 'V', 'Feriado Nacional do Fernando', null, 'ATIVO', null, 'NACIONAL', NULL, NULL);