-- USUARIO
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
    VALUES (100, 'A', 'F', '0', SYSDATE - 15, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50, NULL),
           (101, 'A', 'F', '0', CURRENT_DATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50, NULL),
           (102, 'I', 'F', '0', CURRENT_DATE, 'JOAO@GMAIL.COM', 'JOAO', '$', 50, 50, NULL),
           (103, 'A', 'F', '0', SYSDATE - 32, 'CARLOS@HOTMAIL.COM', 'CARLOS', '$', 50, 50, NULL),
           (104, 'A', 'F', '0', SYSDATE - 47, 'MARIA@HOTMAIL.COM', 'MARIA', '$', 50, 50, NULL),
           (106, 'A', 'F', '0', SYSDATE - 100, 'ALBERTO@HOTMAIL.COM', 'ALBERTO', '$', 50, 50, SYSDATE - 2),
           (107, 'A', 'F', '0', SYSDATE - 100, 'EXECUTIVO1@TESTE.COM', 'EXECUTIVO 1', '$', 5, 3, SYSDATE - 2),
           (108, 'A', 'F', '0', SYSDATE - 100, 'EXECUTIVO2@TESTE.COM', 'EXECUTIVO 2', '$', 5, 3, SYSDATE - 2),
           (109, 'A', 'F', '0', SYSDATE - 100, 'COORDENADOR@TESTE.COM', 'COORDENADOR', '$', 4, 3, SYSDATE - 2),
           (110, 'I', 'F', '0', SYSDATE - 100, 'RENATO@TESTE.COM', 'EXECUTIVO 3 INATIVO', '$', 5, 3, SYSDATE - 2);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (111, 'A', 'F', '0', SYSDATE - 90, 'EXECUTIVOHUNTER2@TESTE.COM', 'HUNTER 2', '$', 95, 3);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (112, 'I', 'F', '0', SYSDATE - 90, 'EXECUTIVOHUNTER3@TESTE.COM', 'HUNTER 3', '$', 95, 3);

INSERT INTO USUARIO_HIERARQUIA (FK_USUARIO, FK_USUARIO_SUPERIOR, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (107, 109, 109, SYSDATE), (108, 109, 109, SYSDATE);

-- USUARIO CIDADE
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO, DATA_BAIXA)
    VALUES (100, 5578, 100, CURRENT_DATE, NULL),
           (100, 3237, 100, CURRENT_DATE, NULL),
           (100, 4498, 100, CURRENT_DATE, NULL),
           (100, 879, 100, CURRENT_DATE, CURRENT_DATE),
           (101, 5107, 100, CURRENT_DATE, NULL);