INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'BCC', 'Brasil Center');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'CALLINK', 'Callink');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'PROPRIO', 'Próprio');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'ATENTO', 'Atento');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'VGX', 'VGX');