-- USUARIO --
INSERT INTO USUARIO (ID, SITUACAO, CPF, DATA_CADASTRO, EMAIL_01, NOME, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA)
    VALUES (1, 'A', '33322288896', SYSDATE, 'JOAO@HOTMAIL.COM', 'JOAO EXECUTIVO', '(43) 33228855', 5, 3, 'SENHA', 'F');
 -- EMPRESAS CLARO E NET NO USUARIO --
INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA) VALUES (1, 1);
INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA) VALUES (1, 3);
-- CIDADES DO USUARIO --
INSERT INTO USUARIO_CIDADE (FK_CIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (5578, 1, SYSDATE);
INSERT INTO USUARIO_CIDADE (FK_CIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (3426, 1, SYSDATE);
INSERT INTO USUARIO_CIDADE (FK_CIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (3408, 1, SYSDATE);
INSERT INTO USUARIO_CIDADE (FK_CIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (5128, 1, SYSDATE);

-- USUARIO --
INSERT INTO USUARIO (ID, SITUACAO, CPF, DATA_CADASTRO, EMAIL_01, NOME, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA)
    VALUES (2, 'A', '44455588878', SYSDATE, 'ALBERTO@HOTMAIL.COM', 'ALBERTO EXECUTIVO', '(43) 33421155', 5, 3, 'SENHA', 'F');
-- EMPRESAS NET  --
INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA) VALUES (2, 3);
-- CIDADES DO USUARIO --
INSERT INTO USUARIO_CIDADE (FK_CIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (46, 2, SYSDATE);