INSERT INTO NIVEL_EMPRESA (ID, NIVEL_EMPRESA) VALUES (1, 'VAREJO');
INSERT INTO NIVEL_EMPRESA (ID, NIVEL_EMPRESA) VALUES (2, 'RECEPTIVO');

INSERT INTO MODALIDADE_EMPRESA (ID, MODALIDADE_EMPRESA) VALUES (1, 'PAP');
INSERT INTO MODALIDADE_EMPRESA (ID, MODALIDADE_EMPRESA) VALUES (2, 'TELEVENDAS');

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO)
    VALUES (1, 'A', 'F', '0', CURRENT_DATE, 'ADMIN@XBRAIN.COM.BR', 'Thiago', '$', 50, 50);

INSERT INTO ORGANIZACAO_EMPRESA (ID, RAZAO_SOCIAL, CNPJ, FK_NIVEL_EMPRESA, SITUACAO, DATA_CADASTRO, FK_USUARIO_CADASTRO)
    VALUES (1, 'THIAGO TESTE', '08112392000192', 2, 'A', CURRENT_DATE, 1);

INSERT INTO ORGANIZACAO_EMPRESA_HIST (ID, SITUACAO, OBSERVACAO, FK_ORGANIZACAO_EMPRESA, DATA_ALTERACAO, USUARIO_ID, USUARIO_NOME)
    VALUES (100, 'A', 'INATIVACAO', 1, CURRENT_DATE, 2, 'Thiago');