INSERT INTO NIVEL (ID, CODIGO, EXIBIR_CAD_USUARIO, NOME, SITUACAO) VALUES (100, 'MSO', 'V', 'MSO', 'A');

INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (200, 'BRIEFING_ANALISTA_TI', 'Analista de TI', 'A', 100);

INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (500, 'COMERCIAL', 'Comercial', 'A', 100);

INSERT INTO APLICACAO (ID, CODIGO, NOME) VALUES (60, 'BRF', 'BRIEFING');

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO, PERMISSAO_TELA) VALUES (1006, 'Criar solicitação de demanda', 'BRF_10006', 60, null);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 200, 500, 10006);
