----USUARIOS
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (10220, 'A', 'F', '54564564654', SYSDATE, 'GERENTE_OPERACAO@NET.COM.BR', 'Gerente operacao ativo local', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 7, 3);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (11122, 'A', 'F', '54564564654', SYSDATE, 'COORDENADOR_OPERACAO@NET.COM.BR', 'Coordenador operacao ativo local', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 4, 3);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (11123, 'A', 'F', '54564564654', SYSDATE, 'SUPERVISOR_OPERACAO@NET.COM.BR', 'Supervisor operacao ativo local', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 10, 3);

---- DEFINIR CANAL USUARIOS
INSERT INTO USUARIO_CANAL(FK_USUARIO, CANAL) VALUES (10220, 'ATIVO_PROPRIO');
INSERT INTO USUARIO_CANAL(FK_USUARIO, CANAL) VALUES (11122, 'ATIVO_PROPRIO');
INSERT INTO USUARIO_CANAL(FK_USUARIO, CANAL) VALUES (11123, 'ATIVO_PROPRIO');

---- DEFINIR HIERARQUIA DOS USUARIOS
INSERT INTO USUARIO_HIERARQUIA (FK_USUARIO, FK_USUARIO_SUPERIOR, DATA_CADASTRO, FK_USUARIO_CADASTRO) VALUES (11122, 10220, SYSDATE, 100);
INSERT INTO USUARIO_HIERARQUIA (FK_USUARIO, FK_USUARIO_SUPERIOR, DATA_CADASTRO, FK_USUARIO_CADASTRO) VALUES (11123, 10220, SYSDATE, 100);

---- SITE --
INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (1, 'Manaus', 'AMT', 'A');
INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (2, 'Site Inativo', 'FNT', 'I');

---- VINCULAR SITES A SUPERVIDORES E COORDENADORES
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(1, 11122);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(2, 11123);