-- USUARIO HISTORICO --
-- DEVE INATIVAR --
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (200, to_date('03/03/2019 10:00:00', 'dd/mm/yyyy hh24:mi:ss'), null, 'A', 5, 100, 100);
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (201, to_date('02/03/2019 13:10:00', 'dd/mm/yyyy hh24:mi:ss'), null, 'A', 5, 101, 101);
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (202, sysdate - 31, null, 'A', 5, 366, 366);
-- NAO DEVE INATIVAR --
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (203, SYSDATE, null, 'A', 5, 106, 106);

