-- USUARIO
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (100, 'A', 'F', '0', CURRENT_DATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (101, 'A', 'F', '0', current_date, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);

-- USUARIO CIDADE
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (100, 5578, 100, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (100, 3237, 100, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (100, 4498, 100, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO, DATA_BAIXA) VALUES (100, 879, 100, CURRENT_DATE, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (101, 5107, 100, CURRENT_DATE);