INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (300, 'RENATO', 'RENATO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (301, 'JOAO', 'JOAO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE), NULL);
INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (302, 'CAIO', 'CAIO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 31), NULL);
INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (303, 'ALBERTO', 'ALBERTO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 33), NULL);
INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (304, 'MARIA', 'MARIA@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 32), NULL);
INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (305, 'EDUARDA', 'EDUARDA@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 40), (SYSDATE - 4));
INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (306, 'ERICA', 'ERICA@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 1), (SYSDATE - 3));

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 10), 301);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 5), 301);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, SYSDATE, 301);

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 31), 302);

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 33), 303);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 34), 303);


INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 32), 304);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 33), 304);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 70), 304);

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 40), 305);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 41), 305);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 65), 305);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 62), 305);

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 1), 306);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 11), 306);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 30), 306);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 65), 306);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 90), 306);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 110), 306);

-- OBS: NÃO ADICIONAR MAIS SCRIPTS NESTE ARQUIVO --