-- USUARIO HISTORICO --
-- DEVE INATIVAR --
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (200, to_date('03/03/2019 10:00:00', 'dd/mm/yyyy hh24:mi:ss'), null, 'A', 5, 100, 100);
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (201, to_date('02/03/2019 13:10:00', 'dd/mm/yyyy hh24:mi:ss'), null, 'A', 5, 101, 101);
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (202, sysdate - 31, null, 'A', 5, 130, 130);
-- NAO DEVE INATIVAR --
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (203, SYSDATE, null, 'A', 5, 106, 106);

-- USUÁRIO SEM HISTÓRICO --
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO)
    VALUES (799, 'A', 'F', '65710871036', SYSDATE, 'HELPDESK@XBRAIN.COM.BR', 'HELPDESK', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 51, 51);

-- USUÁRIO COM HISTÓRICO --
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO)
    VALUES (800, 'A', 'F', '39688855522', SYSDATE, 'FUNCIONARIO@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 51, 51);
INSERT INTO USUARIO_HISTORICO (ID, DATA_CADASTRO, OBSERVACAO, SITUACAO, FK_MOTIVO_INATIV, FK_USUARIO, FK_USUARIO_ALTERACAO)
    VALUES (204, SYSDATE, null, 'A', 5, 800, 800);