INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL, QUANTIDADE_SUPERIOR) VALUES (1000, 'EXECUTIVO', 'Executivo', 'A', 1, 50);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL, QUANTIDADE_SUPERIOR) VALUES (1001, 'GERENTE_OPERACAO', 'Gerente', 'A', 1, 50);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL, QUANTIDADE_SUPERIOR) VALUES (1002, 'COORDENADOR_OPERACAO', 'Coordenador', 'A', 1, 50);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL, QUANTIDADE_SUPERIOR) VALUES (1003, 'EXECUTIVO_HUNTER', 'Executivo Hunter', 'A', 1, 50);

INSERT INTO CIDADE(ID, NOME, FK_SUB_CLUSTER, FK_UF, FK_USUARIO_APROVADOR_MSO, CODIGO_IBGE, NET_UNO) VALUES(1111, 'LONDRINA', 1, 1, NULL,'4113700', 'F');
INSERT INTO CIDADE(ID, NOME, FK_SUB_CLUSTER, FK_UF, FK_USUARIO_APROVADOR_MSO, CODIGO_IBGE, NET_UNO) VALUES(2222, 'SAO PAULO', 1, 2, NULL,'4113700', 'F');
INSERT INTO CIDADE(ID, NOME, FK_SUB_CLUSTER, FK_UF, FK_USUARIO_APROVADOR_MSO, CODIGO_IBGE, NET_UNO) VALUES(3333, 'RIO DE JANEIRO', 1, 19, NULL,'4113700', 'F');
INSERT INTO CIDADE(ID, NOME, FK_SUB_CLUSTER, FK_UF, FK_USUARIO_APROVADOR_MSO, CODIGO_IBGE, NET_UNO) VALUES(4444, 'CAPITOLIO', 1, 8, NULL,'4113700', 'F');

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (1, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1000, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (2, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1000, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (3, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1001, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (4, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1001, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (5, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1002, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (6, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1002, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (7, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1003, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, TELEFONE_01, FK_CARGO, FK_DEPARTAMENTO) VALUES (8, 'A', 'F', '38957979875', SYSDATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$2a$10$5Km7U7CyDD5VIrkJPXPK8.px0hJE9n.NgGx2tGRa/Gu3e3xEumipm', '99999', 1003, 50);

INSERT INTO USUARIO_CIDADE VALUES (1111, 1, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (1111, 2, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (1111, 3, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (1111, 4, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (1111, 5, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (1111, 6, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (1111, 7, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (1111, 8, NULL, CURRENT_DATE, NULL, NULL);

INSERT INTO USUARIO_CIDADE VALUES (2222, 1, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (2222, 2, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (2222, 3, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (2222, 4, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (2222, 5, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (2222, 7, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (2222, 8, NULL, CURRENT_DATE, NULL, NULL);

INSERT INTO USUARIO_CIDADE VALUES (3333, 1, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (3333, 3, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (3333, 4, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (3333, 5, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (3333, 7, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (3333, 8, NULL, CURRENT_DATE, NULL, NULL);

INSERT INTO USUARIO_CIDADE VALUES (4444, 1, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (4444, 2, NULL, CURRENT_DATE, NULL, NULL);
INSERT INTO USUARIO_CIDADE VALUES (4444, 7, NULL, CURRENT_DATE, NULL, NULL);
