--INSERT INTO UF (ID, NOME, UF) VALUES (7000, 'PARANÁ', 'PR');
--INSERT INTO CIDADE (ID, NOME, FK_UF, CODIGO_CIDADE_DBM) VALUES (5578, 'LONDRINA', 7000, 3);
UPDATE CIDADE SET CODIGO_CIDADE_DBM = 3 WHERE ID = 5578;
INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO, SITE_NACIONAL) VALUES (100, 'Parana', 'BRT', 'A', 'F');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(100, 5578);

INSERT INTO UF (ID, NOME, UF) VALUES (10000, 'SAO PAULO', 'SP');
INSERT INTO CIDADE (ID, NOME, FK_UF, CODIGO_CIDADE_DBM) VALUES (6578, 'SAO PAULO', 10000, 4);
INSERT INTO CIDADE (ID, NOME, FK_UF, CODIGO_CIDADE_DBM) VALUES (6579, 'SAO PAULO', 10000, 4);