INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (1, 'São Paulo', 'AMERICA_SAO_PAULO', 'A');

INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(1, 5578);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(1, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(1, 102);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (2, 'Recife', 'AMERICA_RECIFE', 'A');

INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(2, 3423);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(2, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(2, 102);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (3, 'Manaus', 'AMERICA_MANAUS', 'A');

INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(3, 4943);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(3, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(3, 102);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (4, 'Inativo', 'AMERICA_MANAUS', 'I');
