-- USUÁRIOS APTOS PARA INATIVAÇÃO

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (801, 'LUCAS', 'LUCAS@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 33), 801);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (802, 'LARISSA', 'LARISSA@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 35), 802);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (803, 'JOAO', 'JOAO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 38), 803);

-- USUÁRIOS QUE NÃO SE ENCAIXAM NA REGRA

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (804, 'THIAGO', 'THIAGO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 2), 804);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (805, 'DANIEL', 'DANIEL@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 31), 805);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (806, 'MARCOS', 'MARCOS@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', '3-Jun-2020', NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 33), 806);

-- USUÁRIO DE VIABILIDADE

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (807, 'LUIZ', 'LUIZ@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 50), 807);