INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (300, 'RENATO', 'RENATO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (301, 'JOAO', 'JOAO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, to_date('28/06/2019 09:45:00', 'dd/mm/yyyy hh24:mi:ss'));

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (302, 'CAIO', 'CAIO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, to_date('27/06/2019 09:26:30', 'dd/mm/yyyy hh24:mi:ss'));

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO)
    VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, to_date('26/06/2019 08:30:00', 'dd/mm/yyyy hh24:mi:ss'), 301);

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO)
    VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, to_date('27/06/2019 09:26:30', 'dd/mm/yyyy hh24:mi:ss'), 302);

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO)
    VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, to_date('28/06/2019 09:45:00', 'dd/mm/yyyy hh24:mi:ss'), 301);