--INSERT INTO UF (ID, NOME, UF) VALUES (7000, 'PARANÁ', 'PR');
--INSERT INTO CIDADE (ID, NOME, FK_UF, CODIGO_CIDADE_DBM) VALUES (5578, 'LONDRINA', 7000, 3);
UPDATE CIDADE SET CODIGO_CIDADE_DBM = 3 WHERE ID = 5578;
INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (100, 'Parana', 'BRT', 'A');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(100, 5578);