--REGIONAL--
INSERT INTO REGIONAL(ID, NOME, SITUACAO)
VALUES(1004, 'REGIONAL', 'A');

--  GRUPO  --
INSERT INTO GRUPO(ID, NOME, FK_REGIONAL, SITUACAO)
VALUES(1005, 'X GRUPO', 1004, 'A');

INSERT INTO GRUPO(ID, NOME, FK_REGIONAL, SITUACAO)
VALUES(1006, 'A GRUPO', 1004, 'A');

INSERT INTO GRUPO(ID, NOME, FK_REGIONAL, SITUACAO)
VALUES(1007, 'B GRUPO', 1004, 'A');

INSERT INTO GRUPO(ID, NOME, FK_REGIONAL, SITUACAO)
VALUES(1008, 'GRUPO', 1004, 'I');

--CLUSTERS--
INSERT INTO CLUSTERS(ID, NOME, SITUACAO, FK_GRUPO)
VALUES(1009, 'A NOME CLUSTER', 'A', 1008);

INSERT INTO CLUSTERS(ID, NOME, SITUACAO, FK_GRUPO)
VALUES(1010, 'C NOME CLUSTER', 'A', 1008);

INSERT INTO CLUSTERS(ID, NOME, SITUACAO, FK_GRUPO)
VALUES(1011, 'B NOME CLUSTER', 'A', 1008);

INSERT INTO CLUSTERS(ID, NOME, SITUACAO, FK_GRUPO)
VALUES(1012, 'D NOME CLUSTER', 'I', 1008);

--SUB_CLUSTER--
INSERT INTO SUB_CLUSTER(ID, NOME, SITUACAO, FK_CLUSTER)
VALUES(1013, 'A NOME SUB CLUSTER', 'A', 1009);

INSERT INTO SUB_CLUSTER(ID, NOME, SITUACAO, FK_CLUSTER)
VALUES(1014, 'C NOME SUB CLUSTER', 'A', 1009);

INSERT INTO SUB_CLUSTER(ID, NOME, SITUACAO, FK_CLUSTER)
VALUES(1015, 'B NOME SUB CLUSTER', 'A', 1010);

INSERT INTO SUB_CLUSTER(ID, NOME, SITUACAO, FK_CLUSTER)
VALUES(1016, 'D NOME SUB CLUSTER', 'I', 1010);

