-- USUARIO
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1001, 'A', 'F', '0', CURRENT_DATE, 'SUPERVISOR_1@XBRAIN.COM.BR', 'SUPERVISOR 1', '$', 10, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1002, 'A', 'F', '0', CURRENT_DATE, 'SUPERVISOR 2@XBRAIN.COM.BR', 'SUPERVISOR 2', '$', 10, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1003, 'A', 'F', '0', CURRENT_DATE, 'TELEVENDAS_1@XBRAIN.COM.BR', 'TELEVENDAS 1', '$', 120, 3, NULL);


-- USUARIO_HIERARQUIA
INSERT INTO USUARIO_HIERARQUIA (FK_USUARIO, FK_USUARIO_SUPERIOR, FK_USUARIO_CADASTRO, DATA_CADASTRO)
VALUES (1003, 1002, 1002, CURRENT_DATE);