INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (1, 'BCC', 'Brasil Center');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (2, 'CALLINK', 'Callink');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (3, 'PROPRIO', 'Próprio');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (4, 'ATENTO', 'Atento');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (5, 'VGX', 'VGX');

INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (1, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (2, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (3, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (4, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (5, 5);