-- USUÁRIOS APTOS PARA INATIVAÇÃO

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (8011, 'TESTE', 'TESTE@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 35), (SYSDATE - 4));
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 35), 8011);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (802, 'LARISSA', 'LARISSA@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 35), NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 35), 802);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (803, 'JOAO', 'JOAO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', (SYSDATE - 8), NULL, CURRENT_DATE);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (810, 'JOAO', 'JOAO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', (SYSDATE - 8), NULL, (SYSDATE - 4));

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (811, 'JOSE', 'JOSE@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 33), (SYSDATE - 3));
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 33), 811);

-- USUÁRIOS QUE NÃO SE ENCAIXAM NA REGRA

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (804, 'THIAGO', 'THIAGO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 2), NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 2), 804);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (805, 'DANIEL', 'DANIEL@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 31), NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 31), 805);

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (806, 'MARCOS', 'MARCOS@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 31), NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 31), 806);

-- USUÁRIO DE VIABILIDADE

INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO, DATA_REATIVACAO)
    VALUES (807, 'LUIZ', 'LUIZ@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, (SYSDATE - 50), NULL);
INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 50), 807);