INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (100, 'São Paulo', 'BRT', 'A');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(100, 5578);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(100, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(100, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (100, 1);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (101, 'Rio Branco', 'ACT', 'A');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(101, 3423);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(101, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(101, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (101, 1), (101, 2);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO, DISCADORA_ID) VALUES (102, 'Manaus', 'AMT', 'A', 8);
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(102, 4943);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(102, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(102, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (102, 2);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (103, 'Site Inativo', 'FNT', 'I');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(103, 527);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(103, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(103, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (103, 10);
