INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'BCC', 'Brasil Center');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'CALLINK', 'Callink');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'PROPRIO', 'Próprio');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'ATENTO', 'Atento');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'VGX', 'VGX');

INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (1, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (2, 2)
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (3, 3)
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (4, 4)
INSERT INTO ORGANIZACAO_NIVEL(FK_ORGANIZACAO, FK_NIVEL) VALUES (5, 5)