INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (1, 'São Paulo', 'BRT', 'A');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(1, 5578);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(1, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(1, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (1, 1);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (2, 'Rio Branco', 'ACT', 'A');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(2, 3423);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(2, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(2, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (2, 1), (2, 2);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (3, 'Manaus', 'AMT', 'A');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(3, 4943);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(3, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(3, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (3, 2);

INSERT INTO SITE(ID, NOME, TIME_ZONE, SITUACAO) VALUES (4, 'Site Inativo', 'FNT', 'I');
INSERT INTO SITE_CIDADE(FK_SITE, FK_CIDADE) VALUES(4, 527);
INSERT INTO SITE_COORDENADOR(FK_SITE, FK_USUARIO) VALUES(4, 300);
INSERT INTO SITE_SUPERVISOR(FK_SITE, FK_USUARIO) VALUES(4, 102);
INSERT INTO SITE_ESTADO(FK_SITE, FK_ESTADO) VALUES (4, 10);
