INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO)
    VALUES (300, 'RENATO', 'RENATO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE),
           (301, 'JOAO', 'JOAO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE),
           (302, 'ALBERTO', 'ALBERTO@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE),
           (303, 'MARIA', 'MARIA@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE),
           (304, 'EDUARDA', 'EDUARDA@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE);

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
    VALUES (9000, 'Gerenciar Lead', 'FDR_GERENCIAR_LEAD', 23),
           (9001, 'Remover Contrato Agente Autorizado', 'POL_REMOVER_CONTRATO_AA', 23);

INSERT INTO  PERMISSAO_ESPECIAL (ID, DATA_BAIXA, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
    VALUES (1, null, sysdate, 9000, 300, 300),
           (2, null, sysdate, 9000, 301, 301),
           (3, null, sysdate, 9000, 302, 302),
           (4, null, sysdate, 9001, 303, 303);