-- USUARIO
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1001, 'A', 'F', '0', CURRENT_DATE, 'SUPERVISOR_1@XBRAIN.COM.BR', 'SUPERVISOR 1', '$', 10, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1002, 'A', 'F', '0', CURRENT_DATE, 'SUPERVISOR 2@XBRAIN.COM.BR', 'SUPERVISOR 2', '$', 10, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1003, 'A', 'F', '0', CURRENT_DATE, 'TELEVENDAS_1@XBRAIN.COM.BR', 'TELEVENDAS 1', '$', 120, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1004, 'A', 'F', '0', CURRENT_DATE, 'SUPERVISOR_3@XBRAIN.COM.BR', 'SUPERVISOR 3', '$', 10, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1005, 'A', 'F', '0', CURRENT_DATE, 'SUPERVISOR 4@XBRAIN.COM.BR', 'SUPERVISOR 4', '$', 10, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1006, 'I', 'F', '0', CURRENT_DATE, 'TELEVENDAS_2@XBRAIN.COM.BR', 'TELEVENDAS 2', '$', 120, 3, NULL);

INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO)
VALUES (1007, 'R', 'F', '0', CURRENT_DATE, 'TELEVENDAS_3@XBRAIN.COM.BR', 'TELEVENDAS 3', '$', 120, 3, NULL);

-- USUARIO_HIERARQUIA
INSERT INTO USUARIO_HIERARQUIA (FK_USUARIO, FK_USUARIO_SUPERIOR, FK_USUARIO_CADASTRO, DATA_CADASTRO)
VALUES (1003, 1002, 1002, CURRENT_DATE);

INSERT INTO USUARIO_HIERARQUIA (FK_USUARIO, FK_USUARIO_SUPERIOR, FK_USUARIO_CADASTRO, DATA_CADASTRO)
VALUES (1006, 1005, 1005, CURRENT_DATE);

INSERT INTO USUARIO_HIERARQUIA (FK_USUARIO, FK_USUARIO_SUPERIOR, FK_USUARIO_CADASTRO, DATA_CADASTRO)
VALUES (1007, 1005, 1005, CURRENT_DATE);