INSERT INTO USUARIO (ID, NOME, EMAIL_01, FK_CARGO, FK_DEPARTAMENTO, SENHA, ALTERAR_SENHA, SITUACAO, DATA_CADASTRO, DATA_ULTIMO_ACESSO)
    VALUES (307, 'LUCAS', 'LUCAS@XBRAIN.COM.BR', 50, 1, '123', 'F', 'A', CURRENT_DATE, NULL);

INSERT INTO USUARIO_ACESSO(ID, DATA_CADASTRO, FK_USUARIO) VALUES (SEQ_USUARIO_ACESSO.NEXTVAL, (SYSDATE - 33), 307);