-- USUARIO
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (100, 'A', 'F', '0', SYSDATE - 15, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (101, 'A', 'F', '0', current_date, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (102, 'I', 'F', '0', current_date, 'JOAO@GMAIL.COM', 'JOAO', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (103, 'A', 'F', '0', SYSDATE - 32, 'CARLOS@HOTMAIL.COM', 'CARLOS', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (104, 'A', 'F', '0', SYSDATE - 47, 'MARIA@HOTMAIL.COM', 'MARIA', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO, DATA_ULTIMO_ACESSO) VALUES (106, 'A', 'F', '0', SYSDATE - 100, 'ALBERTO@HOTMAIL.COM', 'ALBERTO', '$', 50, 50, SYSDATE - 2);

-- USUARIO CIDADE
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (100, 5578, 100, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (100, 3237, 100, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (100, 4498, 100, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO, DATA_BAIXA) VALUES (100, 879, 100, CURRENT_DATE, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, FK_USUARIO_CADASTRO, DATA_CADASTRO) VALUES (101, 5107, 100, CURRENT_DATE);