INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (100, 'A', 'F', '0', CURRENT_DATE, 'ADMIN@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);

INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, DATA_CADASTRO) VALUES (100, 3237, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, DATA_CADASTRO) VALUES (100, 1443, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, DATA_CADASTRO) VALUES (100, 2466, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, DATA_CADASTRO) VALUES (100, 3022, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, DATA_CADASTRO) VALUES (100, 2617, CURRENT_DATE);
INSERT INTO USUARIO_CIDADE (FK_USUARIO, FK_CIDADE, DATA_CADASTRO, DATA_BAIXA) VALUES (100, 1403, CURRENT_DATE, CURRENT_DATE);