INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (100, 'A', 'F', '0', CURRENT_DATE, 'ATIVO_COM_AFASTAMENTO@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (101, 'A', 'F', '0', CURRENT_DATE, 'INATIVO_SEM_AFASTAMENTO@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (102, 'A', 'F', '0', CURRENT_DATE, 'INATIVO_COM_AFASTAMETNO_VENCENDO@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);
INSERT INTO USUARIO (ID, SITUACAO, ALTERAR_SENHA, CPF, DATA_CADASTRO, EMAIL_01, NOME, SENHA, FK_CARGO, FK_DEPARTAMENTO) VALUES (103, 'A', 'F', '0', CURRENT_DATE, 'INATIVO_COM_AFASTAMENTO_SEM_VENCER@XBRAIN.COM.BR', 'ADMIN', '$', 50, 50);


INSERT INTO USUARIO_AFASTAMENTO (ID, FK_USUARIO, DATA_CADASTRO, INICIO, FIM) VALUES (1, 100, CURRENT_DATE, CURRENT_DATE, to_date('01/01/2017', 'dd/mm/yyyy'));
INSERT INTO USUARIO_AFASTAMENTO (ID, FK_USUARIO, DATA_CADASTRO, INICIO, FIM) VALUES (2, 102, CURRENT_DATE, CURRENT_DATE, to_date('01/01/2019', 'dd/mm/yyyy'));
INSERT INTO USUARIO_AFASTAMENTO (ID, FK_USUARIO, DATA_CADASTRO, INICIO, FIM) VALUES (3, 103, CURRENT_DATE, CURRENT_DATE, to_date('01/01/2018', 'dd/mm/yyyy'));