package br.com.xbrain.autenticacao.modules.feeder.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ECargosComPermissaoAaFeeder {

    AGENTE_AUTORIZADO_SOCIO,
    AGENTE_AUTORIZADO_SOCIO_SECUNDARIO,
    AGENTE_AUTORIZADO_BACKOFFICE_TELEVENDAS,
    AGENTE_AUTORIZADO_BACKOFFICE_D2D,
    AGENTE_AUTORIZADO_BACKOFFICE_TEMP,
    AGENTE_AUTORIZADO_BACKOFFICE_TELEVENDAS_RECEPTIVO,
    AGENTE_AUTORIZADO_GERENTE,
    AGENTE_AUTORIZADO_COORDENADOR;
}
