-- https://api.calendario.com.br/?ano=2019&token=RElPR09NQVJRVUVTQFhCUkFJTi5DT00uQlImaGFzaD0yNDI3NDgxMDc&json=true --

INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (1, 'Ano Novo', to_date('01-01-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (2, 'Sexta-Feira Santa', to_date('30-03-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (3, 'Dia de Tiradentes', to_date('21-04-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (4, 'Dia do Trabalho', to_date('01-05-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (5, 'Independência do Brasil', to_date('07-09-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (6, 'Nossa Senhora Aparecida', to_date('12-10-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (7, 'Dia de Finados', to_date('02-11-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (8, 'Proclamação da República', to_date('15-11-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (9, 'Natal', to_date('25-12-18', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');

INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (10, 'Ano Novo', to_date('01-01-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (11, 'Sexta-Feira Santa', to_date('19-04-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (12, 'Dia de Tiradentes', to_date('21-04-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (13, 'Dia do Trabalho', to_date('01-05-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (14, 'Independência do Brasil', to_date('07-09-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (15, 'Nossa Senhora Aparecida', to_date('12-10-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (16, 'Dia de Finados', to_date('02-11-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (17, 'Proclamação da República', to_date('15-11-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (18, 'Natal', to_date('25-12-19', 'dd/mm/yyyy'),  CURRENT_TIMESTAMP, 'V');

