-- https://api.calendario.com.br/?ano=2019&token=RElPR09NQVJRVUVTQFhCUkFJTi5DT00uQlImaGFzaD0yNDI3NDgxMDc&json=true --

INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (1, 'Ano Novo', '01-01-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (2, 'Sexta-Feira Santa', '30-03-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (3, 'Dia de Tiradentes', '21-04-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (4, 'Dia do Trabalho', '01-05-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (5, 'Independência do Brasil', '07-09-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (6, 'Nossa Senhora Aparecida', '12-10-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (7, 'Dia de Finados', '02-11-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (8, 'Proclamação da República', '15-11-18',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (9, 'Natal', '25-12-18',  CURRENT_TIMESTAMP, 'V');

INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (10, 'Ano Novo', '01-01-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (11, 'Sexta-Feira Santa', '19-04-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (12, 'Dia de Tiradentes', '21-04-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (13, 'Dia do Trabalho', '01-05-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (14, 'Independência do Brasil', '07-09-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (15, 'Nossa Senhora Aparecida', '12-10-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (16, 'Dia de Finados', '02-11-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (17, 'Proclamação da República', '15-11-19',  CURRENT_TIMESTAMP, 'V');
INSERT INTO FERIADO(ID, NOME, DATA_feriado, DATA_CADASTRO, FERIADO_NACIONAL) VALUES (18, 'Natal', '25-12-19',  CURRENT_TIMESTAMP, 'V');

