-- APLICAÇÃO
INSERT INTO APLICACAO (ID, NOME, CODIGO) VALUES (11, 'CONEXÃO GESTÃO', 'COG');

-- CARGO
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (86, 'OUVIDORIA', 'Ouvidoria', 'A', 15);

-- DEPARTAMENTO
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (66, 'OUVIDORIA', 'Ouvidoria', 'A', 15);

-- FUNCIONALIDADES - CONEXÃO GESTÃO --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (10000, 'Listar Contatos', 'COG_10000', 11);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (10001, 'Visualizar Detalhamento da Venda', 'COG_10001', 11);

-- Cargo XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 10000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 10001);

-- Cargo OUVIDORIA
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'OUVIDORIA'), 66, 10000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'OUVIDORIA'), 66, 10001);

-- END CONEXÃO GESTÂO