INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3030, 'Cadastrar venda para o vendedor D2D', 'VDS_3030', 3);

-- ADICIONA A PERMISSAO AO BACKOFFICE D2D  --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 78, 40, 3030, 1);