INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (79, 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D', 'Vendedor Back Office D2D', 'A', 3);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (80, 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS', 'Vendedor Back Office Televendas ', 'A', 3);

-- PERMISSOES AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 32, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 11, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3000, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3008, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3022, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3013, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3006, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3002, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3016, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3014, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3019, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3020, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3021, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3003, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3017, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 2015, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3028, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 3027, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS'), 40, 2021, 1);

-- PERMISSOES AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 32, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 11, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3000, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3008, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3022, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3013, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3006, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3002, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3016, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3014, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3019, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3020, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3021, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3003, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3017, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 2015, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3028, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 3027, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES
(SEQ_CARGO_DEPART_FUNC.nextval, CURRENT_DATE, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_D2D'), 40, 2021, 1);