INSERT INTO cargo (id, nome, situacao, FK_NIVEL) values (81, 'Supervisor Temporário', 'A', 3);

INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 2015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3000);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3001);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3002);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3003);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3007);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3008);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3009);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3010);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 5000);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 5001);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 5002);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 5003);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 5004);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 4);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 11);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 5);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 32);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3014);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3019);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3020);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3021);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 81, 40, 3029);

INSERT INTO cargo (id, nome, situacao, FK_NIVEL) values (82, 'Gerente Temporário', 'A', 3);

INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3016);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3017);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3022);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3000);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3001);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3002);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3003);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3004);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3007);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3008);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3009);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3010);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 5000);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 5001);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 5002);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 5003);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 5004);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 4);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 11);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 5);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 32);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3014);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 2015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3019);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3020);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3021);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3027);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3028);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 82, 40, 3029);


INSERT INTO cargo (id, nome, situacao, FK_NIVEL) values (83, 'Vendedor Temporário', 'A', 3);

INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3004);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3000);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3001);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3002);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3003);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3007);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3009);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3010);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 11);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 32);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3013);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3014);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 2021);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3019);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3020);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 83, 40, 3015);

INSERT INTO cargo (id, nome, situacao, FK_NIVEL) values (84, 'BackOffice Temporário', 'A', 3);

INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 32);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 11);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3000);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3008);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3022);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3005);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3013);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3006);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3001);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3002);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3016);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3014);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3019);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3020);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3021);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3003);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3017);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 2015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3027);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3028);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 84, 40, 3029);

INSERT INTO cargo (id, nome, situacao, FK_NIVEL) values (85, 'Vendedor BackOffice Temporário', 'A', 3);

INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 32);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 11);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3000);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3008);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3022);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3005);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3013);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3006);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3001);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3002);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3016);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3014);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3019);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3020);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3021);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3003);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3017);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 2015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3027);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3028);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3015);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 2021);
INSERT INTO CARGO_DEPART_FUNC (id, data_cadastro, fk_cargo, fk_departamento, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 85, 40, 3029);