INSERT INTO cargo (id, nome, codigo, situacao, fk_nivel) values (87, 'Vendedor Televendas Receptivo', 'AGENTE_AUTORIZADO_VENDEDOR_TELEVENDAS_RECEPTIVO', 'A', 3);

Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3000, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3001, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3002, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3003, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3007, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3009, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3010, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 11, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 32, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3005, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3006, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3013, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 9004, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3014, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 2021, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3019, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3020, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3029, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO,FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 87, 40, 3015, 124343);

INSERT INTO cargo (id, nome, codigo, situacao, fk_nivel) values (88, 'Vendedor Back Office Receptivo', 'AGENTE_AUTORIZADO_BACKOFFICE_TELEVENDAS_RECEPTIVO', 'A', 3);

Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 32, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 11, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3000, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3008, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3022, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3005, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3013, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3006, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3001, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3002, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3016, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 9004, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3014, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3019, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3020, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3021, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3003, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3017, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 2015, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3027, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3028, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3029, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 9001, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 9002, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 88, 40, 3015, 124343);

INSERT INTO cargo (id, nome, codigo, situacao, fk_nivel) values (89, 'Vendedor Back Office Televendas Receptivo', 'AGENTE_AUTORIZADO_VENDEDOR_BACKOFFICE_TELEVENDAS_RECEPTIVO', 'A', 3);

Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 9004, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 11, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 32, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 2015, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 2021, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3000, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3001, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3002, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3003, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3005, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3006, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3007, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3008, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3009, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3010, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3013, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3014, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3016, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3017, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3019, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3020, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3021, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3029, 124343);
Insert into CARGO_DEPART_FUNC(ID ,DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 89, 40, 3015, 124343);



INSERT INTO cargo (id, nome, codigo, situacao, fk_nivel) values (90, 'Supervisor Receptivo', 'AGENTE_AUTORIZADO_SUPERVISOR_RECEPTIVO', 'A', 3);

Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 9004, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 2015, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3000, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3001, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3002, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3003, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3007, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3008, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3009, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3010, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 5000, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 5001, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 5002, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 5003, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 5004, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 4, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 11, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 5, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 32, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3014, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3019, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3020, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3021, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 3029, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 9001, 124343);
Insert into CARGO_DEPART_FUNC (ID,DATA_CADASTRO,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE,FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 90, 40, 2025, 124343);



INSERT INTO cargo (id, nome, codigo, situacao, fk_nivel) values (91, 'Gerente Receptivo', 'AGENTE_AUTORIZADO_GERENTE_RECEPTIVO', 'A', 3);

Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3016, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3017, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3022, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 9004, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3000, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3001, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3002, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3003, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3004, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3007, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3008, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3009, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3010, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 5000, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 5001, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 5002, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 5003, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 5004, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 4, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 11, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 5, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 32, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3014, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 2015, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3019, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3020, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3021, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3027, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3028, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 3029, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 9001, 124343);
Insert into CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) values (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 91, 40, 9002, 124343);

