INSERT INTO NIVEL(ID, CODIGO, EXIBIR_CAD_USUARIO, NOME, SITUACAO) VALUES(16, 'ATIVO_LOCAL_COLABORADOR', 'V', 'Ativo Local Colaborador', 'A');

INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (92, 'VENDEDOR_ATIVO_LOCAL_COLABORADOR', 'Vendedor Ativo Local Colaborador', 'A', 16);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (93, 'SUPERVISOR_ATIVO_LOCAL_COLABORADOR', 'Supervisor Ativo Local Colaborador', 'A', 16);

INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (67, 'COMERCIAL', 'Comercial', 'A', 16);