
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2032, 'Obrigatório selecionar Cidades de atuação', 'AUT_2032', 1);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 2, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 5, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 6, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 7, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 8, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 9, 3, 2032, 104703, CURRENT_DATE);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 10, 3, 2032, 104703, CURRENT_DATE);

ALTER TABLE USUARIO ADD FOTO_DIRETORIO VARCHAR(255);
ALTER TABLE USUARIO ADD FOTO_NOME_ORIGINAL VARCHAR(255);
ALTER TABLE USUARIO ADD FOTO_CONTENT_TYPE VARCHAR(255);

ALTER TABLE USUARIO_AUD ADD FOTO_DIRETORIO VARCHAR(255);
ALTER TABLE USUARIO_AUD ADD FOTO_NOME_ORIGINAL VARCHAR(255);
ALTER TABLE USUARIO_AUD ADD FOTO_CONTENT_TYPE VARCHAR(255);

ALTER TABLE USUARIO_AUD ADD IMEI NUMBER(16);