
CREATE TABLE CARGO_SUPERIOR (
  "FK_CARGO" NUMBER(10,0) NOT NULL,
  "FK_CARGO_SUPERIOR" NUMBER(10,0) NOT NULL,
  CONSTRAINT "FK_CARGO_SUP_CARGO" FOREIGN KEY ("FK_CARGO") REFERENCES CARGO ("ID"),
  CONSTRAINT "FK_CARGO_SUP_CARGO_SUPER" FOREIGN KEY ("FK_CARGO_SUPERIOR") REFERENCES CARGO ("ID")
);

INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (4, 7);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (5, 7);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (5, 4);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (7, 6);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (10, 4);
