
CREATE TABLE CARGO_SUPERIOR (
  "FK_CARGO" NUMBER(10,0) NOT NULL,
  "FK_CARGO_SUPERIOR" NUMBER(10,0) NOT NULL,
  CONSTRAINT "FK_CARGO_SUP_CARGO" FOREIGN KEY ("FK_CARGO") REFERENCES CARGO ("ID"),
  CONSTRAINT "FK_CARGO_SUP_CARGO_SUPER" FOREIGN KEY ("FK_CARGO_SUPERIOR") REFERENCES CARGO ("ID")
);

INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (4, 7);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (5, 7);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (5, 4);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (7, 6);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (10, 4);

ALTER TABLE CARGO DROP COLUMN FK_CARGO_SUPERIOR;

--######### ROLBACK #########

--ALTER TABLE CARGO ADD FK_CARGO_SUPERIOR NUMBER(10);
--ALTER TABLE CARGO ADD CONSTRAINT FK_CARGO_CARGO_SUPER FOREIGN KEY (FK_CARGO_SUPERIOR) REFERENCES CARGO (ID);

--UPDATE CARGO SET FK_CARGO_SUPERIOR = 6 WHERE ID = 7;
--UPDATE CARGO SET FK_CARGO_SUPERIOR = 7 WHERE ID = 4;
--UPDATE CARGO SET FK_CARGO_SUPERIOR = 5 WHERE ID = 4;
--UPDATE CARGO SET FK_CARGO_SUPERIOR = 4 WHERE ID = 10;
