
UPDATE CARGO SET CODIGO = 'AGENTE_AUTORIZADO_COORDENADOR' WHERE ID = 45;
UPDATE CARGO SET CODIGO = 'AGENTE_AUTORIZADO_EMPRESARIO' WHERE ID = 46;
UPDATE CARGO SET CODIGO = 'AGENTE_AUTORIZADO_APRENDIZ' WHERE ID = 43;
UPDATE CARGO SET CODIGO = 'AGENTE_AUTORIZADO_ASSISTENTE' WHERE ID = 44;
UPDATE CARGO SET CODIGO = 'MSO_GERENTE' WHERE ID = 24;
UPDATE CARGO SET CODIGO = 'MSO_ANALISTA' WHERE ID = 20;
UPDATE CARGO SET CODIGO = 'MSO_COORDENADOR' WHERE ID = 23;
UPDATE CARGO SET CODIGO = 'MSO_DIRETOR' WHERE ID = 25;
UPDATE CARGO SET CODIGO = 'MSO_AUDITORIA' WHERE ID = 52;
UPDATE CARGO SET CODIGO = 'MSO_ASSISTENTE' WHERE ID = 21;
UPDATE CARGO SET CODIGO = 'OPERACAO_ANALISTA' WHERE ID = 1;
UPDATE CARGO SET CODIGO = 'OPERACAO_CONSULTOR' WHERE ID = 3;
UPDATE CARGO SET CODIGO = 'OPERACAO_TECNICO' WHERE ID = 9;

ALTER TABLE CARGO MODIFY CODIGO VARCHAR(80) NOT NULL;
ALTER TABLE CARGO ADD FK_CARGO_SUPERIOR NUMBER(10);
ALTER TABLE CARGO ADD CONSTRAINT FK_CARGO_CARGO_SUPER FOREIGN KEY (FK_CARGO_SUPERIOR) REFERENCES CARGO (ID);

UPDATE CARGO SET FK_CARGO_SUPERIOR = 6 WHERE ID = 7;
UPDATE CARGO SET FK_CARGO_SUPERIOR = 7 WHERE ID = 4;
UPDATE CARGO SET FK_CARGO_SUPERIOR = 4 WHERE ID = 10;