
UPDATE CARGO SET FK_CARGO_SUPERIOR = NULL;
UPDATE CARGO SET FK_CARGO_SUPERIOR = 6 WHERE ID = 7;
UPDATE CARGO SET FK_CARGO_SUPERIOR = 7 WHERE ID = 4;
UPDATE CARGO SET FK_CARGO_SUPERIOR = 4 WHERE ID = 5;
UPDATE CARGO SET FK_CARGO_SUPERIOR = 4 WHERE ID = 10;