ALTER TABLE FERIADO ADD (
    TIPO_FERIADO VARCHAR(255),
    FK_UF INTEGER,
    SITUACAO VARCHAR(255) DEFAULT 'ATIVO',
    FK_FERIADO_PAI INTEGER,
    FK_USUARIO_CADASTRO INTEGER
);

ALTER TABLE FERIADO ADD CONSTRAINT FK_FERIADO_UF FOREIGN KEY (FK_UF) REFERENCES UF;
ALTER TABLE FERIADO ADD CONSTRAINT FK_FERIADO_FERIADO_PAI FOREIGN KEY (FK_FERIADO_PAI) REFERENCES FERIADO;
ALTER TABLE FERIADO ADD CONSTRAINT FK_FERIADO_USUARIO_CAD FOREIGN KEY (FK_USUARIO_CADASTRO) REFERENCES USUARIO;