--PERMISSÃO DASHBOARD NÚMEROS TABULAÇÃO OPERADOR_TELEVENDAS
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 120, 3, 3019);
--PERMISSÃO DASHBOARD RELATÓRIO TABULACÃO OPERADOR_TELEVENDAS
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 120, 3, 3020);

