
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3053, 'Visualizar Pré-Venda', 'VDS_3053', 3);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3054, 'Cadastrar Pré-Venda', 'VDS_3054', 3);


-- Configuração de quais usuários poderão ter acesso a tela de LISTAGEM de pre venda
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 3, 3053); -- cargo: Analista / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 2, 3, 3053); -- cargo: Assistente / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 3, 3053); -- cargo: Consultor / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 3053); -- cargo: Coordenador / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 5, 3, 3053); -- cargo: Executivo / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 6, 3, 3053); -- cargo: Diretor / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 7, 3, 3053); -- cargo: Gerente / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 8, 3, 3053); -- cargo: Vendedor / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 9, 3, 3053); -- cargo: Técnico / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 10, 3, 3053); -- cargo: Supervisor / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 94, 3, 3053); -- cargo: Assistente Hunter / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 95, 3, 3053); -- cargo: Executivo Hunter / departamento: Comercial / nivel: OPERACAO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 20, 21, 3053); -- cargo: Analista / departamento: Comercial / nivel: MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 21, 21, 3053); -- cargo: Assistente / departamento: Comercial / nivel: MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 3053); -- cargo: Consultor / departamento: Comercial / nivel: MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 23, 21, 3053); -- cargo: Coordenador / departamento: Comercial / nivel: MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 24, 21, 3053); -- cargo: Gerente / departamento: Comercial / nivel: MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 25, 21, 3053); -- cargo: Diretor / departamento: Comercial / nivel: MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 52, 21, 3053); -- cargo: Auditoria / departamento: Comercial / nivel: MSO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 87, 40, 3053); -- cargo: Vendedor Televendas Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 88, 40, 3053); -- cargo: Vendedor Back Office Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 89, 40, 3053); -- cargo: Vendedor Back Office Televendas Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 90, 40, 3053); -- cargo: Supervisor Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 91, 40, 3053); -- cargo: Gerente Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 40, 40, 3053); -- cargo: Aceite / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 41, 40, 3053); -- cargo: Sócio Principal / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 42, 40, 3053); -- cargo: Sócio Secundário / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 43, 40, 3053); -- cargo: Aprendiz / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 44, 40, 3053); -- cargo: Assistente / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 45, 40, 3053); -- cargo: Coordenador / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 46, 40, 3053); -- cargo: Empresário / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 47, 40, 3053); -- cargo: Gerente / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 48, 40, 3053); -- cargo: Supervisor / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 49, 40, 3053); -- cargo: Vendedor Híbrido / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 56, 40, 3053); -- cargo: Back Office Televendas / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 78, 40, 3053); -- cargo: Back Office D2D / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 57, 40, 3053); -- cargo: Vendedor D2D / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 58, 40, 3053); -- cargo: Vendedor Televendas / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 79, 40, 3053); -- cargo: Vendedor Back Office D2D / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 80, 40, 3053); -- cargo: Vendedor Back Office Televendas  / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 81, 40, 3053); -- cargo: Supervisor* / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 82, 40, 3053); -- cargo: Gerente* / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 83, 40, 3053); -- cargo: Vendedor* / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 84, 40, 3053); -- cargo: BackOffice* / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 85, 40, 3053); -- cargo: Vendedor BackOffice* / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 51, 3053); -- cargo: Administrador / departamento: HelpDesk / nivel: XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 3053); -- cargo: Administrador / departamento: Administrador / nivel: XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 51, 51, 3053); -- cargo: Analista de Suporte / departamento: HelpDesk / nivel: XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 51, 50, 3053); -- cargo: Analista de Suporte / departamento: Administrador / nivel: XBRAIN

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 53, 54, 3053); -- cargo: Gerente / departamento: Varejo / nivel: VAREJO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 54, 54, 3053); -- cargo: Supervisor / departamento: Varejo / nivel: VAREJO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 55, 54, 3053); -- cargo: Vendedor / departamento: Varejo / nivel: VAREJO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 59, 55, 3053); -- cargo: Vendedor Atendimento Pessoal / departamento: Comercial / nivel: ATP
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 60, 55, 3053); -- cargo: Supervisor Atendimento Pessoal / departamento: Comercial / nivel: ATP

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 61, 56, 3053); -- cargo: Vendedor Lojas / departamento: Comercial / nivel: LOJAS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 62, 56, 3053); -- cargo: Supervisor Lojas / departamento: Comercial / nivel: LOJAS

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 63, 57, 3053); -- cargo: Vendedor Receptivo / departamento: Comercial / nivel: RECEPTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 64, 57, 3053); -- cargo: Supervisor Receptivo / departamento: Comercial / nivel: RECEPTIVO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 65, 58, 3053); -- cargo: Vendedor Ativo Local Proprio / departamento: Comercial / nivel: ATIVO_LOCAL_PROPRIO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 66, 58, 3053); -- cargo: Supervisor Ativo Local Proprio / departamento: Comercial / nivel: ATIVO_LOCAL_PROPRIO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 67, 59, 3053); -- cargo: Vendedor Ativo Local Terceiro / departamento: Comercial / nivel: ATIVO_LOCAL_TERCEIRO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 68, 59, 3053); -- cargo: Supervisor Ativo Local Terceiro / departamento: Comercial / nivel: ATIVO_LOCAL_TERCEIRO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 69, 60, 3053); -- cargo: Vendedor Receptivo Segmentado / departamento: Comercial / nivel: RECEPTIVO_SEGMENTADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 70, 60, 3053); -- cargo: Supervisor Receptivo Segmentado / departamento: Comercial / nivel: RECEPTIVO_SEGMENTADO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 71, 61, 3053); -- cargo: Vendedor AA Nacional / departamento: Comercial / nivel: ATIVO_NACIONAL_TERCEIRO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 72, 61, 3053); -- cargo: Supervisor AA Nacional / departamento: Comercial / nivel: ATIVO_NACIONAL_TERCEIRO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 73, 62, 3053); -- cargo: Vendedor Ativo Local Terceiro Segmentado / departamento: Comercial / nivel: ATIVO_NACIONAL_TERCEIRO_SEGMENTADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 74, 62, 3053); -- cargo: Supervisor Ativo Local Terceiro Segmentado / departamento: Comercial / nivel: ATIVO_NACIONAL_TERCEIRO_SEGMENTADO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 75, 63, 3053); -- cargo: Vendedor Ativo Rentabilização / departamento: Comercial / nivel: ATIVO_RENTABILIZACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 76, 63, 3053); -- cargo: Supervisor Ativo Rentabilização / departamento: Comercial / nivel: ATIVO_RENTABILIZACAO

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 92, 67, 3053); -- cargo: Vendedor Ativo Local Colaborador / departamento: Comercial / nivel: ATIVO_LOCAL_COLABORADOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 93, 67, 3053); -- cargo: Supervisor Ativo Local Colaborador / departamento: Comercial / nivel: ATIVO_LOCAL_COLABORADOR




-- Configuração de quais usuários poderão ter acesso a tela de CADASTRO de pre venda
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 8, 3, 3054); -- cargo: Vendedor / departamento: Comercial / nivel: OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 87, 40, 3054); -- cargo: Vendedor Televendas Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 88, 40, 3054); -- cargo: Vendedor Back Office Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 89, 40, 3054); -- cargo: Vendedor Back Office Televendas Receptivo / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 49, 40, 3054); -- cargo: Vendedor Híbrido / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 57, 40, 3054); -- cargo: Vendedor D2D / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 58, 40, 3054); -- cargo: Vendedor Televendas / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 79, 40, 3054); -- cargo: Vendedor Back Office D2D / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 80, 40, 3054); -- cargo: Vendedor Back Office Televendas  / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 83, 40, 3054); -- cargo: Vendedor* / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 85, 40, 3054); -- cargo: Vendedor BackOffice* / departamento: Agente Autorizado / nivel: AGENTE_AUTORIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 55, 54, 3054); -- cargo: Vendedor / departamento: Varejo / nivel: VAREJO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 59, 55, 3054); -- cargo: Vendedor Atendimento Pessoal / departamento: Comercial / nivel: ATP
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 61, 56, 3054); -- cargo: Vendedor Lojas / departamento: Comercial / nivel: LOJAS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 63, 57, 3054); -- cargo: Vendedor Receptivo / departamento: Comercial / nivel: RECEPTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 65, 58, 3054); -- cargo: Vendedor Ativo Local Proprio / departamento: Comercial / nivel: ATIVO_LOCAL_PROPRIO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 67, 59, 3054); -- cargo: Vendedor Ativo Local Terceiro / departamento: Comercial / nivel: ATIVO_LOCAL_TERCEIRO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 69, 60, 3054); -- cargo: Vendedor Receptivo Segmentado / departamento: Comercial / nivel: RECEPTIVO_SEGMENTADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 71, 61, 3054); -- cargo: Vendedor AA Nacional / departamento: Comercial / nivel: ATIVO_NACIONAL_TERCEIRO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 73, 62, 3054); -- cargo: Vendedor Ativo Local Terceiro Segmentado / departamento: Comercial / nivel: ATIVO_NACIONAL_TERCEIRO_SEGMENTADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 75, 63, 3054); -- cargo: Vendedor Ativo Rentabilização / departamento: Comercial / nivel: ATIVO_RENTABILIZACAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 92, 67, 3054); -- cargo: Vendedor Ativo Local Colaborador / departamento: Comercial / nivel: ATIVO_LOCAL_COLABORADOR
