CREATE TABLE ORGANIZACAO_NIVEL (FK_NIVEL INTEGER NOT NULL, FK_ORGANIZACAO INTEGER NOT NULL);

ALTER TABLE ORGANIZACAO_NIVEL ADD CONSTRAINT FK_ORG_NIVEL_ORGANIZACAO FOREIGN KEY (FK_ORGANIZACAO) REFERENCES ORGANIZACAO ;
ALTER TABLE ORGANIZACAO_NIVEL ADD CONSTRAINT FK_ORG_NIVEL_NIVEL FOREIGN KEY (FK_NIVEL) REFERENCES NIVEL;

INSERT INTO NIVEL(ID, CODIGO, EXIBIR_CAD_USUARIO, NOME, SITUACAO) VALUES(SEQ_NIVEL.NEXTVAL, 'BACKOFFICE', 'V', 'Backoffice', 'A');

INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (5, 'CSU', 'CSU');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (6, 'MOTIVA', 'Motiva');

-- CSU
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (SEQ_NIVEL.CURRVAL, 5);

-- MOTIVA
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (SEQ_NIVEL.CURRVAL, 6);

-- CALLLINK
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (1, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (2, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (3, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (4, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (8, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (9, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (11, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (13, 2);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (15, 2);

-- BRASIL CENTER
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (1, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (2, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (3, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (4, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (8, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (9, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (11, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (13, 1);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (15, 1);

-- PROPRIO
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (1, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (2, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (3, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (4, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (8, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (9, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (11, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (13, 3);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (15, 3);

-- VGX
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (1, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (2, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (3, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (4, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (8, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (9, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (11, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (13, 21);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (15, 21);

-- ATENTO
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (1, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (2, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (3, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (4, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (8, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (9, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (11, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (13, 4);
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES (15, 4);

-- CARGOS
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (110, 'BACKOFFICE_OPERADOR_TRATAMENTO_ONLINE', 'Operador Tratamento Online', 'A', 18);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (111, 'BACKOFFICE_OPERADOR_TRATAMENTO_OFFLINE', 'Operador Tratamento Offline', 'A', 18);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (112, 'BACKOFFICE_SUPERVISOR', 'Supervisor', 'A', 18);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (113, 'BACKOFFICE_COORDENADOR', 'Coordenador', 'A', 18);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (114, 'BACKOFFICE_GERENTE', 'Gerente', 'A', 18);

-- DEPARTAMENTO
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (69, 'COMERCIAL', 'Comercial', 'A', 18);

-- APLICAÇÃO
INSERT INTO APLICACAO (ID, NOME, CODIGO) VALUES (24, 'BACKOFFICE', 'BKO');

-- FUNCIONALIDADE
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16000, 'Realizar tratamento de pendências', 'BKO_15000', 24);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16001, 'Visualizar tratativas pendentes de análise externa', 'BKO_15001', 24);

-- PERMISSAO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 110, 69, 16000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 111, 69, 16000);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 111, 69, 16001);




