-------------------
---- APLICAÇÃO ----
-------------------
INSERT INTO APLICACAO (ID, CODIGO, NOME) VALUES (SEQ_APLICACAO.NEXTVAL, 'PAP', 'SOLICITACAO CLIENTE PAP');

------------------------
---- FUNCIONALIDADE ----
------------------------
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (SEQ_FUNCIONALIDADE.NEXTVAL, 'Gerenciar Solicitacoes cliente PaP', 'CTR_GERENCIAR_SOLICITACOES_PAP', (SELECT ID FROM APLICACAO WHERE CODIGO ='PAP'));

--------------------
---- PERMISSÕES ---- FALTA VER QUAL CAGO E DEPARTAMENTO É O CORRETO
--------------------
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE ='CTR_GERENCIAR_SOLICITACOES_PAP'));
