BEGIN
    FOR PERM IN (
        SELECT
            FK_FUNCIONALIDADE,
            FK_USUARIO,
            CANAL
        FROM
            CARGO_DEPART_FUNC
        WHERE
            FK_CARGO = 22
            AND FK_DEPARTAMENTO = 21
            AND FK_FUNCIONALIDADE NOT IN (
                SELECT FK_FUNCIONALIDADE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 3 AND FK_DEPARTAMENTO = 12
                UNION
                SELECT FK_FUNCIONALIDADE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 22 AND FK_DEPARTAMENTO = 30
            )
    )
    LOOP
        INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL)
            VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 3, 12, PERM.FK_FUNCIONALIDADE, PERM.FK_USUARIO, PERM.CANAL);
        INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL)
            VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 22, 30, PERM.FK_FUNCIONALIDADE, PERM.FK_USUARIO, PERM.CANAL);
    END LOOP;
END;