-- Feriados Nacionais 2021
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Confraternização Universal', '01-Jan-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Carnaval', '15-Feb-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Carnaval', '16-Feb-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Paixão de Cristo', '2-Apr-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Tiradentes', '21-Apr-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Dia do Trabalho', '01-May-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Independência do Brasil', '07-Sep-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Nossa Sr.a Aparecida - Padroeira do Brasil', '12-Oct-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Finados', '02-Nov-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Proclamação da República', '15-Nov-2021', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Natal', '25-Dec-2021', 'V', NULL, CURRENT_TIMESTAMP);

-- Feriados Municipais

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Santos Reis', '6-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'NATAL' and uf.uf = 'RN';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '12-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELEM' and uf.uf = 'PA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'são sebastião', '20-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Sebastião', '20-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RIO DE JANEIRO' and uf.uf = 'RJ';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São Francisco de Sales', '24-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO VELHO' and uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '25-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO PAULO' and uf.uf = 'SP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora dos Navegantes', '2-Feb-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO ALEGRE' and uf.uf = 'RS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '4-Feb-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACAPA' and uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Carnaval', '16-Feb-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MANAUS' and uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Quarta de cinzas', '17-Feb-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MANAUS' and uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '17-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'ARACAJU' and uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de são josé', '19-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FORTALEZA' and uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'são josé', '19-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PALMAS' and uf.uf = 'TO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '23-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FLORIANOPOLIS' and uf.uf = 'SC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '3-Apr-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CUIABA' and uf.uf = 'MT';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '13-Apr-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FORTALEZA' and uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '20-May-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PALMAS' and uf.uf = 'TO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira da Cidade', '24-May-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'GOIANIA' and uf.uf = 'GO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'ARACAJU' and uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELO HORIZONTE' and uf.uf = 'MG';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CAMPO GRANDE' and uf.uf = 'MS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CUIABA' and uf.uf = 'MT';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CURITIBA' and uf.uf = 'PR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FLORIANOPOLIS' and uf.uf = 'SC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FORTALEZA' and uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'GOIANIA' and uf.uf = 'GO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACEIO' and uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'NATAL' and uf.uf = 'RN';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO ALEGRE' and uf.uf = 'RS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SALVADOR' and uf.uf = 'BA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO PAULO' and uf.uf = 'SP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'TERESINA' and uf.uf = 'PI';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Corpus Christi', '3-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'VITORIA' and uf.uf = 'ES';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de Santo Antonio', '13-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CAMPO GRANDE' and uf.uf = 'MS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'são joão', '24-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'ARACAJU' and uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'dia de são joão', '24-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'JOAO PESSOA' and uf.uf = 'PB';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'dia de são joão', '24-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SALVADOR' and uf.uf = 'BA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'são pedro', '29-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Pedro', '29-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '9-Jul-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira da Cidade', '16-Jul-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RECIFE' and uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Assunção de Nossa Senhora', '15-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELO HORIZONTE' and uf.uf = 'MG';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'nossa senhora da assunção', '15-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FORTALEZA' and uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '16-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'TERESINA' and uf.uf = 'PI';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '26-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CAMPO GRANDE' and uf.uf = 'MS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira da Cidade', '27-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACEIO' and uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, ' N. Sra da Luz dos Pinhais', '8-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CURITIBA' and uf.uf = 'PR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Natividade de nossa senhora', '8-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Vitoria', '8-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'VITORIA' and uf.uf = 'ES';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '2-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO VELHO' and uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do comerciário', '18-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '24-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'GOIANIA' and uf.uf = 'GO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '24-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MANAUS' and uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO PAULO' and uf.uf = 'SP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'N. Sra da Apresentação', '21-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'NATAL' and uf.uf = 'RN';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '30-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BRASILIA' and uf.uf = 'DF';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'ARACAJU' and uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELEM' and uf.uf = 'PA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELO HORIZONTE' and uf.uf = 'MG';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CUIABA' and uf.uf = 'MT';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'JOAO PESSOA' and uf.uf = 'PB';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACEIO' and uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACEIO' and uf.uf = 'BA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RECIFE' and uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'TERESINA' and uf.uf = 'PI';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '28-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RIO BRANCO' and uf.uf = 'AC';

-- FERIADOS ESTADUAIS

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Estado', '4-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Católico', '22-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '23-Jan-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Carnaval', '16-Feb-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RJ';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Revolução Pernambucana', '6-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Mulher', '12-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de são josé', '19-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Data magna do ceará', '25-Mar-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Estado', '12-Apr-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'ES';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Jorge', '23-Apr-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RJ';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'dia de cabralzinho', '15-May-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Acre', '15-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '18-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São João', '24-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Pedro', '24-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Pedro', '29-Jun-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Independência da Bahia', '2-Jul-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'BA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Estado', '8-Jul-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Revolução Constitucionalista', '9-Jul-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'SP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Adesão ao Imperio Brasileiro', '28-Jul-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Fundação do estado da paraiba', '5-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PB';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Revolução Acreana', '6-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Adesão ao Imperio Brasileiro', '15-Aug-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Amazônia', '5-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Estado', '5-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira do Estado', '8-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'TO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da criação do ex-território federal do Amapá', '13-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Emancipação de Alagoas', '16-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Proc. República Rio Grandense', '20-Sep-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Mártires de Cunhaú e Uruaçu', '3-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RN';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Estado', '5-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Estado', '5-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'TO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Estado', '11-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'MS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Piaui', '19-Oct-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PI';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RJ';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'MT';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '30-Nov-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia Nossa senhora da conceição', '8-Dec-2021', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AM';
