-- REMOVE PERMISSAO GERENCIAR MAILING ATIVO LOCAL, DO CARGO DIRETOR OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 6 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3055;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 6 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3056;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 6 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3057;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 6 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3058;