DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID IN (3051, 3052);

    IF QTD = 0 THEN
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3051, 'VISUALIZAR TRATATIVAS', 'VDS_3051', 3);
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3052, 'CRIAR TRATATIVAS', 'VDS_3052', 3);

        FOR C IN (SELECT DISTINCT FK_CARGO, FK_DEPARTAMENTO FROM CARGO_DEPART_FUNC WHERE FK_CARGO NOT IN (110, 111, 112, 113, 114))
           LOOP
              INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, C.FK_CARGO, C.FK_DEPARTAMENTO, 3051);
              INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, C.FK_CARGO, C.FK_DEPARTAMENTO, 3052);
           END LOOP;
    END IF;
END;