-- ADD PERMISSAO GERENCIAR EQUIPE VENDA ATIVO LOCAL PARA CARGO DE DIRETORES
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL)
    VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 6, 3, 2048, 'ATIVO_PROPRIO');