-- OPERAÇÃO COMERCIAL OPERADOR_TELEVENDAS REALIZAR PAUSAS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 120, 3, 2036, 110827);
