update cidade set CODIGO_CIDADE_DBM= 742 where nome= 'SETE LAGOAS' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 477 where nome= 'TIMOTEO' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 126 where nome= 'JUIZ DE FORA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 803 where nome= 'UBERABA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 806 where nome= 'UBERLANDIA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 867 where nome= 'DOURADOS' and fk_uf=(select id from uf where uf='MS');
update cidade set CODIGO_CIDADE_DBM= 70 where nome= 'BRUSQUE' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 66 where nome= 'RIO BRANCO' and fk_uf=(select id from uf where uf='MT');
update cidade set CODIGO_CIDADE_DBM= 818 where nome= 'RONDONOPOLIS' and fk_uf=(select id from uf where uf='MT');
update cidade set CODIGO_CIDADE_DBM= 837 where nome= 'SINOP' and fk_uf=(select id from uf where uf='MT');
update cidade set CODIGO_CIDADE_DBM= 389 where nome= 'CAMPO LARGO' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 2 where nome= 'MARABA' and fk_uf=(select id from uf where uf='PA');
update cidade set CODIGO_CIDADE_DBM= 538 where nome= 'AMPARO' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 133 where nome= 'CABEDELO' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 194 where nome= 'BELEn' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 291 where nome= 'PAULISTA' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 129 where nome= 'SANTO ANDRE' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 195 where nome= 'SERTAOZINHO' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 152 where nome= 'CARUARU' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 269 where nome= 'OLINDA' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 637 where nome= 'PARNAMIRIM' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 956 where nome= 'PETROLINA' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 87 where nome= 'CAPAO DA CANOA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 379 where nome= 'CAMBE' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 530 where nome= 'CAPIVARI' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 241 where nome= 'TIETE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 882 where nome= 'MONTE MOR' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 48 where nome= 'RAFARD' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 924 where nome= 'OSASCO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 443 where nome= 'BARUERI' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 567 where nome= 'COTIA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 533 where nome= 'CARAPICUIBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 599 where nome= 'EMBU' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 621 where nome= 'SANTANA DE PARNAIBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 216 where nome= 'TABOAO DA SERRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 765 where nome= 'JANDIRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 714 where nome= 'ITAPECERICA DA SERRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 722 where nome= 'ITAPEVI' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 276 where nome= 'VARGEM GRANDE PAULISTA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 656 where nome= 'GUARATINGUETA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 24 where nome= 'POTIM' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 572 where nome= 'CRUZEIRO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 795 where nome= 'LORENA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 719 where nome= 'CUIABA' and fk_uf=(select id from uf where uf='MT');
update cidade set CODIGO_CIDADE_DBM= 540 where nome= 'PALMAS' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 161 where nome= 'DUQUE DE CAXIAS' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 239 where nome= 'MESQUITA' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 95 where nome= 'NATAL' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 91 where nome= 'MARINGA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 226 where nome= 'NILOPOLIS' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 237 where nome= 'NOVA IGUACU' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 316 where nome= 'SAO JOAO DE MERITI' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 96 where nome= 'SAO LUIS' and fk_uf=(select id from uf where uf='MA');
update cidade set CODIGO_CIDADE_DBM= 63 where nome= 'TERESINA' and fk_uf=(select id from uf where uf='PI');
update cidade set CODIGO_CIDADE_DBM= 858 where nome= 'VARZEA GRANDE' and fk_uf=(select id from uf where uf='MT');
update cidade set CODIGO_CIDADE_DBM= 3 where nome= 'SAO PAULO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 413 where nome= 'ARARAS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 53 where nome= 'SAO CARLOS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 637 where nome= 'PARNAMIRIM' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 93 where nome= 'ARAPONGAS' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 409 where nome= 'ARARAQUARA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 661 where nome= 'GUARULHOS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 34 where nome= 'ARRAIAL DO CABO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 715 where nome= 'ITAPETININGA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 746 where nome= 'ITU' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 115 where nome= 'CABO FRIO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 529 where nome= 'CAMPOS DOS GOYTACAZES' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 55 where nome= 'JUNDIAI' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 197 where nome= 'MACAE' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 996 where nome= 'LONDRINA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 820 where nome= 'MARILIA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 856 where nome= 'MOGI DAS CRUZES' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 976 where nome= 'PINDAMONHANGABA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 6 where nome= 'SAO JOSE DO RIO PRETO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 162 where nome= 'SAO JOSE DOS CAMPOS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 76 where nome= 'RIO CLARO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 235 where nome= 'TAUBATE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 305 where nome= 'SAO GONCALO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 129 where nome= 'SANTO ANDRE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 320 where nome= 'SAO PEDRO DA ALDEIA' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 359 where nome= 'VOLTA REDONDA' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 865 where nome= 'MOGI MIRIM' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 947 where nome= 'MOSSORO' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 54 where nome= 'INDAIATUBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 207 where nome= 'SUMARE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 75 where nome= 'SANTA MARIA' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 294 where nome= 'ALMIRANTE TAMANDARE' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 685 where nome= 'CRUZ ALTA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 66 where nome= 'RIO BRANCO' and fk_uf=(select id from uf where uf='AC');
update cidade set CODIGO_CIDADE_DBM= 194 where nome= 'BELEn' and fk_uf=(select id from uf where uf='AL');
update cidade set CODIGO_CIDADE_DBM= 11 where nome= 'CAMPO GRANDE' and fk_uf=(select id from uf where uf='AL');
update cidade set CODIGO_CIDADE_DBM= 750 where nome= 'CAMACARI' and fk_uf=(select id from uf where uf='BA');
update cidade set CODIGO_CIDADE_DBM= 851 where nome= 'ROLANDIA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 220 where nome= 'PORTO VELHO' and fk_uf=(select id from uf where uf='RO');
update cidade set CODIGO_CIDADE_DBM= 749 where nome= 'PARANAGUA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 641 where nome= 'CASCAVEL' and fk_uf=(select id from uf where uf='CE');
update cidade set CODIGO_CIDADE_DBM= 910 where nome= 'NOVA ODESSA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 572 where nome= 'CRUZEIRO' and fk_uf=(select id from uf where uf='DF');
update cidade set CODIGO_CIDADE_DBM= 75 where nome= 'SANTA MARIA' and fk_uf=(select id from uf where uf='DF');
update cidade set CODIGO_CIDADE_DBM= 917 where nome= 'CARIACICA' and fk_uf=(select id from uf where uf='ES');
update cidade set CODIGO_CIDADE_DBM= 566 where nome= 'SERRA' and fk_uf=(select id from uf where uf='ES');
update cidade set CODIGO_CIDADE_DBM= 895 where nome= 'APARECIDA DE GOIANIA' and fk_uf=(select id from uf where uf='GO');
update cidade set CODIGO_CIDADE_DBM= 73 where nome= 'CALDAS NOVAS' and fk_uf=(select id from uf where uf='GO');
update cidade set CODIGO_CIDADE_DBM= 852 where nome= 'FEIRA DE SANTANA' and fk_uf=(select id from uf where uf='BA');
update cidade set CODIGO_CIDADE_DBM= 51 where nome= 'IMPERATRIZ' and fk_uf=(select id from uf where uf='MA');
update cidade set CODIGO_CIDADE_DBM= 455 where nome= 'ARAGUARI' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 514 where nome= 'BETIM' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 753 where nome= 'CONTAGEM' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 832 where nome= 'DIVINOPOLIS' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 405 where nome= 'IPATINGA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 813 where nome= 'ITABIRA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 402 where nome= 'ITAJUBA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 43 where nome= 'LAGOA SANTA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 275 where nome= 'MONTES CLAROS' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 312 where nome= 'NOVA LIMA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 37 where nome= 'POCOS DE CALDAS' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 541 where nome= 'SABARA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 550 where nome= 'ARACAJU' and fk_uf=(select id from uf where uf='SE');
update cidade set CODIGO_CIDADE_DBM= 423 where nome= 'ATIBAIA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 302 where nome= 'BARRETOS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 456 where nome= 'BERTIOGA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 573 where nome= 'CUBATAO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 97 where nome= 'FORTALEZA' and fk_uf=(select id from uf where uf='CE');
update cidade set CODIGO_CIDADE_DBM= 659 where nome= 'GUARUJA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 668 where nome= 'HORTOLANDIA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 498 where nome= 'CAIEIRAS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 553 where nome= 'CARAGUATATUBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 565 where nome= 'COSMOPOLIS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 569 where nome= 'CRAVINHOS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 586 where nome= 'DRACENA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 923 where nome= 'SAO JOSE DOS PINHAIS' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 315 where nome= 'SAO JOSE DO RIO PARDO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 678 where nome= 'SAO ROQUE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 579 where nome= 'SERRA NEGRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 209 where nome= 'SUZANO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 233 where nome= 'TATUI' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 277 where nome= 'VARZEA PAULISTA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 282 where nome= 'VOTORANTIM' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 458 where nome= 'ALVORADA' and fk_uf=(select id from uf where uf='TO');
update cidade set CODIGO_CIDADE_DBM= 560 where nome= 'CACHOEIRINHA' and fk_uf=(select id from uf where uf='TO');
update cidade set CODIGO_CIDADE_DBM= 195 where nome= 'SERTAOZINHO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 508 where nome= 'VITORIA' and fk_uf=(select id from uf where uf='ES');
update cidade set CODIGO_CIDADE_DBM= 178 where nome= 'ANANINDEUA' and fk_uf=(select id from uf where uf='PA');
update cidade set CODIGO_CIDADE_DBM= 386 where nome= 'AMERICANA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 690 where nome= 'BAGE' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 8 where nome= 'BAURU' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 700 where nome= 'BLUMENAU' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 471 where nome= 'BOTUCATU' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 40 where nome= 'BRASILIA' and fk_uf=(select id from uf where uf='DF');
update cidade set CODIGO_CIDADE_DBM= 687 where nome= 'CAXIAS DO SUL' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 696 where nome= 'CHAPECO' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 430 where nome= 'CIANORTE' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 89 where nome= 'CRICIUMA' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 881 where nome= 'CURITIBA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 695 where nome= 'ERECHIM' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 10 where nome= 'GOIANIA' and fk_uf=(select id from uf where uf='GO');
update cidade set CODIGO_CIDADE_DBM= 531 where nome= 'GUARAPUAVA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 769 where nome= 'JAU' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 907 where nome= 'JOAO PESSOA' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 86 where nome= 'JOINVILLE' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 791 where nome= 'LIMEIRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 121 where nome= 'MANAUS' and fk_uf=(select id from uf where uf='AM');
update cidade set CODIGO_CIDADE_DBM= 228 where nome= 'NITEROI' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 691 where nome= 'PELOTAS' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 9 where nome= 'PIRACICABA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 268 where nome= 'RESENDE' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 5 where nome= 'RIBEIRAO PRETO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 38 where nome= 'RIO DE JANEIRO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 692 where nome= 'RIO GRANDE' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 230 where nome= 'SALVADOR' and fk_uf=(select id from uf where uf='BA');
update cidade set CODIGO_CIDADE_DBM= 4 where nome= 'SANTOS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 7 where nome= 'SOROCABA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 684 where nome= 'URUGUAIANA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 13 where nome= 'BELO HORIZONTE' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 56 where nome= 'FRANCA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 689 where nome= 'LAJEADO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 480 where nome= 'MACEIO' and fk_uf=(select id from uf where uf='AL');
update cidade set CODIGO_CIDADE_DBM= 693 where nome= 'PASSO FUNDO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 136 where nome= 'RECIFE' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 75 where nome= 'SANTA MARIA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 194 where nome= 'BELEM' and fk_uf=(select id from uf where uf='PA');
update cidade set CODIGO_CIDADE_DBM= 474 where nome= 'BRAGANCA PAULISTA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 712 where nome= 'ITANHAEM' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 733 where nome= 'ITAQUAQUECETUBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 761 where nome= 'JAGUARIUNA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 540 where nome= 'PALMAS' and fk_uf=(select id from uf where uf='TO');
update cidade set CODIGO_CIDADE_DBM= 798 where nome= 'LOUVEIRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 592 where nome= 'ORLANDIA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 954 where nome= 'PAULINIA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 495 where nome= 'PENAPOLIS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 143 where nome= 'SAO CAETANO DO SUL' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 36 where nome= 'PRESIDENTE PRUDENTE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 67 where nome= 'RIBEIRAO PIRES' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 104 where nome= 'SANTA BRANCA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 187 where nome= 'SAO VICENTE' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 141 where nome= 'SAO BERNARDO DO CAMPO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 96 where nome= 'SAO LUIS' and fk_uf=(select id from uf where uf='RR');
update cidade set CODIGO_CIDADE_DBM= 458 where nome= 'ALVORADA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 316 where nome= 'SAO VICENTE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 756 where nome= 'JACAREI' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 560 where nome= 'CACHOEIRINHA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 584 where nome= 'CAMPO BOM' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 601 where nome= 'CANELA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 603 where nome= 'CANOAS' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 103 where nome= 'SANTA BARBARA D OESTE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 614 where nome= 'CARAZINHO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 27 where nome= 'PRAIA GRANDE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 272 where nome= 'VALINHOS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 757 where nome= 'ESTANCIA VELHA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 758 where nome= 'ESTEIO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 83 where nome= 'FARROUPILHA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 720 where nome= 'GRAVATAI' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 728 where nome= 'GUAIBA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 223 where nome= 'JABOATAO DOS GUARARAPES' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 291 where nome= 'PAULISTA' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 499 where nome= 'PAROBE' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 42 where nome= 'LAURO DE FREITAS' and fk_uf=(select id from uf where uf='BA');
update cidade set CODIGO_CIDADE_DBM= 507 where nome= 'VILA VELHA' and fk_uf=(select id from uf where uf='ES');
update cidade set CODIGO_CIDADE_DBM= 100 where nome= 'BARRA MANSA' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 577 where nome= 'DIADEMA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 710 where nome= 'SAO LEOPOLDO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 330 where nome= 'SAPIRANGA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 332 where nome= 'SAPUCAIA DO SUL' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 493 where nome= 'XANGRI LA' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 752 where nome= 'BALNEARIO CAMBORIU' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 213 where nome= 'LAGES' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 336 where nome= 'VITORIA DA CONQUISTA' and fk_uf=(select id from uf where uf='BA');
update cidade set CODIGO_CIDADE_DBM= 780 where nome= 'TRES CORACOES' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 250 where nome= 'PETROPOLIS' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 333 where nome= 'ARAUCARIA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 154 where nome= 'GASPAR' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 163 where nome= 'GUARAMIRIM' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 278 where nome= 'PALHOCA' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 833 where nome= 'MAUA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 193 where nome= 'ITAJAI' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 94 where nome= 'ITAPEMA' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 770 where nome= 'PINHAIS' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 437 where nome= 'COLOMBO' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 236 where nome= 'VIDEIRA' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 487 where nome= 'CACAPAVA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 570 where nome= 'SAO BENTO DO SUL' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 53 where nome= 'SAO CARLOS' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 363 where nome= 'SAO JOSE' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 322 where nome= 'APUCARANA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 543 where nome= 'CATANDUVA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 911 where nome= 'CONSELHEIRO LAFAIETE' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 778 where nome= 'CORONEL FABRICIANO' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 930 where nome= 'GOVERNADOR VALADARES' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 60 where nome= 'ITUIUTABA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 884 where nome= 'CURITIBA - CABO' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 71500 where nome= 'ITAPETININGA - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 6000 where nome= 'SAO JOSE DO RIO PRETO - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 7000 where nome= 'SOROCABA - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 15 where nome= 'ANAPOLIS' and fk_uf=(select id from uf where uf='GO');
update cidade set CODIGO_CIDADE_DBM= 11 where nome= 'CAMPO GRANDE' and fk_uf=(select id from uf where uf='MS');
update cidade set CODIGO_CIDADE_DBM= 641 where nome= 'CASCAVEL' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 794 where nome= 'PONTA GROSSA' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 105 where nome= 'BELFORD ROXO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 688 where nome= 'BENTO GONCALVES' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 600 where nome= 'NOVO HAMBURGO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 880 where nome= 'PORTO ALEGRE' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 694 where nome= 'SANTA CRUZ DO SUL' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 88 where nome= 'FLORIANOPOLIS' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 404 where nome= 'ARACATUBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 52 where nome= 'CAMPINAS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 863 where nome= 'MOGI GUACU' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 76 where nome= 'RIO CLARO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 858 where nome= 'VARZEA GRANDE' and fk_uf=(select id from uf where uf='PI');
update cidade set CODIGO_CIDADE_DBM= 194 where nome= 'BELEn' and fk_uf=(select id from uf where uf='MA');
update cidade set CODIGO_CIDADE_DBM= 8700 where nome= 'LITORAL' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 521 where nome= 'SOBRAL' and fk_uf=(select id from uf where uf='CE');
update cidade set CODIGO_CIDADE_DBM= 4560 where nome= 'BERTIOGA - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 911 where nome= 'CACHOEIRO DE ITAPEMIRIM' and fk_uf=(select id from uf where uf='ES');
update cidade set CODIGO_CIDADE_DBM= 43 where nome= 'LAGOA SANTA' and fk_uf=(select id from uf where uf='GO');
update cidade set CODIGO_CIDADE_DBM= 1 where nome= 'TREINAMENTO' and fk_uf=(select id from uf where uf='TR');
update cidade set CODIGO_CIDADE_DBM= 18700 where nome= 'SAO VICENTE - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 65900 where nome= 'GUARUJA - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 4000 where nome= 'SANTOS - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 2700 where nome= 'PRAIA GRANDE - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 57300 where nome= 'CUBATAO - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 78 where nome= 'PORTO ALEGRE - CABO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 880 where nome= 'PORTO ALEGRE - MMDS' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 879 where nome= 'PORTO ALEGRE - MMDS 2' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 8800 where nome= 'PORTO ALEGRE - MMDS 3' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 686 where nome= 'NOVO HAMBURGO - CABO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 112 where nome= 'RIO VERDE' and fk_uf=(select id from uf where uf='GO');
update cidade set CODIGO_CIDADE_DBM= 160 where nome= 'VALPARAISO DE GOIAS' and fk_uf=(select id from uf where uf='GO');
update cidade set CODIGO_CIDADE_DBM= 763 where nome= 'TEOFILO OTONI' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 821 where nome= 'VARGINHA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 834 where nome= 'VESPASIANO' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 348 where nome= 'MAFRA' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 399 where nome= 'APARECIDA' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 847 where nome= 'CAMPINA GRANDE' and fk_uf=(select id from uf where uf='PB');
update cidade set CODIGO_CIDADE_DBM= 295 where nome= 'SALTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 22 where nome= 'PORTO FELIZ' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 595 where nome= 'ELIAS FAUSTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 399 where nome= 'APARECIDA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 488 where nome= 'CACHOEIRA PAULISTA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 30 where nome= 'NOVA FRIBURGO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 338 where nome= 'TERESOPOLIS' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 11 where nome= 'CAMPO GRANDE' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 398 where nome= 'TORRES' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 58 where nome= 'BIGUACU' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 739 where nome= 'ITATIBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 203 where nome= 'JARAGUA DO SUL' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 25 where nome= 'PRESIDENTE BERNARDES' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 419 where nome= 'ARTUR NOGUEIRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 442 where nome= 'BARRINHA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 448 where nome= 'BATATAIS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 464 where nome= 'BOITUVA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 10000 where nome= 'CAMPO LIMPO PAULISTA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 576 where nome= 'DESCALVADO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 431 where nome= 'MOCOCA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 506 where nome= 'FOZ DO IGUACU' and fk_uf=(select id from uf where uf='PR');
update cidade set CODIGO_CIDADE_DBM= 615 where nome= 'SAO JOAQUIM DA BARRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 587 where nome= 'SERRANA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 246 where nome= 'TREMEMBE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 261 where nome= 'UBATUBA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 279 where nome= 'VINHEDO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 948 where nome= 'LINS' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 850 where nome= 'MIRASSOL' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 869 where nome= 'MONGAGUA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 966 where nome= 'PEDREIRA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 972 where nome= 'PERUIBE' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 609 where nome= 'POA' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 108 where nome= 'SANTA CRUZ DO RIO PARDO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 390 where nome= 'ALEGRETE' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 394 where nome= 'CACHOEIRA DO SUL' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 817 where nome= 'GRAMADO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 950 where nome= 'MONTENEGRO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 293 where nome= 'OSORIO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 48000 where nome= 'MACEIO - PILOTO' and fk_uf=(select id from uf where uf='AL');
update cidade set CODIGO_CIDADE_DBM= 13600 where nome= 'RECIFE - PILOTO' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 22300 where nome= 'JABOATAO DOS GUARARAPES - PILOTO' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 29100 where nome= 'PAULISTA - PILOTO' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 26900 where nome= 'OLINDA - PILOTO' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 9500 where nome= 'NATAL - PILOTO' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 63700 where nome= 'PARNAMIRIM - PILOTO' and fk_uf=(select id from uf where uf='RN');
update cidade set CODIGO_CIDADE_DBM= 55000 where nome= 'ARACAJU - PILOTO' and fk_uf=(select id from uf where uf='SE');
update cidade set CODIGO_CIDADE_DBM= 260 where nome= 'NAVEGANTES' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 27 where nome= 'PRAIA GRANDE' and fk_uf=(select id from uf where uf='SC');
update cidade set CODIGO_CIDADE_DBM= 3 where nome= 'SAO PAULO PME' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 560 where nome= 'CACHOEIRINHA' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 832 where nome= 'DIVINOPOLIS' and fk_uf=(select id from uf where uf='TO');
update cidade set CODIGO_CIDADE_DBM= 239 where nome= 'MESQUITA' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 459 where nome= 'POUSO ALEGRE' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 871 where nome= 'VIAMAO' and fk_uf=(select id from uf where uf='RS');
update cidade set CODIGO_CIDADE_DBM= 999999 where nome= 'CIDADE HOMOLOGACAO' and fk_uf=(select id from uf where uf='TR');
update cidade set CODIGO_CIDADE_DBM= 285 where nome= 'RIO DAS OSTRAS' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 15200 where nome= 'CARUARU - PILOTO' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 209 where nome= 'SUZANO PME' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 38 where nome= 'RIO DE JANEIRO PME' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 13 where nome= 'BELO HORIZONTE PME' and fk_uf=(select id from uf where uf='MG');
update cidade set CODIGO_CIDADE_DBM= 81 where nome= 'CIDADES CODIGO 81' and fk_uf=(select id from uf where uf='PE');
update cidade set CODIGO_CIDADE_DBM= 282000 where nome= 'VOTORANTIM - PILOTO' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 52900 where nome= 'CAMPOS DOS GOYTACAZES - PILOTO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 19700 where nome= 'MACAE - PILOTO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 28500 where nome= 'RIO DAS OSTRAS - PILOTO' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 11000 where nome= 'CAMPO GRANDE - PILOTO' and fk_uf=(select id from uf where uf='MS');
update cidade set CODIGO_CIDADE_DBM= 116 where nome= 'BUZIOS' and fk_uf=(select id from uf where uf='RJ');
update cidade set CODIGO_CIDADE_DBM= 897 where nome= 'SANTOS ABC' and fk_uf=(select id from uf where uf='SP');
update cidade set CODIGO_CIDADE_DBM= 579 where nome= 'SERRA NEGRA ' and fk_uf=(select id from uf where uf='SP');
