-- FUNCIONALIDADE --
--------------------

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20000, 'Descredenciar Agente Autorizado Direto', 'POL_20000', 2);

-- PERMISSÕES --
----------------

-- ADMINISTRADOR XBRAIN

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20000);


-- ANALISTA DE SUPORTE XBRAIN (DEPARTAMENTO ADMINISTRADOR)

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 51, 50, 20000);

-- ANALISTA DE SUPORTE XBRAIN (DEPARTAMENTO HELPDESK)

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 51, 51, 20000);
