CREATE TABLE FERIADO_HISTORICO
    (
        ID              INTEGER NOT NULL,
        DATA_CADASTRO   TIMESTAMP NOT NULL,
        FK_USUARIO      INTEGER,
        FK_FERIADO      INTEGER,
        OBSERVACAO      VARCHAR(255),
        PRIMARY KEY (ID)
    );

ALTER TABLE FERIADO_HISTORICO ADD CONSTRAINT FK_FERIADO_HIST_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO;
ALTER TABLE FERIADO_HISTORICO ADD CONSTRAINT FK_FERIADO_HISTORICO_FERIADO FOREIGN KEY (FK_FERIADO) REFERENCES FERIADO;