DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID IN (8008, 8009);

    IF QTD = 0 THEN
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8008, 'Criar templates de comunicados', 'CMD_8008', 21);
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8009, 'Visualizar templates de comunicados', 'CMD_8009', 21);
    END IF;
END;