
ALTER TABLE CARGO ADD QUANTIDADE_SUPERIOR NUMBER(10, 0);
UPDATE CARGO SET QUANTIDADE_SUPERIOR = 50;
UPDATE CARGO SET QUANTIDADE_SUPERIOR = 1 WHERE ID = 8;

INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (8, 10);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (2, 4);
