---  COMERCIAL -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = 19000;
---  ADMINISTRATIVO -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 20 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 20 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 20 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 20 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 20 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 20 AND FK_FUNCIONALIDADE = 19000;
---  COMUNICAÇÃO -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 22 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 22 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 22 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 22 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 22 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 22 AND FK_FUNCIONALIDADE = 19000;
---  ENDOMARKETING -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 23 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 23 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 23 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 23 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 23 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 23 AND FK_FUNCIONALIDADE = 19000;
---  MARKETING -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 24 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 24 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 24 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 24 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 24 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 24 AND FK_FUNCIONALIDADE = 19000;
---  PLANEJAMENTO COMERCIAL -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 25 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 25 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 25 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 25 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 25 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 25 AND FK_FUNCIONALIDADE = 19000;
---  PROCESSOS COMERCIAL -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 26 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 26 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 26 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 26 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 26 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 26 AND FK_FUNCIONALIDADE = 19000;
---  PROJETOS -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 27 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 27 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 27 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 27 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 27 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 27 AND FK_FUNCIONALIDADE = 19000;
---  SUPORTE COMERCIAL -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 28 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 28 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 28 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 28 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 28 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 28 AND FK_FUNCIONALIDADE = 19000;
---  TRADE MARKETING -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 29 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 29 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 29 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 29 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 29 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 29 AND FK_FUNCIONALIDADE = 19000;
---  TREINAMENTO -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 30 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 30 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 30 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 30 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 30 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 30 AND FK_FUNCIONALIDADE = 19000;
---  FINANCEIRO -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 31 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 31 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 31 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 31 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 31 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 31 AND FK_FUNCIONALIDADE = 19000;
---  AUDITORIA -----
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 52 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 52 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 52 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 52 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 52 AND FK_FUNCIONALIDADE = 19000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 52 AND FK_FUNCIONALIDADE = 19000;
