-- CANAIS PARA OS CARGOS

-- Operador Televendas
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'ATP' FROM CARGO WHERE CODIGO = 'OPERACAO_TELEVENDAS';

-- Assistente Hunter
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'ATP' FROM CARGO WHERE CODIGO = 'ASSISTENTE_HUNTER';
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'D2D_PROPRIO' FROM CARGO WHERE CODIGO = 'ASSISTENTE_HUNTER';

-- Executivo Hunter
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'ATP' FROM CARGO WHERE CODIGO = 'EXECUTIVO_HUNTER';
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'D2D_PROPRIO' FROM CARGO WHERE CODIGO = 'EXECUTIVO_HUNTER';
