DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID IN (8006, 8007);

    IF QTD = 0 THEN
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8006, 'Criar solicitações de comunicados', 'CMD_8006', 21);
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8007, 'Atender solicitações de comunicados', 'CMD_8007', 21);
    END IF;
END;