-- NOVAS PERMISSÕES DASHBOARD -- RELATÓRIO DE VISITAS POR PERÍODO --

-- Assistente Operação - Comercial Operação
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 2, 3, 9009);
-- Coordernador Operação - Comercial Operação
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 9009);
