CREATE SEQUENCE SEQ_SITE START WITH 1 INCREMENT BY 1;

CREATE TABLE SITE (ID INTEGER NOT NULL,
                   NOME VARCHAR(100) NOT NULL,
                   SITUACAO VARCHAR(255) NOT NULL,
                   TIME_ZONE VARCHAR(25) NOT NULL,
                   PRIMARY KEY (ID));

CREATE TABLE SITE_CIDADE (FK_SITE INTEGER NOT NULL,
                          FK_CIDADE INTEGER NOT NULL,
                          PRIMARY KEY (FK_SITE, FK_CIDADE));

CREATE TABLE SITE_COORDENADOR (FK_SITE INTEGER NOT NULL,
                               FK_USUARIO INTEGER NOT NULL,
                              PRIMARY KEY (FK_SITE, FK_USUARIO));

CREATE TABLE SITE_SUPERVISOR (FK_SITE INTEGER NOT NULL,
                              FK_USUARIO INTEGER NOT NULL,
                              PRIMARY KEY (FK_SITE, FK_USUARIO));

ALTER TABLE SITE_CIDADE ADD CONSTRAINT FK_SITE_CIDADE_CIDADE
FOREIGN KEY (FK_CIDADE) REFERENCES CIDADE;

ALTER TABLE SITE_CIDADE ADD CONSTRAINT FK_SITE_CIDADE_SITE
FOREIGN KEY (FK_SITE) REFERENCES SITE;

ALTER TABLE SITE_COORDENADOR ADD CONSTRAINT FK_SITE_COORDENADOR_USU
FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO;

ALTER TABLE SITE_COORDENADOR ADD CONSTRAINT FK_SITE_COORDENADOR_SITE
FOREIGN KEY (FK_SITE) REFERENCES SITE;

ALTER TABLE SITE_SUPERVISOR ADD CONSTRAINT FK_SITE_SUPERVISOR_USU
FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO;

ALTER TABLE SITE_SUPERVISOR ADD CONSTRAINT FK_SITE_SUPERVISOR_SITE
FOREIGN KEY (FK_SITE) REFERENCES SITE;