-- REMOVE ROLE_AUT_2047 DO DIRETOR_OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 6 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 2047;

-- REMOVE ROLE_AUT_2047 DO GERENTE_OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 7 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 2047;