-- CRIA PERMISSAO GERENCIAR DESCRITIVO MAILING
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
    VALUES (SEQ_FUNCIONALIDADE.NEXTVAL, 'Gerenciar Descritivo de Mailing', 'CTR_GERENCIAR_DESCRITIVO_MAILING', (SELECT ID FROM APLICACAO WHERE NOME = 'CONTROLE'));

-- MSO COMERCIAL PERMISSAO GERENCIAR DESCRITIVO MAILING
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 2, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));