DECLARE
  QTD INT;
BEGIN
  SELECT COUNT(tname) INTO QTD FROM tab WHERE tname = 'CARGO_CANAL';

  IF QTD > 0 THEN
    INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'D2D_PROPRIO' FROM CARGO WHERE CODIGO = 'OPERACAO_EXECUTIVO_VENDAS';
  END IF;
END;