-- 5013 - Distribuir Agendamentos Proprietários

-- 10 - SUPERVISOR_OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 10, 3, 5013);

-- 4 - COORDENADOR_OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 4, 3, 5013);

-- 7 - GERENTE_OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 7, 3, 5013);