ALTER TABLE CARGO_DEPART_FUNC ADD CANAL VARCHAR2(255);

UPDATE CARGO_DEPART_FUNC
    SET CANAL = 'ATIVO_PROPRIO'
    WHERE FK_FUNCIONALIDADE = 2048;

UPDATE CARGO_DEPART_FUNC
    SET CANAL = 'D2D_PROPRIO'
    WHERE FK_FUNCIONALIDADE = 2037;