DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 16002;

    IF QTD = 0 THEN
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16002, 'VISUALIZAR TRATATIVAS (BACKOFFICE)', 'BKO_16002', 24);

        INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 114, 69, 16002);
        INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 113, 69, 16002);
        INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 112, 69, 16002);

        UPDATE FUNCIONALIDADE SET ROLE = 'BKO_16000' WHERE ID = 16000;
        UPDATE FUNCIONALIDADE SET ROLE = 'BKO_16001' WHERE ID = 16001;
    END IF;
END;