CREATE TABLE SITE_ESTADO (
    FK_SITE INTEGER NOT NULL,
    FK_ESTADO INTEGER NOT NULL,
    CONSTRAINT PK_SITE_ESTADO PRIMARY KEY (FK_SITE, FK_ESTADO),
    CONSTRAINT FK_SITE_ESTADO_SITE FOREIGN KEY (FK_SITE) REFERENCES SITE,
    CONSTRAINT FK_SITE_ESTADO_ESTADO FOREIGN KEY (FK_ESTADO) REFERENCES UF
);

CREATE INDEX CIDADE_IDX01 ON CIDADE(FK_UF);