-- CANAIS PARA OS CARGOS
-- Operador vendedor
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'D2D_PROPRIO' FROM CARGO WHERE CODIGO = 'VENDEDOR_OPERACAO';
-- Operador técnico
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'D2D_PROPRIO' FROM CARGO WHERE CODIGO = 'OPERACAO_TECNICO';