-- Adicionar a permissão do RESGATE DE GRAVAÇÕES para o canal D2D
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (3034, 'D2D_PROPRIO');

-- Adicionar a permissão do SELECIONAR_RAMAL_MODAL para supervisor e coordenador
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 4, 3, 3029);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 10, 3, 3029);