ALTER TABLE USUARIO ADD URL_LOJA_BASE VARCHAR2(200);
ALTER TABLE USUARIO ADD URL_LOJA_PROSPECT VARCHAR2(200);

ALTER TABLE USUARIO_AUD ADD URL_LOJA_BASE VARCHAR2(200);
ALTER TABLE USUARIO_AUD ADD URL_LOJA_PROSPECT VARCHAR2(200);
