INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 45, 40, 3005);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 45, 40, 3006);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 45, 40, 5005);

DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 45 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 8000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 45 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 15000;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 45 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 9008;