--Visualizar Acompanhamento de Venda
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 120, 3, 3007);

--Visualizar Dados Vendedor Próprio
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 120, 3, 2021);