INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES (3004, 'AGENTE_AUTORIZADO');
INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES (3005, 'AGENTE_AUTORIZADO');
INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES (3006, 'AGENTE_AUTORIZADO');
INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES (3004, 'D2D_PROPRIO');
INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES (3006, 'ATIVO_PROPRIO');