CREATE TABLE CARGO_CANAL (
    FK_CARGO NUMBER(10,0) NOT NULL,
    CANAL VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE CARGO_CANAL
ADD CONSTRAINT FK_CARGO_CANAL
FOREIGN KEY (FK_CARGO) REFERENCES CARGO(ID);
