-- Cargo Vendedor Executivo - Nivel Operacao --
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL, QUANTIDADE_SUPERIOR) VALUES (98, 'OPERACAO_EXECUTIVO_VENDAS', 'Executivo de Vendas', 'A', 1, 50);

INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (98, 10);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (98, 2);

-- Adicionar permissoes do VENDEDOR_OPERACAO para cargo OPERACAO_EXECUTIVO_VENDAS
BEGIN
    FOR PERM IN (
        SELECT
            FK_FUNCIONALIDADE,
        FROM
            CARGO_DEPART_FUNC
        WHERE
            FK_CARGO = 8
            AND FK_DEPARTAMENTO = 3
    )
    LOOP
        INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
            VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 98, 3, PERM.FK_FUNCIONALIDADE);
    END LOOP;
END;

-- Adicionar a permissão do CLICK_TO_CALL para cargo OPERACAO_EXECUTIVO_VENDAS
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 98, 3, 3006);

INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (3006, 'D2D_PROPRIO');