-- PERMISSÕES PARA GERENCIAR SCRIPTS DO MAILING --

-- FUNCIONALIDADE --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (5017, 'Gerenciar Scripts do Mailing', 'MLG_5017', 4);

-- PERMISSÕES --
-- MSO Consultor - Comercial
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 5017);
-- X-Brain Administrador
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 5017);
