INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
SELECT 2035, 'Distribuir Agendamentos', 'AUT_DISTRIBUIR_AGENDAMENTOS', 1
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM FUNCIONALIDADE
    WHERE (ID = 2035 AND ROLE = 'AUT_DISTRIBUIR_AGENDAMENTOS' AND FK_APLICACAO = 1));


INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 2035
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE (FK_CARGO = 50 AND FK_DEPARTAMENTO = 50 AND FK_FUNCIONALIDADE = 2035));