-- REMOVE PERMISSAO DESCRITIVO-MAILING
-- MSO ANALISTA
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 20 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');
-- MSO ASSISTENTE
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 21 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');
-- MSO CONSULTOR
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 22 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');
-- MSO GERENTE
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 24 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');
-- MSO DIRETOR
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 25 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');
-- MSO COORDENADOR
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 23 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');
-- MSO AUDITORIA
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 52 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');
-- ASSISTENTE OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 2 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING');

-- CRIA PERMISSAO PARA GERENCIAR FORNECEDORES
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (1063, 'Gerenciar Fornecedores de Mailing', 'CTR_GERENCIAR_FORNECEDORES_MAILING', 20);

-- XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 50, 50, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_FORNECEDORES_MAILING'));