DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID IN (8010, 8011, 8012, 8013);

    IF QTD = 0 THEN
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8010, 'Criar elementos newsletter', 'CMD_8010', 21);
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8011, 'Visualizar elementos newsletter', 'CMD_8011', 21);
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8012, 'Gerenciar newsletters', 'CMD_8012', 21);
        INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8013, 'Visualizar todos os newsletters', 'CMD_8013', 21);
    END IF;
END;