CREATE SEQUENCE AUTENTICACAO.SEQ_USUARIOS_DESLOGAR INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;
ALTER TABLE AUTENTICACAO.usuarios_para_deslogar ADD(id number(16) DEFAULT AUTENTICACAO.SEQ_USUARIOS_DESLOGAR.NEXTVAL NOT NULL);
ALTER TABLE AUTENTICACAO.usuarios_para_deslogar ADD(CONSTRAINT PK_USUARIOS_DESLOGAR PRIMARY KEY(ID));