-- FUNCIONALIDADE
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15007, 'Gerenciar Agente Autorizado Conversão e Punição', 'GRL_15007', 23);

-- CARGO_DEPART_FUNC: ADMINISTRADOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 15007);
-- CARGO_DEPART_FUNC: CONSULTOR MSO COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 15007);
