-- FUNCIONALIDADE: MLG_5018 - Gerenciar Distribuição Mailing Segmentação
-- CARGO_DEPART_FUNC: ASSISTENTE COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 2, 3, 5018);