-- MSO ANALISTA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 20, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
-- MSO ASSISTENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 21, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
-- MSO CONSULTOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 22, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
-- MSO GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 24, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
-- MSO DIRETOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 25, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
-- MSO COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 23, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
-- MSO AUDITORIA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 52, 21, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
-- XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 50, 50, (SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'CTR_GERENCIAR_DESCRITIVO_MAILING'));
