INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 3007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 5004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 5004);