-- Permissão: MLG_VISUALIZAR_IMP_MAILING

-- OPERACAO | ASSISTENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 2, 3, 5001, 'ATIVO_PROPRIO');
-- OPERACAO | COORDENADOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 4, 3, 5001, 'ATIVO_PROPRIO');
-- OPERACAO | DIRETOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 6, 3, 5001, 'ATIVO_PROPRIO');
-- OPERACAO | GERENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 7, 3, 5001, 'ATIVO_PROPRIO');
-- OPERACAO | SUPERVISOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 10, 3, 5001, 'ATIVO_PROPRIO');

-- Permissão: MLG_VISUALIZAR_TIPOS_MAILING

-- OPERACAO | ASSISTENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 2, 3, 5004, 'ATIVO_PROPRIO');
-- OPERACAO | COORDENADOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 4, 3, 5004, 'ATIVO_PROPRIO');
-- OPERACAO | DIRETOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 6, 3, 5004, 'ATIVO_PROPRIO');
-- OPERACAO | GERENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 7, 3, 5004, 'ATIVO_PROPRIO');
-- OPERACAO | SUPERVISOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 10, 3, 5004, 'ATIVO_PROPRIO');

-- Permissão: MLG_ACOMPANHAR_MAILING

-- OPERACAO | ASSISTENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 2, 3, 5005, 'ATIVO_PROPRIO');
-- OPERACAO | COORDENADOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 4, 3, 5005, 'ATIVO_PROPRIO');
-- OPERACAO | DIRETOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 6, 3, 5005, 'ATIVO_PROPRIO');
-- OPERACAO | GERENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 7, 3, 5005, 'ATIVO_PROPRIO');
-- OPERACAO | SUPERVISOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 10, 3, 5005, 'ATIVO_PROPRIO');

-- Permissão: MLG_5006

-- OPERACAO | ASSISTENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 2, 3, 5006, 'ATIVO_PROPRIO');
-- OPERACAO | COORDENADOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 4, 3, 5006, 'ATIVO_PROPRIO');
-- OPERACAO | DIRETOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 6, 3, 5006, 'ATIVO_PROPRIO');
-- OPERACAO | GERENTE_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 7, 3, 5006, 'ATIVO_PROPRIO');
-- OPERACAO | SUPERVISOR_OPERACAO | COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 10, 3, 5006, 'ATIVO_PROPRIO');