INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 16002);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 5006);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 5004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 3016);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 10008);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 10002);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 3, 7, 3018);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 16002);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 5006);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 5004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 3016);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 10008);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 10002);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 7, 3018);

INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (3, 4);
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR) VALUES (1, 4);
