ALTER TABLE FERIADO ADD (
    TIPO_FERIADO VARCHAR(255),
    FK_UF INTEGER,
    FK_FERIADO_PAI INTEGER
);

ALTER TABLE FERIADO ADD CONSTRAINT FK_FERIADO_UF FOREIGN KEY (FK_UF) REFERENCES UF;
ALTER TABLE FERIADO ADD CONSTRAINT FK_FERIADO_FERIADO_PAI FOREIGN KEY (FK_FERIADO_PAI) REFERENCES FERIADO;