UPDATE FERIADO SET TIPO_FERIADO = 'NACIONAL' WHERE FERIADO_NACIONAL = 'V';
UPDATE FERIADO SET TIPO_FERIADO = 'MUNICIPAL' WHERE FERIADO_NACIONAL = 'F' AND FK_CIDADE IS NOT NULL;

UPDATE FERIADO F SET F.FK_UF = (SELECT UF.ID
                                  FROM CIDADE C
                                  JOIN UF UF ON C.FK_UF = UF.ID
                                  WHERE F.FK_CIDADE = C.ID) WHERE F.FK_CIDADE IS NOT NULL;