ALTER TABLE USUARIO ADD TIPO_CANAL VARCHAR2(50);
ALTER TABLE USUARIO_AUD ADD TIPO_CANAL VARCHAR2(50);

ALTER TABLE USUARIO ADD CONSTRAINT TIPO_CANAL_VALUES CHECK (TIPO_CANAL IN (
    'PAP',
    'PAP_PREMIUM',
    'INSIDE_SALES_PME'
));
