-- PERMISSÃO PARA GERENCIAR CONFIGURAÇÕES DE PRODUTO - NÍVEL XBRAIN --

-- FUNCIONALIDADE
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (7006, 'Gerenciar Configurações de Produto', 'INT_GERENCIA_CONFIG_PRODUTO', 8);

-- PERMISSÕES
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 7006);