-- FUNCIONALIDADE --
--------------------

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15011, 'Gerenciar Layout de Carga de Leads', 'FDR_15011', 23);

-- PERMISSÕES --
----------------

-- ADMINISTRADOR XBRAIN (DEPARTAMENTO ADMINISTRADOR)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 15011);

-- MSO CONSULTOR (DEPARTAMENTO COMERCIAL)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 15011);