INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2053, 'Visualizar Tentativas na Super Abordagem', 'CTR_VISUALIZAR_TENT_SUPERABOR', 20);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,50, 3,  2053, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,50, 50, 2053, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,50, 51, 2053, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,51, 50, 2053, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,51, 51, 2053, 110827);