-- ADICIONA FUNCIONALIDADE 'GERENCIAR LEAD' PARA OS CARGOS DE DIRETOR, EXECUTIVO, GERENTE E COORDENADOR DO DEPARTAMENTO COMERCIAL
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_FUNC.nextval, 4, 3, 15000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_FUNC.nextval, 5, 3, 15000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_FUNC.nextval, 6, 3, 15000);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_FUNC.nextval, 7, 3, 15000);

-- ADICIONA FUNCIONALIDADE 'GERENCIAR LEAD' PARA O CANAL 'AGENTE AUTORIZADO'
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (15000, 'AGENTE_AUTORIZADO');
