CREATE SEQUENCE SEQ_ORGANIZACAO START WITH 1 INCREMENT BY 1;
CREATE TABLE ORGANIZACAO (ID INTEGER NOT NULL, CODIGO VARCHAR(80) NOT NULL, NOME VARCHAR(80) NOT NULL, PRIMARY KEY (ID));
ALTER TABLE ORGANIZACAO ADD CONSTRAINT UK_ORGANIZACAO_CODIGO UNIQUE (CODIGO);

ALTER TABLE USUARIO ADD FK_ORGANIZACAO INTEGER;
ALTER TABLE USUARIO_AUD ADD FK_ORGANIZACAO INTEGER;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_ORGANIZACAO FOREIGN KEY (FK_ORGANIZACAO) REFERENCES ORGANIZACAO;

INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'BCC', 'Brasil Center');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'CALLINK', 'Callink');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'PROPRIO', 'Próprio');
INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (SEQ_ORGANIZACAO.NEXTVAL, 'ATENTO', 'Atento');

-- BRASIL CENTER
UPDATE USUARIO
SET FK_CARGO =
  (SELECT ID FROM cargo WHERE CODIGO = 'SUPERVISOR_RECEPTIVO'
  ),
  FK_ORGANIZACAO =
  (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'BCC'
  )
WHERE ID IN
  (SELECT ID
  FROM USUARIO
  WHERE UPPER(EMAIL_01) LIKE '%@BRASILCENTER.COM.BR'
  AND SITUACAO = 'A'
  AND fk_cargo =
    (SELECT id FROM cargo WHERE codigo = 'SUPERVISOR_RECEPTIVO_SEGMENTADO'
    )
  );

UPDATE USUARIO
SET FK_CARGO =
  (SELECT ID FROM cargo WHERE CODIGO = 'VENDEDOR_RECEPTIVO'
  ),
  FK_ORGANIZACAO =
  (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'BCC'
  )
WHERE ID IN
  (SELECT ID
  FROM USUARIO
  WHERE UPPER(EMAIL_01) LIKE '%@BRASILCENTER.COM.BR'
  AND SITUACAO = 'A'
  AND fk_cargo =
    (SELECT id FROM cargo WHERE codigo = 'VENDEDOR_RECEPTIVO_SEGMENTADO'
    )
  );


-- CALLINK
UPDATE USUARIO
SET FK_CARGO =
  (SELECT ID FROM cargo WHERE CODIGO = 'SUPERVISOR_RECEPTIVO'
  ),
   FK_ORGANIZACAO =
  (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'CALLINK'
  )
WHERE ID IN
  (SELECT ID
  FROM USUARIO
  WHERE UPPER(EMAIL_01) LIKE '%@CALLINK%'
  AND SITUACAO = 'A'
  AND fk_cargo =
    (SELECT id FROM cargo WHERE codigo = 'SUPERVISOR_RECEPTIVO_SEGMENTADO'
    )
  );

UPDATE USUARIO
SET FK_CARGO =
  (SELECT ID FROM cargo WHERE CODIGO = 'VENDEDOR_RECEPTIVO'
  ),
   FK_ORGANIZACAO =
  (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'CALLINK'
  )
WHERE ID IN
  (SELECT ID
  FROM USUARIO
  WHERE UPPER(EMAIL_01) LIKE '%@CALLINK%'
  AND SITUACAO = 'A'
  AND fk_cargo =
    (SELECT id FROM cargo WHERE codigo = 'VENDEDOR_RECEPTIVO_SEGMENTADO'
    )
  );


-- NET / CLARO
UPDATE USUARIO
SET FK_CARGO =
  (SELECT ID FROM cargo WHERE CODIGO = 'SUPERVISOR_RECEPTIVO'
  ),
   FK_ORGANIZACAO =
  (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'PROPRIO'
  )
WHERE ID IN
  (SELECT ID
  FROM USUARIO
  WHERE (UPPER(EMAIL_01) LIKE '%@NET.COM.BR'
  OR UPPER(EMAIL_01) LIKE '%@CLARO.COM.BR')
  AND SITUACAO = 'A'
  AND fk_cargo =
    (SELECT id FROM cargo WHERE codigo = 'SUPERVISOR_RECEPTIVO_SEGMENTADO'
    )
  );

UPDATE USUARIO
SET FK_CARGO =
  (SELECT ID FROM cargo WHERE CODIGO = 'VENDEDOR_RECEPTIVO'
  ),
   FK_ORGANIZACAO =
  (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'PROPRIO'
  )
WHERE ID IN
  (SELECT ID
  FROM USUARIO
  WHERE (UPPER(EMAIL_01) LIKE '%@NET.COM.BR'
  OR UPPER(EMAIL_01) LIKE '%@CLARO.COM.BR')
  AND SITUACAO = 'A'
  AND fk_cargo =
    (SELECT id FROM cargo WHERE codigo = 'VENDEDOR_RECEPTIVO_SEGMENTADO'
    )
  );


-- NET / CLARO
UPDATE USUARIO
SET FK_ORGANIZACAO =
(SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'PROPRIO'
)
WHERE ID IN
(SELECT ID
FROM USUARIO
WHERE FK_CARGO IN (SELECT id FROM cargo WHERE codigo IN ('VENDEDOR_RECEPTIVO', 'SUPERVISOR_RECEPTIVO'))
  AND (UPPER(EMAIL_01) LIKE UPPER('%@NET.COM.BR') OR UPPER(EMAIL_01) LIKE UPPER('%@CLARO.COM.BR'))
  AND FK_ORGANIZACAO IS NULL
  AND SITUACAO = 'A');


--- CALLINK
UPDATE USUARIO
SET FK_ORGANIZACAO =
(SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'CALLINK'
)
WHERE ID IN
(SELECT ID
FROM USUARIO
WHERE FK_CARGO IN (SELECT id FROM cargo WHERE codigo IN ('VENDEDOR_RECEPTIVO', 'SUPERVISOR_RECEPTIVO'))
  AND UPPER(EMAIL_01) LIKE UPPER('%@CALLINK%')
  AND FK_ORGANIZACAO IS NULL
  AND SITUACAO = 'A');


-- BRASILCENTER
UPDATE USUARIO
SET FK_ORGANIZACAO =
(SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'BCC'
)
WHERE ID IN
(SELECT ID
FROM USUARIO
WHERE FK_CARGO IN (SELECT id FROM cargo WHERE codigo IN ('VENDEDOR_RECEPTIVO', 'SUPERVISOR_RECEPTIVO'))
  AND UPPER(EMAIL_01) LIKE UPPER('%@BRASILCENTER.COM.BR')
  AND FK_ORGANIZACAO IS NULL
  AND SITUACAO = 'A');