-- CRIA PERMISSAO PARA VIZUALIZACAO DE FILTROS E LISTAGEM DE EMAIL
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2056, 'Visualizar Funcionalidade de Listagem de Email', 'CTR_2056', 20);

--XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL,SYSDATE,50,50,2056)
