-- REMOVE FUNCIONALIDADES NAO UTILIZADAS
-- 226 Gerenciar Usuários Executivos
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 226;
DELETE FROM FUNCIONALIDADE WHERE ID = 226;

-- 2004 Visualizar Empresa/Unidade de Negócio
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 2004;
DELETE FROM FUNCIONALIDADE WHERE ID = 2004;

-- 2006 Visualizar Usuários por Cidades
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 2006;
DELETE FROM FUNCIONALIDADE WHERE ID = 2006;

-- REMOVE E ADICIONA A PERMISSAO Visualizar Carteira/Hierarquia PARA OS CARGOS CORRETOS
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 2005;

-- 2 ASSISTENTE_OPERACAO
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 1, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 2, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 3, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 4, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 5, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 6, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 7, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 8, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 9, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 10, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 11, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 12, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 52, 2005, 1);

-- Coordenador Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 1, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 2, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 3, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 4, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 5, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 6, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 7, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 8, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 9, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 10, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 11, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 12, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 52, 2005, 1);
-- Diretor Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 1, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 2, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 3, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 4, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 5, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 6, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 7, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 8, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 9, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 10, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 11, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 12, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 52, 2005, 1);
-- Gerente Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 1, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 2, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 3, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 4, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 5, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 6, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 7, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 8, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 9, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 10, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 11, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 12, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 52, 2005, 1);
-- Supervisor Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 1, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 2, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 3, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 4, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 5, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 6, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 7, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 8, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 9, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 10, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 11, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 12, 2005, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 52, 2005, 1);


-- REMOVE E ADICIONA A PERMISSAO Visualizar Usuários PARA OS CARGOS CORRETOS
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 2001 AND FK_CARGO IN (2, 4, 6, 7, 10);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 1, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 2, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 3, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 4, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 5, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 6, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 7, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 8, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 9, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 10, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 11, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 12, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 52, 2001, 1);

-- Coordenador Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 1, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 2, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 3, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 4, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 5, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 6, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 7, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 8, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 9, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 10, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 11, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 12, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 52, 2001, 1);
-- Diretor Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 1, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 2, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 3, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 4, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 5, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 6, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 7, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 8, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 9, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 10, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 11, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 12, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 52, 2001, 1);
-- Gerente Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 1, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 2, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 3, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 4, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 5, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 6, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 7, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 8, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 9, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 10, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 11, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 12, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 52, 2001, 1);
-- Supervisor Operação
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 1, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 2, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 3, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 4, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 5, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 6, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 7, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 8, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 9, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 10, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 11, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 12, 2001, 1);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 52, 2001, 1);
