-- Criar usuário motiva --
INSERT INTO USUARIO
    (
        ID,
        ALTERAR_SENHA,
        DATA_CADASTRO,
        EMAIL_01,
        NASCIMENTO,
        NOME,
        SENHA,
        SITUACAO,
        FK_CARGO,
        FK_DEPARTAMENTO,
        RECUPERAR_SENHA_TENTATIVA
    )
    VALUES
    (
        SEQ_USUARIO.NEXTVAL,
        'F',
        CURRENT_DATE,
        'INTEGRACAOMOTIVA@XBRAIN.COM.BR',
        CURRENT_DATE,
        'INTEGRAÇÃO MOTIVA',
        '$2a$10$t6Khqh8NUQwp2vfwiGuw4.6PSCfKXSmQWpe9tOY4yTbqd.TTSQxTi',
        'A',
        (SELECT ID FROM CARGO WHERE CODIGO = 'INTEGRACAO'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'INTEGRACAO'),
        0
    );

INSERT INTO USUARIO_UNIDADE_NEGOCIO (FK_USUARIO, FK_UNIDADE_NEGOCIO)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOMOTIVA@XBRAIN.COM.BR'), 3);

INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOMOTIVA@XBRAIN.COM.BR'), 4);

-- Criar funcionalidade --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (7007, 'Resgatar tratativas para motiva', 'INT_7007', 8);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 7007);

-- Adicionar permissão especial para o usuário motiva --
INSERT INTO PERMISSAO_ESPECIAL
    (
        ID,
        DATA_CADASTRO,
        FK_FUNCIONALIDADE,
        FK_USUARIO,
        FK_USUARIO_CADASTRO
    )
VALUES
    (
        SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        7007,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOMOTIVA@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'FAGNERONESKO@XBRAIN.COM.BR')
    );
