INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15012, ' Descartar Lead', 'FDR_15012', 23);

-- Nível: MSO | Departamento: Comercial | Cargo: Consultor --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 15012);

BEGIN
    FOR AA_ESPECIAL IN (
        SELECT
            FK_USUARIO
        FROM
            PERMISSAO_ESPECIAL
        WHERE
            FK_FUNCIONALIDADE = 15005
            AND FK_USUARIO IN (
                SELECT ID FROM USUARIO WHERE FK_CARGO IN (
                  SELECT ID FROM CARGO WHERE FK_NIVEL = 3
                )
            )
    )
    LOOP
        INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
        VALUES (SEQ_PERMISSAO_ESPECIAL.nextval, CURRENT_DATE, 15012, AA_ESPECIAL.FK_USUARIO, 1);
    END LOOP;
END;