-- FUNCIONALIDADE --
--------------------

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (2055, 'Importar Planilha Direcionamento PAP Premium', 'CTR_2055', 20);

-- PERMISSÕES --
----------------

-- ADMINISTRADOR XBRAIN (DEPARTAMENTO ADMINISTRADOR)

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 2055);