-- REMOVE TRABALHAR MAILING DO GERENTE
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 7 AND FK_DEPARTAMENTO = 3 and FK_FUNCIONALIDADE = 3008;

-- TRATA PERMISSOES DE DISCADORA E CLICK TO CALL P#ARA SER SOMENTE AGENDA AUTORIZADO
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (3005, 'AGENTE_AUTORIZADO');
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (3006, 'AGENTE_AUTORIZADO');
