-- PERMISSÃO PARCEIROS
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (239, 'Gerenciar Funil de Prospecções e Lista de Ocorrências', 'POL_239', 2);

-- NÍVEL DE OPERAÇÃO | DEPARTAMENTO COMERCIAL
-- 1 - EXECUTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 5, 3, 239, 138133);
-- 2 - COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 4, 3, 239, 138133);
-- 3 - GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 7, 3, 239, 138133);

-- NÍVEL DE MSO | DEPARTAMENTO COMERCIAL
-- MSO_ANALISTA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 20, 21, 239, 138133);
-- MSO_ASSISTENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 21, 21, 239, 138133);
-- MSO_CONSULTOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 22, 21, 239, 138133);
-- MSO_COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 23, 21, 239, 138133);
-- MSO_GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 24, 21, 239, 138133);
-- MSO_DIRETOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 25, 21, 239, 138133);
-- MSO_AUDITORIA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 52, 21, 239, 138133);

-- NÍVEL ADMINISTRADOR: XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 50, 50, 239, 138133);
