-- ADICIONA PERMISSAO DE GERENCIAR EQUIPE AO SUPERVISOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 10, 3, 2037, 1);
