INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
SELECT 5012, 'Discadora Alternativa', 'MLG_5012', 4
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM FUNCIONALIDADE
    WHERE (ID = 5012 AND ROLE = 'MLG_5012' AND FK_APLICACAO = 4));


INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 5012, 130821
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE (FK_CARGO = 50 AND FK_DEPARTAMENTO = 50 AND FK_FUNCIONALIDADE = 5012));