-- COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 45, 40, 2035, 130821, SYSDATE);

-- GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 47, 40, 2035, 130821, SYSDATE);
-- GERENTE RECEPTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 91, 40, 2035, 130821, SYSDATE);
-- GERENTE TMP
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 82, 40, 2035, 130821, SYSDATE);

-- SUPERVISOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 48, 40, 2035, 130821, SYSDATE);
-- SUPERVISOR RECEPTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 90, 40, 2035, 130821, SYSDATE);
-- SUPERVISOR TMP
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 81, 40, 2035, 130821, SYSDATE);

-- SOCIO PRINCIPAL
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 41, 40, 2035, 130821, SYSDATE);
-- SOCIO SECUNDARIO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 42, 40, 2035, 130821, SYSDATE);