CREATE SEQUENCE SEQ_USUARIO_ACESSO START WITH 1 INCREMENT BY 1;

CREATE TABLE USUARIO_ACESSO (
    ID INTEGER NOT NULL,
    DATA_CADASTRO TIMESTAMP,
    FK_USUARIO INTEGER,
    PRIMARY KEY (ID)
);

ALTER TABLE USUARIO_ACESSO ADD CONSTRAINT FK_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO;

ALTER TABLE USUARIO ADD DATA_ULTIMO_ACESSO TIMESTAMP;

UPDATE USUARIO SET DATA_ULTIMO_ACESSO = SYSDATE WHERE ID IN (
  SELECT ID FROM USUARIO WHERE SITUACAO = 'A'
);