INSERT INTO APLICACAO (ID, NOME, CODIGO) VALUES (15, 'CHAMADO', 'CHM');

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (14000, 'Abrir chamado', 'CHM_ABRIR_CHAMADO', 15);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (14001, 'Tratar chamado suporte', 'CHM_TRATAR_CHAMADO_SUPORTE', 15);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (14002, 'Tratar chamado processo', 'CHM_TRATAR_CHAMADO_PROCESSO', 15);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (14003, 'Tratar todos os chamados', 'CHM_TRATAR_CHAMADO_GERAL', 15);

-- ABRIR CHAMADO --
-- CARGO SOCIO AA
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 41, 40, 14000);
-- CARGO SOCIO SECUNDARIO AA
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 42, 40, 14000);
-- CARGO GERENTE AA
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 47, 40, 14000);
-- CARGO SUPERVISOR AA
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 48, 40, 14000);

-- TRATAR CHAMADO SUPORTE --
-- CARGO HELPDESK
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 51, 51, 14001);
-- CARGO HELPDESK (DEPARTAMENTO ADMIN)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 51, 50, 14001);

-- TRATAR CHAMADO PROCESSO --
-- CARGO EXECUTIVO (DEPARTAMENTO COMERCIAL [NIVEL=OPERACAO])
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 5, 3, 14002);

-- TRATAR TODOS OS CHAMADOS --
-- CARGO ADMIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 14003);