CREATE TABLE USUARIO_FERIAS (ID INTEGER NOT NULL, FK_USUARIO INTEGER NOT NULL, DATA_CADASTRO TIMESTAMP NOT NULL, INICIO TIMESTAMP NOT NULL, FIM TIMESTAMP NOT NULL,  PRIMARY KEY (id));

CREATE SEQUENCE SEQ_USUARIO_FERIAS START WITH 1 INCREMENT BY 1;

ALTER TABLE USUARIO_FERIAS ADD CONSTRAINT FK_USUARIO_FERIAS_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO;

ALTER TABLE USUARIO_HISTORICO ADD FK_USUARIO_FERIAS INTEGER;

ALTER TABLE USUARIO_HISTORICO ADD CONSTRAINT FK_USUARIO_FERIAS_USU_HIS FOREIGN KEY (FK_USUARIO_FERIAS) REFERENCES USUARIO_FERIAS;