INSERT INTO APLICACAO (ID, NOME, CODIGO) VALUES (14, 'CONTATO CRN', 'CRN');

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (13000, 'Abrir chamado CRN', 'CRN_ABRIR_CHAMADO', 14);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (13001, 'Gerenciar chamado CRN', 'CRN_GERENCIAR_CHAMADO', 14);

-- CARGO VENDEDOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 8, 3, 13000);
-- CARGO ADMIN --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 13001);
-- CARGO OUVIDORIA --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 86, 66, 13001);