INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (9008, 'Mix de Produtos - Por Vendedor', 'DSH_9008', 10);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE ,DATA_CADASTRO ,FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 9008 ,SYSDATE,
(SELECT ID FROM USUARIO WHERE EMAIL_01 LIKE 'GABRIELMENDES@XBRAIN.COM.BR')
);