INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (501, 'Importar Funil de Prospecções', 'FPC_IMPORTAR_FUNIL_PROSPECCAO', 16);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 50, 50, 501);
