INSERT INTO APLICACAO (ID, CODIGO, NOME) VALUES (20, 'CTR', 'CONTROLE');

-- CTR
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_VISUALIZAR_CARTEIRA_HIERARQUIA' WHERE ID = 2005;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_VISUALIZAR_DISCADORA' WHERE ID = 2007;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_VISUALIZAR_DIS_AA' WHERE ID = 2008;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_VISUALIZAR_RAMAL' WHERE ID = 2009;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_VISUALIZAR_RAMAL_USUARIO' WHERE ID = 2015;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_GERENCIAR_TEL_LEI_NAO_PERTURBE' WHERE ID = 2020;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_VISUALIZAR_MOTIVO_TELEFONIA' WHERE ID = 2019;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_2034' WHERE ID = 2034;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_2033' WHERE ID = 2033;
UPDATE FUNCIONALIDADE SET FK_APLICACAO = 20, ROLE = 'CTR_2038' WHERE ID = 2038;
