-- REMOVE A PERMISSÃO ANTIGA
DELETE FROM CARGO_DEPART_FUNC
WHERE FK_FUNCIONALIDADE = 2035;

DELETE FROM FUNCIONALIDADE WHERE ID = 2035;

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
SELECT 5013, 'Distribuir Agendamentos Proprietários', 'MLG_5013', 4
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM FUNCIONALIDADE
    WHERE (ID = 5013 AND ROLE = 'MLG_5013' AND FK_APLICACAO = 4));

INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL)
SELECT 5013, 'AGENTE_AUTORIZADO'
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM FUNCIONALIDADE_CANAL
    WHERE FK_FUNCIONALIDADE = 5013 AND CANAL = 'AGENTE_AUTORIZADO');


-- XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 5013, 130821, SYSDATE);

-- COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 45, 40, 5013, 130821, SYSDATE);

-- GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 47, 40, 5013, 130821, SYSDATE);
-- GERENTE RECEPTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 91, 40, 5013, 130821, SYSDATE);
-- GERENTE TMP
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 82, 40, 5013, 130821, SYSDATE);

-- SOCIO PRINCIPAL
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 41, 40, 5013, 130821, SYSDATE);
-- SOCIO SECUNDARIO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 42, 40, 5013, 130821, SYSDATE);