-- ADICIONA PERMISSAO DISTRIBUIR AGENDAMENTOS PARA SUPERVISORES

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 48, 3, 5013, 130821, SYSDATE
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE FK_FUNCIONALIDADE = 5013 AND FK_CARGO = 48 AND FK_DEPARTAMENTO = 3);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 81, 3, 5013, 130821, SYSDATE
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE FK_FUNCIONALIDADE = 5013 AND FK_CARGO = 81 AND FK_DEPARTAMENTO = 3);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 90, 3, 5013, 130821, SYSDATE
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE FK_FUNCIONALIDADE = 5013 AND FK_CARGO = 90 AND FK_DEPARTAMENTO = 3);