INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, DATA_CADASTRO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 5013, 130821, SYSDATE
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE FK_FUNCIONALIDADE = 5013 AND FK_CARGO = 4 AND FK_DEPARTAMENTO = 3);