-- NOVA PERMISSÃO PARCEIROS ONLINE --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (14005, 'Remover Contrato Agente Autorizado', 'POL_REMOVER_CONTRATO_AA', 2);
-- ADICIONA PARA USUÁRIOS ADMINISTRADORES
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 14005);