-- Brasília
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '30-NOV-2019', 'F', 'Dia do Evangélico', 805);
-- Campo Grande
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '11-OCT-2019', 'F', 'Aniversário do Mato Grosso do Sul', 2247);
-- Dourados
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '11-OCT-2019', 'F', 'Aniversário do Mato Grosso do Sul', 2259);
-- Aparecida de Goiânia
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '28-OCT-2019', 'F', 'Dia do Servidor Público', 929);
-- Goiânia
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '28-OCT-2019', 'F', 'Dia do Servidor Público', 1005);
-- Anápolis
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '28-OCT-2019', 'F', 'Dia do Servidor Público', 926);
-- Palmas
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '05-OCT-2019', 'F', 'Aniversário de Tocantins', 5509);
-- Palmas
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '28-OCT-2019', 'F', 'Dia do Servidor Público', 5509);
-- Rio Branco
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '05-SEP-2019', 'F', 'Dia da Amazônia', 16);
-- Maceió
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '16-SEP-2019', 'F', 'Emancipação de Alagoas', 69);
-- Teresina
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '19-OCT-2019', 'F', 'Dia do Piauí', 3211);
-- Natal
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '09-OCT-2019', 'F', 'Feriado Desconhecido (especificado na planilha)', 3791);
-- Parnamirim
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '09-OCT-2019', 'F', 'Feriado (especificado na planilha)', 3800);
-- Manaus
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '05-SEP-2019', 'F', 'Dia da Amazônia', 163);
-- Ananindeua
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '26-OCT-2019', 'F', 'Feriado Desconhecido (especificado na planilha)', 2456);
-- Belém
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '26-OCT-2019', 'F', 'Feriado Desconhecido (especificado na planilha)', 2465);
-- Campos Dos Goytacazes
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3626);
-- Campos Dos Goytacazes
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3626);
-- Rio de Janeiro
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3679);
-- Rio de Janeiro
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3679);
-- Belford Roxo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3620);
-- Belford Roxo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3620);
-- Duque de Caxias
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3636);
-- Duque de Caxias
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3636);
-- Mesquita
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3654);
-- Mesquita
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3654);
-- Nilópolis
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3658);
-- Nilópolis
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3658);
-- Nova Iguacu
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3661);
-- Nova Iguacu
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3661);
-- São João de Meriti
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3686);
-- São João de Meriti
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3686);
-- Niterói
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3659);
-- Niterói
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3659);
-- São Gonçalo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3684);
-- São Gonçalo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3684);
-- Macaé
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3648);
-- Macaé
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3648);
-- Rio das Ostras
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3678);
-- Rio das Ostras
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3678);
-- Nova Friburgo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3660);
-- Nova Friburgo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3660);
-- Petrópolis
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3666);
-- Petrópolis
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3666);
-- Teresópolis
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3697);
-- Teresópolis
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3697);
-- Barra Mansa
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3619);
-- Barra Mansa
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3619);
-- Resende
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3674);
-- Resende
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3674);
-- Volta Redonda
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3703);
-- Volta Redonda
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3703);
-- Armacao Dos Buzios
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3616);
-- Armacao Dos Buzios
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3616);
-- Arraial Do Cabo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3617);
-- Arraial Do Cabo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3617);
-- Cabo Frio
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3623);
-- Cabo Frio
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3623);
-- Sao Pedro Da Aldeia
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '15-OCT-2019', 'F', 'Dia do Professor', 3689);
-- Sao Pedro Da Aldeia
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-NOV-2019', 'F', 'Dia da Consciência Negra', 3689);
-- Alvorada
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 3950);
-- Cachoeirinha
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 3999);
-- Campo Bom
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4009);
-- Canoas
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4017);
-- Estância Velha
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4093);
-- Esteio
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4094);
-- Gravataí
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4122);
-- Guaiba
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4124);
-- Litoral
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4020);
-- Montenegro
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4194);
-- Novo Hamburgo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4223);
-- Porto Alegre
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4260);
-- São Leopoldo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4333);
-- Sapiranga
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4353);
-- Sapucaia do Sul
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4354);
-- Torres
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4386);
-- Viamão
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4419);
-- Xangri-La
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4431);
-- Cachoeira Do Sul
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 3998);
-- Lajeado
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4167);
-- Santa Cruz Do Sul
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4298);
-- Bento Gonçalves
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 3981);
-- Caxias do Sul
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4033);
-- Farroupilha
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4099);
-- Carazinho
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4027);
-- Erechim
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4085);
-- Passo Fundo
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4240);
-- Pelotas
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4246);
-- Rio Grande
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4278);
-- Bagé
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 3968);
-- Cruz Alta
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4062);
-- Santa Maria
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4300);
-- Uruguaiana
INSERT INTO AUTENTICACAO.FERIADO (ID, DATA_CADASTRO, DATA_FERIADO, FERIADO_NACIONAL, NOME, FK_CIDADE) VALUES (SEQ_FERIADO.NEXTVAL, SYSDATE, '20-SEP-2019', 'F', 'Proc. República Rio Grandense', 4408);
