INSERT INTO FUNCIONALIDADE VALUES (650, 'Acesso ao Módulo de Controle', 'CTR_ACESSO_APLICACAO', 20, null);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 86, 66, 650, 1654839);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 8, 3, 650, 1654839);