INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
SELECT 5014, 'Click to Call Alternativo', 'MLG_5014', 4
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM FUNCIONALIDADE
    WHERE (ID = 5014 AND ROLE = 'MLG_5014' AND FK_APLICACAO = 4));


INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 5014, 130821
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE (FK_CARGO = 50 AND FK_DEPARTAMENTO = 50 AND FK_FUNCIONALIDADE = 5014));