INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (5016, 'Alterar agressividade da Discadora', 'MLG_5016', 4);

INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (5016, 'AGENTE_AUTORIZADO');

-- XBRAIN --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,50, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,50, 50, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,51, 50, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,51, 51, 5016, 110827);

-- MSO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 22, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 20, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 22, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 20, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 24, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 25, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 27, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 20, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 25, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 27, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 29, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 53, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 22, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 26, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 21, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 21, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 25, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 23, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 25, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 29, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 23, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 53, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 31, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 53, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 28, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 31, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 25, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 23, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 25, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 21, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 53, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 25, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 21, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 20, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 26, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 26, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 27, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 23, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 20, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 21, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 24, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 26, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 27, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 26, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 30, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 22, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 23, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 29, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 20, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 24, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 30, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 28, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 31, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 53, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 22, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 24, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 23, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 24, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 27, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 30, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 21, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 21, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 53, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 30, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 26, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 27, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 29, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 30, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 23, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 29, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 30, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 22, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 28, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 31, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 20, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 31, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 31, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 24, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 28, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,23, 27, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 30, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 31, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,21, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 22, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 28, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,20, 28, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22, 24, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 26, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 29, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,24, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 3, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,25, 53, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 28, 5016, 110827);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,52, 29, 5016, 110827);

-- AGENTE AUTORIZADO --
-- SOCIO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,41, 40, 5016, 110827);
-- SOCIO SECUNDARIO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,42, 40, 5016, 110827);
-- GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,47, 40, 5016, 110827);
-- GERENTE *
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,82, 40, 5016, 110827);
-- GERENTE RECEPTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,91, 40, 5016, 110827);
