INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
SELECT 14006, 'Click to Call Alternativo', 'MLG_14006', 4
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM FUNCIONALIDADE
    WHERE (ID = 14006 AND ROLE = 'MLG_14006' AND FK_APLICACAO = 4));


INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 14006, 130821
FROM DUAL
WHERE NOT EXISTS (
    SELECT * FROM CARGO_DEPART_FUNC
    WHERE (FK_CARGO = 50 AND FK_DEPARTAMENTO = 50 AND FK_FUNCIONALIDADE = 14006));