INSERT INTO FUNCIONALIDADE VALUES (SEQ_FUNCIONALIDADE.NEXTVAL, 'Deslogar usuários do sistema', 'AUT_DESLOGAR_USUARIO', 1, null);

INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, SYSDATE, 50, 50, SEQ_FUNCIONALIDADE.CURRVAL, 1654839);

