-- REMOVE VDS_VISUALIZAR_RECEPTIVO DO AA SUPERVISOR RECEPTIVO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 90 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 3015;

-- REMOVE VDS_VISUALIZAR_RECEPTIVO DO AA SUPERVISOR TEMPORARIO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 81 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 3015;