INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (241, 'Gerenciar a Ata de Reunião', 'POL_241', 2);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (242, 'Visualizar Ata de Reunião', 'POL_242', 2);

-- NIVEL XBRAIN

-- DEPARTAMENTO: ADMIN | CARGO: ADMIN
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 50, 50, 241);

-- NIVEL MSO

-- DEPARTAMENTO: COMERCIAL | CARGO: MSO ANALISTA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 20, 21, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: MSO ASSISTENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 21, 21, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: MSO CONSULTOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 22, 21, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: MSO COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 23, 21, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: MSO GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 24, 21, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: MSO DIRETOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 25, 21, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: MSO AUDITORIA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 52, 21, 241);

-- NIVEL OPERACAO

-- DEPARTAMENTO: COMERCIAL | CARGO: EXECUTIVO
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 5, 3, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 4, 3, 241);

-- DEPARTAMENTO: COMERCIAL | CARGO: GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 7, 3, 241);

-- NIVEL AGENTE AUTORIZADO

-- DEPARTAMENTO: AGENTE AUTORIZADO | CARGO: SOCIO PRINCIPAL
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 41, 40, 242);