-- NOVA PERMISSÃO RELATÓRIOS --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (10008, 'Relatório Exportar Tabulacões Realizadas', 'REL_10008', 17);

-- INSERIR A PERMISSÃO 'REL_10008' PARA TODOS OS CARGOS QUE TEM A PERMISSÃO REL_10002 'Relatório Exportar Evidências' --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_FUNCIONALIDADE, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, FK_FUNCIONALIDADE, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO
FROM (SELECT 10008 FK_FUNCIONALIDADE, current_date DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 10002);

-- INSERIR A PERMISSÃO 'REL_10008' PARA TODOS OS USUARIOS QUE TEM A PERMISSÃO ESPECIAL REL_10002 'Relatório Exportar Evidências' --
INSERT INTO PERMISSAO_ESPECIAL (ID, FK_FUNCIONALIDADE, DATA_BAIXA, DATA_CADASTRO, FK_USUARIO, FK_USUARIO_BAIXA, FK_USUARIO_CADASTRO)
SELECT SEQ_PERMISSAO_ESPECIAL.nextval, FK_FUNCIONALIDADE, DATA_BAIXA, DATA_CADASTRO, FK_USUARIO, FK_USUARIO_BAIXA, FK_USUARIO_CADASTRO
FROM (SELECT 10008 FK_FUNCIONALIDADE, DATA_BAIXA, DATA_CADASTRO, FK_USUARIO, FK_USUARIO_BAIXA, FK_USUARIO_CADASTRO FROM PERMISSAO_ESPECIAL WHERE FK_FUNCIONALIDADE = 10002);