-- Alterar nome da APLICACAO de GERADOR_LEADS para FEEDER --
UPDATE APLICACAO SET CODIGO = 'FDR', NOME = 'FEEDER' WHERE ID = 23;

-- Alterar nome do NIVEL de GERADOR_LEADS para FEEDER --
UPDATE NIVEL SET CODIGO = 'FEEDER', NOME = 'Feeder' WHERE ID = 17;

-- Alterar nome do DEPARTAMENTO de GERADOR_LEADS para FEEDER --
UPDATE DEPARTAMENTO SET CODIGO = 'FEEDER', NOME = 'Feeder' WHERE ID = 68;

-- Cargo novo de Importador das Cargas --
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL, QUANTIDADE_SUPERIOR) VALUES (97, 'IMPORTADOR_CARGAS', 'Importador de Carga de Leads', 'A', 17, 50);

-- Alterar ROLE das FUNCIONALIDADES de GRL para FDR --
UPDATE FUNCIONALIDADE SET ROLE = 'FDR_GERENCIAR_LEAD' WHERE ID = 15000;
UPDATE FUNCIONALIDADE SET ROLE = 'FDR_CADASTRAR_GERADOR_LEADS' WHERE ID = 15001;
UPDATE FUNCIONALIDADE SET ROLE = 'FDR_GERENCIAR_GERADOR_LEADS' WHERE ID = 15002;
UPDATE FUNCIONALIDADE SET ROLE = 'FDR_APROVAR_GERADOR_LEADS' WHERE ID = 15003;
UPDATE FUNCIONALIDADE SET ROLE = 'FDR_CADASTRAR_LEAD' WHERE ID = 15004;
UPDATE FUNCIONALIDADE SET ROLE = 'FDR_AGENDAR_LEAD' WHERE ID = 15005;
UPDATE FUNCIONALIDADE SET ROLE = 'FDR_GERENCIAR_DIRECIONAMENTO_LEAD' WHERE ID = 15006;

-- Funcionalidade nova para importar carga de leads --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15008, 'Importar Carga de Leads', 'FDR_15008', 23);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15009, 'Visualizar Carga de Leads', 'FDR_15009', 23);

-- Adiciona permissoes para usuario XBRAIN --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 15008);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 15009);

-- Adiciona permissoes para usuario MSO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 15009);

-- Adiciona permissao para usuario IMPORTADOR_CARGAS --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 97, 68, 15008);