CREATE TABLE USUARIO_AFASTAMENTO
(
    ID NUMERIC(10, 0) NOT NULL,
    FK_USUARIO NUMERIC(10, 0) NOT NULL,
    DATA_CADASTRO TIMESTAMP(6) NOT NULL,
    INICIO TIMESTAMP(6) NOT NULL,
    FIM TIMESTAMP(6) NOT NULL
);

ALTER TABLE USUARIO_AFASTAMENTO
ADD CONSTRAINT PK_USUARIO_AFASTAMENTO_ID PRIMARY KEY(ID);

ALTER TABLE USUARIO_AFASTAMENTO
ADD CONSTRAINT FK_USUARIO_AFASTAMENTO_USUARIO FOREIGN KEY(FK_USUARIO)
REFERENCES USUARIO(ID);

ALTER TABLE USUARIO_HISTORICO
ADD FK_USUARIO_AFASTAMENTO NUMERIC(10, 0);

ALTER TABLE USUARIO_HISTORICO
ADD CONSTRAINT FK_USUARIO_AFASTAMENTO_USU_HIS FOREIGN KEY(FK_USUARIO_AFASTAMENTO)
REFERENCES USUARIO_AFASTAMENTO(ID);

create sequence SEQ_USUARIO_AFASTAMENTO start with 1 increment by  1;