-- REMOVE ROLE VDS_VISUALIZAR_AGENDAMENTO DO VENDEDOR OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE ID =
  (
      SELECT ID
        FROM CARGO_DEPART_FUNC
        WHERE FK_CARGO        = 8
        AND FK_FUNCIONALIDADE = 3009
  );