-- ADICIONA PERMISSAO VISUALIZAR AGENDAMENTO BACKOFFICE  TELEVENDAS
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES ((SELECT MAX(ID) + 1 FROM CARGO_DEPART_FUNC), SYSDATE, 56, 40, 3009);

-- ADICIONA PERMISSAO VISUALIZAR AGENDAMENTO BACKOFFICE  D2D
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES ((SELECT MAX(ID) + 1 FROM CARGO_DEPART_FUNC), SYSDATE, 78, 40, 3009);