INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (8003, 'Gerenciar Comunicados', 'CMD_8003', 21);

Insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, 20, 21, 8003);
Insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 8003);
Insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, 22, 20, 8003);
Insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, 24, 21, 8003);
Insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 8003);
Insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, 25, 21, 8003);
