-- Feriados Nacionais 2020
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Confraternização Universal', '2020-01-01', 'V', NULL, CURRENT_TIMESTAMP);
--INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
--VALUES (SEQ_FERIADO.nextval, 'Carnaval', '2020-02-24', 'V', NULL, CURRENT_TIMESTAMP); -- Carnaval, confirmar
--INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
--VALUES (SEQ_FERIADO.nextval, 'Carnaval', '2020-02-25', 'V', NULL, CURRENT_TIMESTAMP); -- Carnaval, confirmar
--INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
--VALUES (SEQ_FERIADO.nextval, 'Carnaval', '2020-02-26', 'V', NULL, CURRENT_TIMESTAMP); -- Carnaval, confirmar
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Paixão de Cristo', '2020-04-10', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Tiradentes', '2020-04-21', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Dia do Trabalho', '2020-05-01', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Corpus Christi', '2020-06-11', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Independência do Brasil', '2020-09-07', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Nossa Sr.a Aparecida - Padroeira do Brasil', '2020-10-12', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Finados', '2020-11-02', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Proclamação da República', '2020-11-15', 'V', NULL, CURRENT_TIMESTAMP);
INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
VALUES (SEQ_FERIADO.nextval, 'Natal', '2020-12-25', 'V', NULL, CURRENT_TIMESTAMP);




-- Feriados Municipais

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '25-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RIO BRANCO' and uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Rio Branco', '28-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RIO BRANCO' and uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira', '27-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACEIO' and uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACEIO' and uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Manaus', '24-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MANAUS' and uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Macapá', '04-Feb-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'MACAPA' and uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São João', '24-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SALVADOR' and uf.uf = 'BA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SALVADOR' and uf.uf = 'BA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São José', '19-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FORTALEZA' and uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Fortaleza', '13-Apr-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FORTALEZA' and uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'N. Senhora da Assunção', '15-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FORTALEZA' and uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Penha', '20-Apr-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'VITORIA' and uf.uf = 'ES';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Vitória', '08-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'VITORIA' and uf.uf = 'ES';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora Auxiliadora', '24-May-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'GOIANIA' and uf.uf = 'GO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Goiânia', '24-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'GOIANIA' and uf.uf = 'GO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São Pedro', '29-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Natividade de Nossa Senhora', '08-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Comerciário', '19-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO LUIS' and uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Assunção de Nossa Senhora', '15-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELO HORIZONTE' and uf.uf = 'MG';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Imaculada Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELO HORIZONTE' and uf.uf = 'MG';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de Santo Antônio', '13-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CAMPO GRANDE' and uf.uf = 'MS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Campo Grande', '26-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CAMPO GRANDE' and uf.uf = 'MS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Cuiabá', '08-Apr-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CUIABA' and uf.uf = 'MT';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Imaculada Conceição de Maria', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CUIABA' and uf.uf = 'MT';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Belém', '12-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BELEM' and uf.uf = 'PA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São João', '24-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'JOAO PESSOA' and uf.uf = 'PB';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'JOAO PESSOA' and uf.uf = 'PB';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira', '16-Jul-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RECIFE' and uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RECIFE' and uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Teresina', '16-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'TERESINA' and uf.uf = 'PI';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'TERESINA' and uf.uf = 'PI';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'N. Sra da Luz dos Pinhais', '08-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'CURITIBA' and uf.uf = 'PR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Sebastião, Padroeiro da cidade', '20-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'RIO DE JANEIRO' and uf.uf = 'RJ';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Santos Reis', '06-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'NATAL' and uf.uf = 'RN';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'N. Sra da Apresentação', '21-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'NATAL' and uf.uf = 'RN';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São Francisco de Sales', '24-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO VELHO' and uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora Auxiliadora', '24-May-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO VELHO' and uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Porto Velho', '02-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO VELHO' and uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São Sebastião', '20-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São Pedro', '29-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Boa Vista', '09-Jul-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BOA VISTA' and uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora dos Navegantes', '02-Feb-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PORTO ALEGRE' and uf.uf = 'RS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '23-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'FLORIANOPOLIS' and uf.uf = 'SC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Aracaju', '17-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'ARACAJU' and uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São João', '24-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'ARACAJU' and uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'ARACAJU' and uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da Cidade', '25-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO PAULO' and uf.uf = 'SP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'SAO PAULO' and uf.uf = 'SP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'São José', '19-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PALMAS' and uf.uf = 'TO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Palmas', '20-May-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'PALMAS' and uf.uf = 'TO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Sagrado Coração de Jesus', '19-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'LONDRINA' and uf.uf = 'PR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da cidade', '10-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'LONDRINA' and uf.uf = 'PR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '30-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE c.nome = 'BRASILIA' and uf.uf = 'DF';

-- FERIADOS ESTADUAIS

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Católico', '24-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Mulher', '08-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Acre', '15-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Revolução Acreana', '06-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Amazônia', '05-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AC';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São João', '24-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Pedro', '29-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Emancipação de Alagoas', '16-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '30-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AL';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Amazonas', '05-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AM';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São José', '19-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de Cabralzinho', '15-May-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Tiago', '25-Jul-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário da criação do ex-território federal do Amapá', '13-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'AP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Independência da Bahia', '02-Jul-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'BA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Data Magna do Ceará', '25-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'CE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Adesão ao Império Brasileiro', '28-Jul-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'MA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário do Mato Grosso do Sul', '11-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'MS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'MT';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Adesão ao Império Brasileiro', '15-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'N. Sra. de Nazaré', '13-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Nossa Senhora da Conceição', '08-Dec-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PA';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Fundação do Estado da Paraíba', '05-Aug-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PB';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Revolução Pernambucana', '06-Mar-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São João', '24-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Piauí', '19-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'PI';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia de São Jorge', '23-Apr-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RJ';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RJ';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Mártires de Cunhaú e Uruaçu', '03-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RN';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Rondônia', '04-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia do Evangélico', '18-Jun-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Roraima', '05-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Dia da Consciência Negra', '20-Nov-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RR';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Proc. República Rio Grandense', '20-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'RS';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Sergipe', '08-Jan-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'SE';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Revolução Constitucionalista', '09-Jul-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'SP';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Padroeira de Tocantins', '08-Sep-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'TO';

INSERT INTO FERIADO(ID, NOME, DATA_FERIADO, FERIADO_NACIONAL, FK_CIDADE, DATA_CADASTRO)
SELECT SEQ_FERIADO.nextval, 'Aniversário de Tocantins', '05-Oct-2020', 'F', C.ID, CURRENT_TIMESTAMP FROM AUTENTICACAO.CIDADE C
INNER JOIN AUTENTICACAO.UF UF ON c.fk_uf = uf.id
WHERE uf.uf = 'TO';
