INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL)
  VALUES (3009, 'AGENTE_AUTORIZADO');

INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL)
  VALUES (3044, 'D2D_PROPRIO');

INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL)
  VALUES (3043, 'D2D_PROPRIO');

-- ADICIONA PERMISSAO EXECUTIVO HUNTER PARA VISUALIZAR AGENDAMENTO NO CANAL AA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES ((SELECT MAX(ID) + 1 FROM CARGO_DEPART_FUNC), SYSDATE, 95, 3, 3009);

-- ADICIONA PERMISSAO EXECUTIVO PARA VISUALIZAR AGENDAMENTO NO CANAL AA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES ((SELECT MAX(ID) + 1 FROM CARGO_DEPART_FUNC), SYSDATE, 5, 3, 3009);

-- ADICIONA PERMISSAO GERENTE OPERACAO PARA VISUALIZAR AGENDAMENTO NO CANAL AA
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES ((SELECT MAX(ID) + 1 FROM CARGO_DEPART_FUNC), SYSDATE, 7, 3, 3009);

-- ADICIONA PERMISSAO EXECUTIVO PARA VISUALIZAR AGENDA DE VISITAS NO CANAL D2D
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES ((SELECT MAX(ID) + 1 FROM CARGO_DEPART_FUNC), SYSDATE, 7, 3, 3044);