INSERT INTO APLICACAO (ID, CODIGO, NOME) VALUES (23, 'GRL', 'GERADOR LEAD');

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (15000, 'Gerenciar Lead', 'GRL_GERENCIAR_LEAD', 23);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3046, 'Tratar Lead', 'VDS_TRATAR_LEAD', 3);