-- PERMISSÃO PARA GERENCIAR CONFIGURAÇÕES DE CIDADE - NÍVEL XBRAIN --

-- FUNCIONALIDADE
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (7008, 'Gerenciar Configurações de Cidade', 'INT_7008', 8);

-- PERMISSÕES
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 7008);
