-- ADICIONAR FUNCIONALIDADES POR CANAL
DECLARE
    QTDE INT;
    TYPE ARRAY_NUMBER IS VARRAY(12) OF NUMBER(10,0);
    FUNCIONALIDADE_IDS ARRAY_NUMBER := ARRAY_NUMBER(2007, 2008, 2009, 2015, 2033, 2034, 2043, 2042, 2038, 2053, 2039, 2040);
BEGIN
    FOR i IN 1..FUNCIONALIDADE_IDS.count LOOP
        -- AGENTE AUTORIZADO
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_IDS(i)
                AND CANAL = 'AGENTE_AUTORIZADO';
        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:ROLE_ID, ''AGENTE_AUTORIZADO'')'
            USING FUNCIONALIDADE_IDS(i);
        END IF;

        -- ATIVO PROPRIO
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_IDS(i)
                AND CANAL = 'ATIVO_PROPRIO';
        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:ROLE_ID, ''ATIVO_PROPRIO'')'
            USING FUNCIONALIDADE_IDS(i);
        END IF;
    END LOOP;
END;

/

-- ATRIBUIR PERMISSÃO CTR_2038 PARA O CARGO 6 E DEPARTAMENTO 3
DECLARE
    QTDE INT;
BEGIN
    SELECT COUNT(*) INTO QTDE
        FROM CARGO_DEPART_FUNC
        WHERE FK_CARGO = 6
            AND FK_DEPARTAMENTO = 3
            AND FK_FUNCIONALIDADE = 2038;

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO CARGO_DEPART_FUNC(ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES(SEQ_CARGO_DEPART_FUNC.NEXTVAL, 6, 3, 2038)';
    END IF;
END;

/

-- REMOVER PERMISSÃO 10015 PARA O CARGO 7 e 4 e PERMISSÃO 10001 PARA O CARGO 120 DO DEPARTAMENTO 3
DECLARE
    QTDE INT;
BEGIN
    -- GERENTE
    SELECT COUNT(*) INTO QTDE
        FROM CARGO_DEPART_FUNC
        WHERE FK_CARGO = 7
            AND FK_DEPARTAMENTO = 3
            AND FK_FUNCIONALIDADE = 10015;
    IF (QTDE = 1) THEN
        EXECUTE IMMEDIATE 'DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 7 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 10015';
    END IF;

    -- COORDENADOR
    SELECT COUNT(*) INTO QTDE
        FROM CARGO_DEPART_FUNC
        WHERE FK_CARGO = 4
            AND FK_DEPARTAMENTO = 3
            AND FK_FUNCIONALIDADE = 10015;
    IF (QTDE = 1) THEN
        EXECUTE IMMEDIATE 'DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 4 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 10015';
    END IF;

    -- OPERADOR TELEVENDAS
    SELECT COUNT(*) INTO QTDE
        FROM CARGO_DEPART_FUNC
        WHERE FK_CARGO = 120
            AND FK_DEPARTAMENTO = 3
            AND FK_FUNCIONALIDADE = 10001;
    IF (QTDE = 1) THEN
        EXECUTE IMMEDIATE 'DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 120 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 10001';
    END IF;
END;