-- ADICIONA FUNCIONALIDADE PARA GERENCIAR MENU DE SEGMENTAÇÃO DE CARGA
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20005, 'Gerenciar Segmentação de Carga', 'FDR_20005', 23);

-- ADICIONA FUNCIONALIDADE PARA GERENCIAR MENU DE LAYOUT DE CARGA
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20006, 'Gerenciar Layout de Carga', 'FDR_20006', 23);

-- ADICIONA NOVAS FUNCIONALIDADES PARA O CANAL AGENTE AUTORIZADO
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (20005, 'AGENTE_AUTORIZADO');
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (20006, 'AGENTE_AUTORIZADO');

-- ADICIONA FUNÇÃO DE GERENCIAR LEADS PARA CARGO DE ASSISTENTE OPERAÇÃO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 2, 3, 15000);

-- ADICIONA FUNÇAO DE GERENCIAR MENU DE SEGMENTAÇÃO DE CARGA AOS CARGOS DE OPERAÇÃO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 2, 3, 20005);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 20005);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 5, 3, 20005);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 6, 3, 20005);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 7, 3, 20005);