-- ADICIONAR FUNCIONALIDADES POR CANAL
DECLARE
    QTDE INT;
    FUNCIONALIDADE_ID INT;
    CARGO_DEPART_FUNC_ID INT;

BEGIN
    -- CRN_VISUALIZAR_CHAMADO
    FUNCIONALIDADE_ID := 0;
    SELECT ID INTO FUNCIONALIDADE_ID
        FROM FUNCIONALIDADE
        WHERE ROLE = 'CRN_VISUALIZAR_CHAMADO';

    IF (FUNCIONALIDADE_ID != 0) THEN
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_ID
                AND CANAL = 'D2D_PROPRIO';

        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:FUNCIONALIDADE_ID, ''D2D_PROPRIO'')'
            USING FUNCIONALIDADE_ID;
        END IF;
    END IF;

    -- CRN_ABRIR_CHAMADO
    FUNCIONALIDADE_ID := 0;
    SELECT ID INTO FUNCIONALIDADE_ID
        FROM FUNCIONALIDADE
        WHERE ROLE = 'CRN_ABRIR_CHAMADO';

    IF (FUNCIONALIDADE_ID != 0) THEN
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_ID
                AND CANAL = 'D2D_PROPRIO';

        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:FUNCIONALIDADE_ID, ''D2D_PROPRIO'')'
            USING FUNCIONALIDADE_ID;
        END IF;
    END IF;

    -- CRN_GERENCIAR_CHAMADO
    FUNCIONALIDADE_ID := 0;
    SELECT ID INTO FUNCIONALIDADE_ID
        FROM FUNCIONALIDADE
        WHERE ROLE = 'CRN_GERENCIAR_CHAMADO';

    IF (FUNCIONALIDADE_ID != 0) THEN
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_ID
                AND CANAL = 'D2D_PROPRIO';

        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:FUNCIONALIDADE_ID, ''D2D_PROPRIO'')'
            USING FUNCIONALIDADE_ID;
        END IF;
    END IF;

    -- EVD_11005
    FUNCIONALIDADE_ID := 0;
    SELECT ID INTO FUNCIONALIDADE_ID
        FROM FUNCIONALIDADE
        WHERE ROLE = 'EVD_11005';

    IF (FUNCIONALIDADE_ID != 0) THEN
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_ID
                AND CANAL = 'D2D_PROPRIO';

        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:FUNCIONALIDADE_ID, ''D2D_PROPRIO'')'
            USING FUNCIONALIDADE_ID;
        END IF;
    END IF;

    -- EVD_11006
    FUNCIONALIDADE_ID := 0;
    SELECT ID INTO FUNCIONALIDADE_ID
        FROM FUNCIONALIDADE
        WHERE ROLE = 'EVD_11006';

    IF (FUNCIONALIDADE_ID != 0) THEN
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_ID
                AND CANAL = 'D2D_PROPRIO';

        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:FUNCIONALIDADE_ID, ''D2D_PROPRIO'')'
            USING FUNCIONALIDADE_ID;
        END IF;
    END IF;

    -- EVD_11007
    FUNCIONALIDADE_ID := 0;
    SELECT ID INTO FUNCIONALIDADE_ID
        FROM FUNCIONALIDADE
        WHERE ROLE = 'EVD_11007';

    IF (FUNCIONALIDADE_ID != 0) THEN
        SELECT COUNT(*) INTO QTDE
            FROM FUNCIONALIDADE_CANAL
            WHERE FK_FUNCIONALIDADE = FUNCIONALIDADE_ID
                AND CANAL = 'D2D_PROPRIO';

        IF (QTDE = 0) THEN
            EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(:FUNCIONALIDADE_ID, ''D2D_PROPRIO'')'
            USING FUNCIONALIDADE_ID;
        END IF;
    END IF;
END;

/

-- REMOVER PERMISSÃO MLG_5017 DO CARGO 120 E DEPARTAMENTO 3
DECLARE
    FUNCIONALIDADE_ID INT;
    CARGO_DEPART_FUNC_ID INT;
BEGIN
    CARGO_DEPART_FUNC_ID := 0;
    SELECT ID INTO FUNCIONALIDADE_ID
        FROM FUNCIONALIDADE
        WHERE ROLE = 'MLG_5017';

    IF (FUNCIONALIDADE_ID != 0) THEN
        SELECT ID INTO CARGO_DEPART_FUNC_ID
            FROM CARGO_DEPART_FUNC
            WHERE FK_CARGO = 120
                AND FK_DEPARTAMENTO = 3
                AND FK_FUNCIONALIDADE = FUNCIONALIDADE_ID;

        IF (CARGO_DEPART_FUNC_ID != 0) THEN
            EXECUTE IMMEDIATE 'DELETE FROM CARGO_DEPART_FUNC WHERE ID = :CARGO_DEPART_FUNC_ID'
            USING CARGO_DEPART_FUNC_ID;
        END IF;
    END IF;
END;
