--- Adiciona canal PAP_PME
ALTER TABLE USUARIO DROP CONSTRAINT TIPO_CANAL_VALUES;
ALTER TABLE USUARIO ADD CONSTRAINT TIPO_CANAL_VALUES CHECK (TIPO_CANAL IN ('PAP','PAP_PME','PAP_PREMIUM','INSIDE_SALES_PME'));