-- ADICIONAR FUNCIONALIDADES POR CANAL
DECLARE
    QTDE INT;
BEGIN
    -- 13000 - CRN_VISUALIZAR_CHAMADO
    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 13000
            AND CANAL = 'D2D_PROPRIO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(13000, ''D2D_PROPRIO'')';
    END IF;

    -- 13001 - CRN_ABRIR_CHAMADO
    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 13001
            AND CANAL = 'D2D_PROPRIO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(13001, ''D2D_PROPRIO'')';
    END IF;

    -- 13002 - CRN_GERENCIAR_CHAMADO
    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 13002
            AND CANAL = 'D2D_PROPRIO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(13002, ''D2D_PROPRIO'')';
    END IF;

    -- 11005 - EVD_11005
    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 11005
            AND CANAL = 'D2D_PROPRIO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(11005, ''D2D_PROPRIO'')';
    END IF;

    -- 11006 - EVD_11006
    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 11006
            AND CANAL = 'D2D_PROPRIO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(11006, ''D2D_PROPRIO'')';
    END IF;

    -- 11007 - EVD_11007
    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 11007
            AND CANAL = 'D2D_PROPRIO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(11007, ''D2D_PROPRIO'')';
    END IF;

    -- 11002 - CTR_11002
    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 11002
            AND CANAL = 'ATIVO_PROPRIO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(11002, ''ATIVO_PROPRIO'')';
    END IF;

    SELECT COUNT(*) INTO QTDE
        FROM FUNCIONALIDADE_CANAL
        WHERE FK_FUNCIONALIDADE = 11002
            AND CANAL = 'AGENTE_AUTORIZADO';

    IF (QTDE = 0) THEN
        EXECUTE IMMEDIATE 'INSERT INTO FUNCIONALIDADE_CANAL(FK_FUNCIONALIDADE, CANAL) VALUES(11002, ''AGENTE_AUTORIZADO'')';
    END IF;
END;

/

-- REMOVER PERMISSÃO MLG_5017 DO CARGO 120 E DEPARTAMENTO 3
DECLARE
    QTDE INT;
BEGIN
    SELECT COUNT(*) INTO QTDE
        FROM CARGO_DEPART_FUNC
        WHERE FK_CARGO = 120
            AND FK_DEPARTAMENTO = 3
            AND FK_FUNCIONALIDADE = 5017;

    IF (QTDE != 0) THEN
        EXECUTE IMMEDIATE 'DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 120 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 5017';
    END IF;
END;
