INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (7, 'CREDITCASH', 'Creditcash');

INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO)
VALUES ((SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE' AND SITUACAO = 'A'), 7);