CREATE SEQUENCE SEQ_HORARIO_ACESSO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_HORARIO_ACESSO_HIST START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_DIA_ACESSO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_DIA_ACESSO_HIST START WITH 1 INCREMENT BY 1;

CREATE TABLE HORARIO_ACESSO (
    ID INTEGER NOT NULL,
    FK_SITE INTEGER NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    USUARIO_ALTERACAO_ID INTEGER NOT NULL,
    USUARIO_ALTERACAO_NOME VARCHAR(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_SITE) REFERENCES SITE (ID)
);

CREATE TABLE HORARIO_ACESSO_HIST (
    ID INTEGER NOT NULL,
    FK_HORARIO_ACESSO INTEGER NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    USUARIO_ALTERACAO_ID INTEGER NOT NULL,
    USUARIO_ALTERACAO_NOME VARCHAR(100 CHAR) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_HORARIO_ACESSO) REFERENCES HORARIO_ACESSO (ID)
);

CREATE TABLE DIA_ACESSO (
    ID INTEGER NOT NULL,
    FK_HORARIO_ACESSO INTEGER NOT NULL,
    DIA_SEMANA VARCHAR(20) NOT NULL,
    HORARIO_INICIO TIMESTAMP(6) NOT NULL,
    HORARIO_FIM TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_HORARIO_ACESSO) REFERENCES HORARIO_ACESSO (ID)
);

CREATE TABLE DIA_ACESSO_HIST (
    ID INTEGER NOT NULL,
    FK_HORARIO_ACESSO_HIST INTEGER NOT NULL,
    DIA_SEMANA VARCHAR(20) NOT NULL,
    HORARIO_INICIO TIMESTAMP(6) NOT NULL,
    HORARIO_FIM TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (FK_HORARIO_ACESSO_HIST) REFERENCES HORARIO_ACESSO_HIST (ID)
);