UPDATE REGIONAL SET ID = 1022 WHERE NOME = 'RBS';
UPDATE REGIONAL SET ID = 1023 WHERE NOME = 'RCO';
UPDATE REGIONAL SET ID = 1024 WHERE NOME = 'RMG';
UPDATE REGIONAL SET ID = 1025 WHERE NOME = 'RNE';
UPDATE REGIONAL SET ID = 1026 WHERE NOME = 'RNO';
UPDATE REGIONAL SET ID = 1027 WHERE NOME = 'RPS';
UPDATE REGIONAL SET ID = 1028 WHERE NOME = 'RRE';
UPDATE REGIONAL SET ID = 1029 WHERE NOME = 'RRS';
UPDATE REGIONAL SET ID = 1030 WHERE NOME = 'RSC';
UPDATE REGIONAL SET ID = 1031 WHERE NOME = 'RSI';

ALTER SEQUENCE SEQ_REGIONAL RESTART START WITH 1032;

UPDATE CIDADE SET FK_REGIONAL = 1022 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('BA','SE'));
UPDATE CIDADE SET FK_REGIONAL = 1023 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('AC','DF','GO','MS','MT','RO','TO'));
UPDATE CIDADE SET FK_REGIONAL = 1024 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'MG');
UPDATE CIDADE SET FK_REGIONAL = 1025 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('AL','CE','PB','PE','PI','RN'));
UPDATE CIDADE SET FK_REGIONAL = 1026 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('AM','AP','MA','PA','RR'));
UPDATE CIDADE SET FK_REGIONAL = 1027 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('PR','SC'));
UPDATE CIDADE SET FK_REGIONAL = 1028 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('ES','RJ'));
UPDATE CIDADE SET FK_REGIONAL = 1029 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'RS');
UPDATE CIDADE SET FK_REGIONAL = 1031 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'SP');
UPDATE CIDADE SET FK_REGIONAL = 1030 WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'SP') AND
    NOME IN ('ALUMINIO','ARACARIGUAMA','ARUJA','ATIBAIA','BARUERI','BIRITIBA-MIRIM',
        'BOM JESUS DOS PERDOES','BRAGANCA PAULISTA','CABREUVA','CAIEIRAS','CAJAMAR',
        'CAMPO LIMPO PAULISTA','CARAPICUIBA','COTIA','DIADEMA','EMBU DAS ARTES',
        'EMBU-GUACU','FERRAZ DE VASCONCELOS','FRANCISCO MORATO','FRANCO DA ROCHA',
        'GUARAREMA','GUARULHOS','IGARATA','ITAPECERICA DA SERRA','ITAPEVI',
        'ITAQUAQUECETUBA','ITATIBA','ITU','ITUPEVA','JANDIRA','JARINU','JOANOPOLIS',
        'JUNDIAI','JUQUITIBA','MAIRINQUE','MAIRIPORA','MAUA','MOGI DAS CRUZES',
        'MORUNGABA','NAZARE PAULISTA','OSASCO','PEDRA BELA','PINHALZINHO','PIRACAIA',
        'PIRAPORA DO BOM JESUS','POA','RIBEIRAO PIRES','RIO GRANDE DA SERRA',
        'SALESOPOLIS','SALTO','SANTA ISABEL','SANTANA DE PARNAIBA','SANTO ANDRE',
        'SAO BERNARDO DO CAMPO','SAO CAETANO DO SUL','SAO LOURENCO DA SERRA','SAO PAULO',
        'SAO ROQUE','SUZANO','TABOAO DA SERRA','TUIUTI','VARGEM','VARGEM GRANDE PAULISTA',
        'VARZEA PAULISTA');