DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 3043 AND FK_CARGO = 4 AND FK_DEPARTAMENTO = 3;

    IF QTD = 0 THEN
        INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 3043);
    END IF;
END;