ALTER TABLE REGIONAL ADD NOVA_REGIONAL VARCHAR(1);
UPDATE REGIONAL SET NOVA_REGIONAL = 'F';
UPDATE REGIONAL SET NOVA_REGIONAL = 'V' WHERE NOME IN ('RBS', 'RCO', 'RMG', 'RNE', 'RNO', 'RPS', 'RRE', 'RRS', 'RSC', 'RSI');