-- Criar usuário Creditcash --
INSERT INTO USUARIO
    (
        ID,
        ALTERAR_SENHA,
        DATA_CADASTRO,
        EMAIL_01,
        NASCIMENTO,
        NOME,
        SENHA,
        SITUACAO,
        FK_CARGO,
        FK_DEPARTAMENTO,
        RECUPERAR_SENHA_TENTATIVA
    )
    VALUES
    (
        SEQ_USUARIO.NEXTVAL,
        'F',
        CURRENT_DATE,
        'INTEGRACAOCREDITCASH@XBRAIN.COM.BR',
        CURRENT_DATE,
        'INTEGRAÇÃO CREDITCASH',
        '$2a$10$L4cjDCSCj0LuFGD38m7JWeWfoPq5URRo6VJ3Y.QUJo1x4VisB6Ppe',
        'A',
        (SELECT ID FROM CARGO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO = 'A'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO ='A'),
        0
    );

INSERT INTO USUARIO_UNIDADE_NEGOCIO (FK_USUARIO, FK_UNIDADE_NEGOCIO)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOCREDITCASH@XBRAIN.COM.BR'), 3);

INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOCREDITCASH@XBRAIN.COM.BR'), 4);

-- Criar funcionalidade --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (7009, 'Resgatar tratativas para Creditcash', 'INT_7009', 8);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 7009);

-- Adicionar permissão especial para o usuário Creditcash --
INSERT INTO PERMISSAO_ESPECIAL
    (
        ID,
        DATA_CADASTRO,
        FK_FUNCIONALIDADE,
        FK_USUARIO,
        FK_USUARIO_CADASTRO
    )
VALUES
    (
        SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        7009,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOCREDITCASH@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'FAGNERONESKO@XBRAIN.COM.BR')
    )