ALTER TABLE CIDADE ADD FK_REGIONAL INTEGER;
ALTER TABLE CIDADE ADD FOREIGN KEY (FK_REGIONAL) REFERENCES REGIONAL (ID);

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RBS')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('BA','SE'));

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RCO')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('AC','DF','GO','MS','MT','RO','TO'));

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RMG')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'MG');

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RNE')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('AL','CE','PB','PE','PI','RN'));

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RNO')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('AM','AP','MA','PA','RR'));

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RPS')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('PR','SC'));

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RRE')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF IN ('ES','RJ'));

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RRS')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'RS');

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RSI')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'SP');

UPDATE CIDADE SET FK_REGIONAL = (SELECT ID FROM REGIONAL WHERE NOME = 'RSC')
WHERE FK_UF IN (SELECT ID FROM UF WHERE UF = 'SP') AND
    NOME IN ('ALUMINIO','ARACARIGUAMA','ARUJA','ATIBAIA','BARUERI','BIRITIBA-MIRIM',
        'BOM JESUS DOS PERDOES','BRAGANCA PAULISTA','CABREUVA','CAIEIRAS','CAJAMAR',
        'CAMPO LIMPO PAULISTA','CARAPICUIBA','COTIA','DIADEMA','EMBU DAS ARTES',
        'EMBU-GUACU','FERRAZ DE VASCONCELOS','FRANCISCO MORATO','FRANCO DA ROCHA',
        'GUARAREMA','GUARULHOS','IGARATA','ITAPECERICA DA SERRA','ITAPEVI',
        'ITAQUAQUECETUBA','ITATIBA','ITU','ITUPEVA','JANDIRA','JARINU','JOANOPOLIS',
        'JUNDIAI','JUQUITIBA','MAIRINQUE','MAIRIPORA','MAUA','MOGI DAS CRUZES',
        'MORUNGABA','NAZARE PAULISTA','OSASCO','PEDRA BELA','PINHALZINHO','PIRACAIA',
        'PIRAPORA DO BOM JESUS','POA','RIBEIRAO PIRES','RIO GRANDE DA SERRA',
        'SALESOPOLIS','SALTO','SANTA ISABEL','SANTANA DE PARNAIBA','SANTO ANDRE',
        'SAO BERNARDO DO CAMPO','SAO CAETANO DO SUL','SAO LOURENCO DA SERRA','SAO PAULO',
        'SAO ROQUE','SUZANO','TABOAO DA SERRA','TUIUTI','VARGEM','VARGEM GRANDE PAULISTA',
        'VARZEA PAULISTA');