-- FUNCIONALIDADE --
INSERT
    INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
    VALUES (20011, 'Realizar Download do Arquivo', 'VDS_20011', 3);

-- CARGO_DEPART_FUNC --
INSERT
    INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
    VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, 50, 50, 20011);