-- CRIA FUNCIONALIDADE DE GERENCIAR HORARIOS DE ACESSO
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20009, 'Gerenciar Horários de Acesso', 'AUT_20009', 1);

-- INCLUI NOVA FUNCIONALIDADE AO CANAL ATIVO PROPRIO
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (20009, 'ATIVO_PROPRIO');

-- ADICIONA FUNCIONALIDADE AO CARGO DE ADMINISTRADOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20009);