-- Permissão: VDS_3058 --
-- OPERACAO | DIRETOR_OPERACAO | COMERCIAL

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, CANAL) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 6, 3, 3056, 'ATIVO_PROPRIO');
