DELETE FROM CARGO_DEPART_FUNC WHERE ID IN(
    SELECT ID
      FROM CARGO_DEPART_FUNC
     WHERE FK_FUNCIONALIDADE = 10007
       AND FK_CARGO IN (3, 51, 86, 52)
    UNION
    SELECT ID
      FROM CARGO_DEPART_FUNC
     WHERE FK_FUNCIONALIDADE = 10007
       AND FK_CARGO = 22
       AND FK_DEPARTAMENTO = 30
);