DROP TABLE DIA_ACESSO_HIST;
DROP TABLE DIA_ACESSO;
DROP TABLE HORARIO_ACESSO_HIST;
DROP TABLE HORARIO_ACESSO;

DROP SEQUENCE SEQ_DIA_ACESSO;
DROP SEQUENCE SEQ_DIA_ACESSO_HIST;
DROP SEQUENCE SEQ_HORARIO_ACESSO;
DROP SEQUENCE SEQ_HORARIO_ACESSO_HIST;

CREATE SEQUENCE SEQ_HORARIO_ACESSO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HORARIO_ATUACAO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HORARIO_HISTORICO START WITH 1 INCREMENT BY 1;

CREATE TABLE HORARIO_ACESSO (
    ID INTEGER NOT NULL PRIMARY KEY,
    FK_SITE INTEGER NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    USUARIO_ALTERACAO_ID INTEGER NOT NULL,
    USUARIO_ALTERACAO_NOME VARCHAR(100 CHAR) NOT NULL,
    FOREIGN KEY (FK_SITE) REFERENCES SITE (ID)
);

CREATE TABLE HORARIO_HISTORICO (
    ID INTEGER NOT NULL PRIMARY KEY,
    FK_HORARIO_ACESSO INTEGER NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    USUARIO_ALTERACAO_ID INTEGER NOT NULL,
    USUARIO_ALTERACAO_NOME VARCHAR(100 CHAR) NOT NULL,
    FOREIGN KEY (FK_HORARIO_ACESSO) REFERENCES HORARIO_ACESSO (ID)
);

CREATE TABLE HORARIO_ATUACAO (
    ID INTEGER NOT NULL PRIMARY KEY,
    FK_HORARIO_ACESSO INTEGER,
    FK_HORARIO_HISTORICO INTEGER NOT NULL,
    DIA_SEMANA VARCHAR(20 CHAR) NOT NULL,
    HORARIO_INICIO TIMESTAMP(6) NOT NULL,
    HORARIO_FIM TIMESTAMP(6) NOT NULL,
    FOREIGN KEY (FK_HORARIO_ACESSO) REFERENCES HORARIO_ACESSO (ID),
    FOREIGN KEY (FK_HORARIO_HISTORICO) REFERENCES HORARIO_HISTORICO (ID)
);