-- REMOVE REGISTROS COM A UF SP E REINSERE NOVAMENTE COM AS REGIONAIS COM OS IDS CORRETOS
DELETE FROM UF_REGIONAL WHERE FK_UF = 2;
-- REGIONAL RBS UF BA, SE
UPDATE UF_REGIONAL SET FK_REGIONAL = 1022 WHERE FK_UF IN (10, 16);
-- REGIONAL RCO UF DF, GO, MS, MT, TO, RO, AC
UPDATE UF_REGIONAL SET FK_REGIONAL = 1023 WHERE FK_UF IN (7, 13, 14, 15, 18, 23, 25);
-- REGIONAL RMG UF MG
UPDATE UF_REGIONAL SET FK_REGIONAL = 1024 WHERE FK_UF = 8;
-- REGIONAL RNE CE, PI, AL, PB, PE, RN
UPDATE UF_REGIONAL SET FK_REGIONAL = 1025 WHERE FK_UF IN (9, 11, 12, 17, 24, 26);
-- REGIONAL RNO MA, RR, AM, PA, AP
UPDATE UF_REGIONAL SET FK_REGIONAL = 1026 WHERE FK_UF IN (4, 6, 20, 21, 27);
-- REGIONAL RPS UF PR, SC
UPDATE UF_REGIONAL SET FK_REGIONAL = 1027 WHERE FK_UF IN (1, 22);
-- REGIONAL RRE RJ, ES
UPDATE UF_REGIONAL SET FK_REGIONAL = 1028 WHERE FK_UF IN (3, 19);
-- REGIONAL RRS UF RS
UPDATE UF_REGIONAL SET FK_REGIONAL = 1029 WHERE FK_UF = 5;
-- REGIONAL RSC, RSI UF SP
INSERT INTO UF_REGIONAL (FK_UF, FK_REGIONAL) VALUES (2, 1030);
INSERT INTO UF_REGIONAL (FK_UF, FK_REGIONAL) VALUES (2, 1031);