-- CIDADE_DBM
CREATE SEQUENCE SEQ_CIDADE_DBM START WITH 1 INCREMENT BY 1;
CREATE TABLE CIDADE_DBM (
    ID                          INTEGER NOT NULL,
    FK_CIDADE                   INTEGER NOT NULL,
    CODIGO_CIDADE_DBM           INTEGER NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CIDADE_DBM FOREIGN KEY (FK_CIDADE) REFERENCES CIDADE
);
CREATE INDEX CIDADE_DBM_IDX01 ON CIDADE_DBM(CODIGO_CIDADE_DBM);

-- CIDADE
ALTER TABLE CIDADE DROP COLUMN CODIGO_CIDADE_DBM;