-- FUNCIONALIDADE --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
    VALUES (246, 'Buscar Dados Vendedor NetSales', 'POL_243', 2);

-- Permissão: POL_243 --
-- OPERACAO | ASSISTENTE_OPERACAO | COMERCIAL

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 2, 3, 246);

-- Permissão: POL_243 --
-- OPERACAO | ASSISTENTE_HUNTER_OPERACAO | COMERCIAL

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 94, 3, 246);

-- Permissão: POL_243 --
-- OPERACAO | EXECUTIVO_OPERACAO | COMERCIAL

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 5, 3, 246);

-- Permissão: POL_243 --
-- OPERACAO | EXECUTIVO_HUNTER_OPERACAO | COMERCIAL

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 95, 3, 246);