
DELETE CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE in ('14000', '14001', '14002', '14003','14004');


/*Nivel Operacao - 14000(ABRIR CHAMADO)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '1', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '2', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '3', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '4', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '5', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '6', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '7', '3', '14000');


/*Nivel MSO - 14000(ABRIR CHAMADO)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '20', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '21', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '22', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '23', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '24', '21', '14000');
DELETE CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE in ('14000', '14001', '14002', '14003','14004');



/*Nivel Operacao - 14000(ABRIR CHAMADO)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '1', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '2', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '3', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '4', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '5', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '6', '3', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '7', '3', '14000');


/*Nivel MSO - 14000(ABRIR CHAMADO)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '20', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '21', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '22', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '23', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '24', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '25', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '52', '21', '14000');

/*Nivel MSO - 14002(TRATAR CHAMADO PROCESSO)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '20', '21', '14002');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '21', '21', '14002');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '22', '21', '14002');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '23', '21', '14002');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '24', '21', '14002');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '25', '21', '14002');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '52', '21', '14002');

/*Nivel MSO - 14004(VISUALIZAR CHAMADO GERAL)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '20', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '21', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '22', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '23', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '24', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '25', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '52', '21', '14004');

/*Nivel XBRAIN - 14004(VISUALIZAR CHAMADO GERAL)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '50', '50', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '51', '50', '14004');

/*Nivel XBRAIN - 14003(TRATAR CHAMADO GERAL)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '50', '50', '14003');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '51', '50', '14003');