-- Criar usuário ANATEL --
INSERT INTO USUARIO
    (
        ID,
        ALTERAR_SENHA,
        DATA_CADASTRO,
        EMAIL_01,
        NASCIMENTO,
        NOME,
        SENHA,
        SITUACAO,
        FK_CARGO,
        FK_DEPARTAMENTO,
        RECUPERAR_SENHA_TENTATIVA
    )
    VALUES
    (
        SEQ_USUARIO.NEXTVAL,
        'F',
        CURRENT_DATE,
        'INTEGRACAOANATEL@XBRAIN.COM.BR',
        CURRENT_DATE,
        'INTEGRAÇÃO ANATEL',
        '$2a$10$L4cjDCSCj0LuFGD38m7JWeWfoPq5URRo6VJ3Y.QUJo1x4VisB6Ppe',
        'A',
        (SELECT ID FROM CARGO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO = 'A'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO ='A'),
        0
    );

INSERT INTO USUARIO_UNIDADE_NEGOCIO (FK_USUARIO, FK_UNIDADE_NEGOCIO)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOANATEL@XBRAIN.COM.BR'), 3);

INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOANATEL@XBRAIN.COM.BR'), 4);

-- Adicionar permissão especial para o usuário ANATEL --
INSERT INTO PERMISSAO_ESPECIAL
    (
        ID,
        DATA_CADASTRO,
        FK_FUNCIONALIDADE,
        FK_USUARIO,
        FK_USUARIO_CADASTRO
    )
VALUES
    (
        SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        10019,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOANATEL@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'JOSE@XBRAIN.COM.BR')
    )
