ALTER TABLE solicitacao_ramal ADD (canal VARCHAR2(80) DEFAULT 'AGENTE_AUTORIZADO' NOT NULL,
FK_SUBCANAL INTEGER,

CONSTRAINT FK_SUBCANAL_SOLICITACAO_RAMAL
FOREIGN KEY (FK_SUBCANAL) REFERENCES SUB_CANAL(ID)
);