INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 20, 21, 2033, 1);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 22, 21, 2033, 1);