DECLARE
    QTD1 INT;
    QTD2 INT;
BEGIN
    SELECT COUNT(*) INTO QTD1 FROM FUNCIONALIDADE WHERE ID = 3067;
    SELECT COUNT(*) INTO QTD2 FROM APLICACAO WHERE ID = 28;

    IF QTD1 = 1 THEN
        UPDATE FUNCIONALIDADE SET FK_APLICACAO = 3 WHERE ID = 3067;
    END IF;

    IF QTD2 = 1 THEN
        DELETE FROM APLICACAO WHERE ID = 28;
    END IF;
END;