INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (78, 'ANTI_FRAUDE', 'Anti Fraude', 'A', 18);
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (79, 'CREDITO', 'Crédito', 'A', 18);
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (80, 'ENDERECOS', 'Endereços', 'A', 18);

INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (124, 'BACKOFFICE_ANALISTA_DE_TRATAMENTO_DE_ENDERECOS', 'Analista de Tratamento de Endereços', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16018, 'Tratar Pendências de Endereços', 'BKO_ANALISTA_TRATAMENTO_ENDERECOS', 24);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 124, 80, 16018);

UPDATE FUNCIONALIDADE SET ROLE = 'BKO_ANALISTA_TRATAMENTO_ANTI_FRAUDE' WHERE ID = 16015;
UPDATE FUNCIONALIDADE SET ROLE = 'BKO_ANALISTA_TRATAMENTO_CREDITO' WHERE ID = 16016;

UPDATE CARGO_DEPART_FUNC SET FK_DEPARTAMENTO = 78 WHERE FK_FUNCIONALIDADE = 16015;
UPDATE CARGO_DEPART_FUNC SET FK_DEPARTAMENTO = 79 WHERE FK_FUNCIONALIDADE = 16016;

UPDATE CARGO SET CODIGO = 'BACKOFFICE_ANALISTA_DE_TRATAMENTO_ANTI_FRAUDE', NOME = 'Analista de Tratamento de Anti Fraude' WHERE ID = 122;
UPDATE CARGO SET CODIGO = 'BACKOFFICE_ANALISTA_DE_TRATAMENTO_DE_CREDITO', NOME = 'Analista de Tratamento de Crédito' WHERE ID = 123;