/*Nivel MSO - Cargo AUDITORIA*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '52', '21', '14000');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '52', '21', '14002');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '52', '21', '14004');

/*Nivel OPERACAO - Cargo SUPERVISOR*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '10', '3', '14000');