-- HIERARQUIA VAREJO --
UPDATE CARGO SET FK_CARGO_SUPERIOR = (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_GERENTE')  WHERE CODIGO = 'VAREJO_COORDENADOR';
UPDATE CARGO SET FK_CARGO_SUPERIOR = (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_COORDENADOR')  WHERE CODIGO = 'VAREJO_SUPERVISOR';
UPDATE CARGO SET FK_CARGO_SUPERIOR = (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_SUPERVISOR')  WHERE CODIGO = 'VAREJO_VENDEDOR';
UPDATE CARGO SET FK_CARGO_SUPERIOR = (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_SUPERVISOR')  WHERE CODIGO = 'VAREJO_VENDEDOR_BACKOFFICE';
UPDATE CARGO SET FK_CARGO_SUPERIOR = (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_SUPERVISOR')  WHERE CODIGO = 'VAREJO_BACKOFFICE';

-- DEPARTAMENTO COMERCIAL VAREJO --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL) VALUES
(SEQ_CARGO_DEPART_FUNC.NEXTVAL, NULL, (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_GERENTE'), (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = 5), 3007, NULL, NULL);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL) VALUES
(SEQ_CARGO_DEPART_FUNC.NEXTVAL, NULL, (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_COORDENADOR'), (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = 5), 3007, NULL, NULL);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL) VALUES
(SEQ_CARGO_DEPART_FUNC.NEXTVAL, NULL, (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_COORDENADOR'), (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'VAREJO' AND FK_NIVEL = 5), 3007, NULL, NULL);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL) VALUES
(SEQ_CARGO_DEPART_FUNC.NEXTVAL, NULL, (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_SUPERVISOR'), (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = 5), 3007, NULL, NULL);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL) VALUES
(SEQ_CARGO_DEPART_FUNC.NEXTVAL, NULL, (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_VENDEDOR'), (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = 5), 3007, NULL, NULL);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL) VALUES
(SEQ_CARGO_DEPART_FUNC.NEXTVAL, NULL, (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_VENDEDOR_BACKOFFICE'), (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = 5), 3007, NULL, NULL);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO, CANAL) VALUES
(SEQ_CARGO_DEPART_FUNC.NEXTVAL, NULL, (SELECT ID FROM CARGO WHERE CODIGO = 'VAREJO_BACKOFFICE'), (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = 5), 3007, NULL, NULL);




