ALTER TABLE USUARIO_AUD ADD FK_ORGANIZACAO_EMPRESA NUMBER(10,0);

ALTER TABLE USUARIO_AUD
    ADD CONSTRAINT "FK_USUARIO_AUD_ORG_EMPRESA" FOREIGN KEY ("FK_ORGANIZACAO_EMPRESA") REFERENCES ORGANIZACAO_EMPRESA ("ID");