-- CRIA PERMISSAO PARA TRABALHAR INDICACOES DO TECNICO VENDEDOR --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16102, 'Trabalhar Indicações do Técnico Vendedor', 'BKO_16102', 24);

-- NIVEL: BACKOFFICE | CARGO: OPERADOR DE TRATAMENTO DE VENDAS | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 115, 69, 16102);

-- NIVEL: BACKOFFICE | CARGO: ANALISTA DE TRATAMENTO DE VENDAS | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 116, 69, 16102);
