-- SOLICITAR RAMAL AGENTE AUTORIZADO --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO, PERMISSAO_TELA)
VALUES (20014, 'Solicitar Ramal AA', 'CTR_20014', 20, NULL);

-- SOLICITAR RAMAL D2D --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO, PERMISSAO_TELA)
VALUES (20015, 'Solicitar Ramal D2D', 'CTR_20015', 20, NULL);

--CARGO XBRAIN -- DEPARTAMENTO ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 50, 20014);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 50, 20015);

--CARGO XBRAIN -- DEPARTAMENTO HELPDESK --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 51, 20014);
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 51, 20015);

-- CARGO MSO ANALISTA -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 20, 21, 20015);

-- CARGO MSO COLSULTOR -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 22, 21, 20015);

-- CARGO OPERAÇÃO ANALISTA -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 1, 3, 20015);

-- CARGO COORDENADOR COLSULTOR -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 3, 20015);

-- CARGO GERENTE OPERAÇÃO -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 3, 20015);

-- AGENTE AUTORIZADO SOCIO PRINCIPAL -- DEPARTAMENTO AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 41, 40, 20014);