-- INATIVAR CARGOS CRIADOS PARA VAREJO

UPDATE CARGO SET SITUACAO = 'I' WHERE CODIGO = 'VAREJO_COORDENADOR';
UPDATE CARGO SET SITUACAO = 'I' WHERE CODIGO = 'VAREJO_BACKOFFICE';
UPDATE CARGO SET SITUACAO = 'I' WHERE CODIGO = 'VAREJO_VENDEDOR_BACKOFFICE';

-- ALTERAR RAZAO_SOCIAL PARA NOME

ALTER TABLE ORGANIZACAO_EMPRESA RENAME COLUMN RAZAO_SOCIAL TO NOME;

