INSERT INTO FUNCIONALIDADE VALUES(3069, 'Visualizar Gráfico Loja Futuro', 'VDS_3069', 3, null);

INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 41, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 42, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 47, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 45, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 48, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 56, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 78, 40, 3069, null, null);