INSERT INTO FUNCIONALIDADE VALUES(3069, 'Visualizar Gráficos Loja Futuro', 'VDS_3069', 3, null);
-- AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 41, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 42, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 47, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 45, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 48, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 56, 40, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 78, 40, 3069, null, null);
-- ADM --
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 50, 50, 3069, null, null);
-- MSO --
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 20, 21, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 21, 21, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 22, 21, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 23, 21, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 24, 21, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 25, 21, 3069, null, null);
INSERT INTO CARGO_DEPART_FUNC VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 52, 21, 3069, null, null);