--- FUNCIONALIDADE ---
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (250, 'Permite acessar SFTP Parceiros Digitais', 'CTR_250_SFTP_PARCEIROS_DIGITAIS', 20);

--- PERMISSÕES ---

-- Nível: X-Brain || Cargo: Administrador || Departamento: Administrador
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, SYSDATE, 50, 50, 250);
