-- CRIA PERMISSAO PARA DESBLOQUEAR INDICACOES DO TECNICO VENDEDOR --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16104, 'Desbloquear Indicações do Técnico Vendedor', 'BKO_16104', 24);

-- NIVEL: BACKOFFICE | CARGO: SUPERVISOR DE TRATAMENTO DE VENDAS | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 117, 69, 16104);

-- NIVEL: BACKOFFICE | CARGO: COORDENADOR DE TRATAMENTO DE VENDAS | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 118, 69, 16104);

-- NIVEL: BACKOFFICE | CARGO: GERENTE DE TRATAMENTO DE VENDAS  | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 119, 69, 16104);

-- NIVEL: MSO | CARGO: CONSULTOR | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 16104);

-- NIVEL: X-BRAIN | CARGO: ADMINISTRADOR | DEPARTAMENTO: ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 16104);
