-- DELETAR CARGOS CRIADOS PARA VAREJO

DELETE FROM CARGO WHERE CODIGO = 'VAREJO_COORDENADOR';
DELETE FROM CARGO WHERE CODIGO = 'VAREJO_BACKOFFICE';
DELETE FROM CARGO WHERE CODIGO = 'VAREJO_VENDEDOR_BACKOFFICE';

-- ALTERAR RAZAO_SOCIAL PARA NOME

ALTER TABLE ORGANIZACAO_EMPRESA RENAME COLUMN RAZAO_SOCIAL TO NOME;

