INSERT INTO CARGO
(ID, CODIGO, NOME, SITUACAO, FK_NIVEL, FK_CARGO_SUPERIOR, QUANTIDADE_SUPERIOR)
VALUES(SEQ_CARGO.nextval, 'VAREJO_COORDENADOR', 'Coordenador', 'A', 5, NULL, 50);

INSERT INTO CARGO
(ID, CODIGO, NOME, SITUACAO, FK_NIVEL, FK_CARGO_SUPERIOR, QUANTIDADE_SUPERIOR)
VALUES(SEQ_CARGO.nextval, 'VAREJO_BACKOFFICE', 'Backoffice', 'A', 5, NULL, 50);

INSERT INTO CARGO
(ID, CODIGO, NOME, SITUACAO, FK_NIVEL, FK_CARGO_SUPERIOR, QUANTIDADE_SUPERIOR)
VALUES(SEQ_CARGO.nextval, 'VAREJO_VENDEDOR_BACKOFFICE', 'Vendedor Backoffice', 'A', 5, NULL, 50);

ALTER TABLE USUARIO ADD FK_ORGANIZACAO_EMPRESA NUMBER(10,0);

ALTER TABLE USUARIO
    ADD CONSTRAINT "FK_USUARIO_ORG_EMPRESA" FOREIGN KEY ("FK_ORGANIZACAO_EMPRESA") REFERENCES ORGANIZACAO_EMPRESA ("ID");

ALTER TABLE ORGANIZACAO_EMPRESA ADD FK_NIVEL NUMBER(10,0);

ALTER TABLE ORGANIZACAO_EMPRESA ADD CONSTRAINT "FK_NIVEL_ORGANIZACAO" FOREIGN KEY ("FK_NIVEL") REFERENCES NIVEL ("ID");

ALTER TABLE ORGANIZACAO_EMPRESA DROP COLUMN FK_NIVEL_EMPRESA;

ALTER TABLE ORGANIZACAO_EMPRESA DROP CONSTRAINT FK_NIVEL_ORGANIZACAO_EMPRESA;

DROP TABLE NIVEL_EMPRESA;
