-- CRIA TABELA DE SUB_CANAIS
CREATE TABLE SUB_CANAL (
  ID INTEGER NOT NULL,
  CODIGO VARCHAR(255) NOT NULL,
  NOME VARCHAR(255) NOT NULL,
  SITUACAO VARCHAR(1) NOT NULL,
  PRIMARY KEY (ID)
);

-- CRIA SEQUENCE PARA IDS DE SUB_CANAL
CREATE SEQUENCE SEQ_SUB_CANAL START WITH 1 INCREMENT BY 1;

-- INSERE SUB_CANAIS
INSERT INTO SUB_CANAL (ID, CODIGO, NOME, SITUACAO) VALUES (SEQ_SUB_CANAL.nextval, 'PAP', 'PAP', 'A');
INSERT INTO SUB_CANAL (ID, CODIGO, NOME, SITUACAO) VALUES (SEQ_SUB_CANAL.nextval, 'PAP_PME', 'PAP PME', 'A');
INSERT INTO SUB_CANAL (ID, CODIGO, NOME, SITUACAO) VALUES (SEQ_SUB_CANAL.nextval, 'PAP_PREMIUM', 'PAP PREMIUM', 'A');
INSERT INTO SUB_CANAL (ID, CODIGO, NOME, SITUACAO) VALUES (SEQ_SUB_CANAL.nextval, 'INSIDE_SALES_PME', 'INSIDE SALES PME', 'A');