-- CRIA TABELA RELACIONAL PARA USUARIO E SUBCANAL
CREATE TABLE USUARIO_SUBCANAL (
    FK_USUARIO INT NOT NULL,
    FK_SUBCANAL INT NOT NULL,
    CONSTRAINT PK_USUARIO_SUBCANAL PRIMARY KEY (FK_USUARIO, FK_SUBCANAL),
    CONSTRAINT FK_USUARIO_SUBCANAL_USUARIO FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO,
    CONSTRAINT FK_USUARIO_SUBCANAL_SUBCANAL FOREIGN KEY (FK_SUBCANAL) REFERENCES SUB_CANAL
);

-- INSERE REGISTROS DE USUARIOS COM APENAS UM SUBCANAL
BEGIN
    FOR USR IN (SELECT ID, TIPO_CANAL FROM USUARIO WHERE TIPO_CANAL IS NOT NULL) LOOP
        INSERT INTO USUARIO_SUBCANAL (FK_USUARIO, FK_SUBCANAL)
        VALUES (USR.ID, (SELECT ID FROM SUB_CANAL WHERE CODIGO = USR.TIPO_CANAL));
    END LOOP;
END;