INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (8, 'TELEMATICA', 'TEL Telemática');

INSERT INTO ORGANIZACAO_NIVEL (FK_NIVEL, FK_ORGANIZACAO) VALUES ((SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'), 8);

-- CARGOS
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (115, 'BACKOFFICE_OPERADOR_TRATAMENTO_VENDAS', 'Operador de Tratamento de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (116, 'BACKOFFICE_SUPERVISOR_TRATAMENTO_VENDAS', 'Supervisor de Tratamento de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (117, 'BACKOFFICE_COORDENADOR_TRATAMENTO_VENDAS', 'Coordenador de Tratamento de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (118, 'BACKOFFICE_GERENTE_TRATAMENTO_VENDAS', 'Gerente de Tratamento de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));

-- FUNCIONALIDADE: VISUALIZAR E DETALHAR INDICACOES DO TECNICO VENDEDOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 115, 69, 16101);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 116, 69, 16101);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 117, 69, 16101);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 118, 69, 16101);
