INSERT INTO ORGANIZACAO(ID, CODIGO, NOME) VALUES (9, 'CLARO', 'Claro');
INSERT INTO ORGANIZACAO_NIVEL(FK_NIVEL, FK_ORGANIZACAO) VALUES ((SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'), 9);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (122, 'BACKOFFICE_ANALISTA_ANTI_FRAUDE', 'Analista Anti Fraude', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (123, 'BACKOFFICE_ANALISTA_DE_CREDITO', 'Analista de Crédito', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
