    ALTER TABLE ORGANIZACAO_EMPRESA ADD DATA_CADASTRO TIMESTAMP NOT NULL;
    ALTER TABLE ORGANIZACAO_EMPRESA ADD FK_USUARIO_CADASTRO INTEGER NOT NULL;
    ALTER TABLE ORGANIZACAO_EMPRESA
        ADD CONSTRAINT FK_USUARIO_CADASTRO_ORG FOREIGN KEY (FK_USUARIO_CADASTRO) REFERENCES USUARIO;