CREATE SEQUENCE SEQ_ORGANIZACAO_EMPRESA_HIST START WITH 1 INCREMENT BY 1;

CREATE TABLE ORGANIZACAO_EMPRESA_HIST(
    ID INTEGER NOT NULL,
    SITUACAO VARCHAR(255) NOT NULL,
    OBSERVACAO VARCHAR(255) NOT NULL,
    FK_ORGANIZACAO_EMPRESA INTEGER NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    USUARIO_ID INTEGER NOT NULL,
    USUARIO_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORG_EMP_HIST FOREIGN KEY (FK_ORGANIZACAO_EMPRESA) REFERENCES ORGANIZACAO_EMPRESA
);