-- PERMISSÃO POL_GERENCIAR_EQUIPE_VENDA - DIRETOR OPERACAO AA

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, sysdate, 6, 3, 5);