-- Cria aplicação loja futuro --
INSERT INTO APLICACAO (ID, CODIGO, NOME) VALUES (28, 'LJF', 'LOJA FUTURO');

-- Permissão criar --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (3067, 'Cadastrar Pré Venda Loja Futuro', 'VDS_3067', 28);
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (3067, 'AGENTE_AUTORIZADO');

-- Cliente e assistente loja futuro --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 201, 40, 3067);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 202, 40, 3067);

-- Permissão Listar --
-- Assistente loja futuro --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 202, 40, 3066);