-- SOLICITAR RAMAL

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 42, 40, 20014, 1);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 45, 40, 20014, 1);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 47, 40, 20014, 1);
