-- INCLUI SUBCANAL PARA USUARIOS DO CANAL D2D SEM O TIPO CANAL CADASTRADO
-- USUARIOS COM EMAIL NET.COM.BR E CLARO.COM.BR, SUBCANAL PAP PREMIUM
BEGIN
    FOR USR IN (
        SELECT ID
        FROM USUARIO
        WHERE TIPO_CANAL IS NULL AND
            REGEXP_LIKE(EMAIL_01, '@(CLARO|NET).COM.BR') AND
            ID IN (
                SELECT FK_USUARIO
                FROM USUARIO_CANAL
                WHERE CANAL = 'D2D_PROPRIO') AND
            ID NOT IN (SELECT FK_USUARIO FROM USUARIO_SUBCANAL))
    LOOP
        INSERT INTO USUARIO_SUBCANAL (FK_USUARIO, FK_SUBCANAL) VALUES (USR.ID, 3);
    END LOOP;
END;
/
-- USUARIO COM OUTROS EMAILS, SUBCANAL PAP
BEGIN
    FOR USR IN (
        SELECT ID
        FROM USUARIO
        WHERE TIPO_CANAL IS NULL AND
            NOT(REGEXP_LIKE(EMAIL_01, '@(CLARO|NET).COM.BR')) AND
            ID IN (
                SELECT FK_USUARIO
                FROM USUARIO_CANAL
                WHERE CANAL = 'D2D_PROPRIO') AND
            ID NOT IN (SELECT FK_USUARIO FROM USUARIO_SUBCANAL))
    LOOP
        INSERT INTO USUARIO_SUBCANAL (FK_USUARIO, FK_SUBCANAL) VALUES (USR.ID, 1);
    END LOOP;
END;
/