INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (121, 'TECNICO_TERCEIRO', 'Técnico Terceiro', 'A', 3);
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (70, 'TECNICO', 'Técnico', 'A', 3);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16103, 'Criar Indicação Técnico', 'BKO_CRIAR_INDICACAO_TECNICO', 24);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 121, 70, 16103);