UPDATE FUNCIONALIDADE SET ROLE = 'VAR_GERENCIAR_ORGANIZACOES' WHERE ID = 6004;
UPDATE FUNCIONALIDADE SET NOME = 'Gerenciar Organizaçoes' WHERE ID = 6004;

--MSO
INSERT INTO CARGO_DEPART_FUNC (ID,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22,20,6004);
INSERT INTO CARGO_DEPART_FUNC (ID,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22,21,6004);
INSERT INTO CARGO_DEPART_FUNC (ID,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22,25,6004);
INSERT INTO CARGO_DEPART_FUNC (ID,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22,28,6004);
INSERT INTO CARGO_DEPART_FUNC (ID,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22,29,6004);
INSERT INTO CARGO_DEPART_FUNC (ID,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22,30,6004);
INSERT INTO CARGO_DEPART_FUNC (ID,FK_CARGO,FK_DEPARTAMENTO,FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval,22,31,6004);
