Insert into FUNCIONALIDADE (ID,NOME,ROLE,FK_APLICACAO) values ('14004','Visualizar chamados em geral','CHM_VISUALIZAR_CHAMADO_GERAL','15');


/*Nivel MSO - 14004(VISUALIZAR CHAMADO GERAL)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '20', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '21', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '22', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '23', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '24', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '25', '21', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '52', '21', '14004');

/*Nivel XBRAIN - 14004(VISUALIZAR CHAMADO GERAL)*/
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '50', '50', '14004');
insert into CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) values (SEQ_CARGO_DEPART_FUNC.nextval, '51', '50', '14004');
