-- SOLICITAR RAMAL

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 1, 3, 2033, 1);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 4, 3, 2033, 1);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 7, 3, 2033, 1);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 20, 3, 2033, 1);

INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, FK_USUARIO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 22, 3, 2033, 1);