CREATE SEQUENCE SEQ_ORGANIZACAO_EMPRESA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NIVEL_EMPRESA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MODALIDADE_EMPRESA START WITH 1 INCREMENT BY 1;

CREATE TABLE NIVEL_EMPRESA(
    ID INTEGER NOT NULL,
    NIVEL_EMPRESA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZACAO_EMPRESA(
    ID INTEGER NOT NULL,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    FK_NIVEL_EMPRESA INTEGER NOT NULL,
    SITUACAO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ORG_NIVEL_EMPRESA FOREIGN KEY (FK_NIVEL_EMPRESA) REFERENCES NIVEL_EMPRESA
);

CREATE TABLE MODALIDADE_EMPRESA(
    ID INTEGER NOT NULL,
    MODALIDADE_EMPRESA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZACAO_MODALIDADE_EMPRESA(

    FK_ORGANIZACAO_EMPRESA INTEGER NOT NULL,
    FK_MODALIDADE_EMPRESA INTEGER NOT NULL,
    CONSTRAINT FK_ORG_MOD_MOD_EMPRESA FOREIGN KEY (FK_ORGANIZACAO_EMPRESA) REFERENCES ORGANIZACAO_EMPRESA,
    CONSTRAINT FK_ORG_MOD_ORG_EMPRESA FOREIGN KEY (FK_MODALIDADE_EMPRESA) REFERENCES MODALIDADE_EMPRESA
);

INSERT INTO NIVEL_EMPRESA (ID, NIVEL_EMPRESA) VALUES (SEQ_NIVEL_EMPRESA.nextval, 'VAREJO');
INSERT INTO NIVEL_EMPRESA (ID, NIVEL_EMPRESA) VALUES (SEQ_NIVEL_EMPRESA.nextval, 'RECEPTIVO');

INSERT INTO MODALIDADE_EMPRESA (ID, MODALIDADE_EMPRESA) VALUES (SEQ_MODALIDADE_EMPRESA.nextval, 'PAP');
INSERT INTO MODALIDADE_EMPRESA (ID, MODALIDADE_EMPRESA) VALUES (SEQ_MODALIDADE_EMPRESA.nextval, 'TELEVENDAS');
