-- CRIA PERMISSAO PARA VISUALIZAR E DETALHAR INDICACOES DO TECNICO VENDEDOR --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16101, 'Acompanhamento de Indicações do Técnico Vendedor', 'BKO_16101', 24);

-- NIVEL: X-BRAIN | CARGO: ADMINISTRADOR | DEPARTAMENTO: ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 16101);

-- NIVEL: MSO | CARGO: CONSULTOR | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 16101);
