UPDATE DEPARTAMENTO SET CODIGO = 'ADMINISTRATIVO' WHERE ID = 1;
UPDATE DEPARTAMENTO SET CODIGO = 'ADMINISTRATIVO' WHERE ID = 20;

UPDATE DEPARTAMENTO SET CODIGO = 'AUDITORIA' WHERE ID = 53;

UPDATE DEPARTAMENTO SET CODIGO = 'COMUNICACAO' WHERE ID = 4;
UPDATE DEPARTAMENTO SET CODIGO = 'COMUNICACAO' WHERE ID = 22;

UPDATE DEPARTAMENTO SET CODIGO = 'ENDOMARKETING' WHERE ID = 5;
UPDATE DEPARTAMENTO SET CODIGO = 'ENDOMARKETING' WHERE ID = 23;

UPDATE DEPARTAMENTO SET CODIGO = 'FINANCEIRO' WHERE ID = 31;

UPDATE DEPARTAMENTO SET CODIGO = 'MARKETING' WHERE ID = 6;
UPDATE DEPARTAMENTO SET CODIGO = 'MARKETING' WHERE ID = 24;

UPDATE DEPARTAMENTO SET CODIGO = 'PLANEJAMENTO_COMERCIAL' WHERE ID = 7;
UPDATE DEPARTAMENTO SET CODIGO = 'PLANEJAMENTO_COMERCIAL' WHERE ID = 25;

UPDATE DEPARTAMENTO SET CODIGO = 'PROCESSOS_COMERCIAL' WHERE ID = 8;
UPDATE DEPARTAMENTO SET CODIGO = 'PROCESSOS_COMERCIAL' WHERE ID = 26;

UPDATE DEPARTAMENTO SET CODIGO = 'PROJETOS' WHERE ID = 9;
UPDATE DEPARTAMENTO SET CODIGO = 'PROJETOS' WHERE ID = 27;

UPDATE DEPARTAMENTO SET CODIGO = 'SUPORTE_COMERCIAL' WHERE ID = 10;
UPDATE DEPARTAMENTO SET CODIGO = 'SUPORTE_COMERCIAL' WHERE ID = 28;

UPDATE DEPARTAMENTO SET CODIGO = 'TRADE_MARKETING' WHERE ID = 11;
UPDATE DEPARTAMENTO SET CODIGO = 'TRADE_MARKETING' WHERE ID = 29;