--CRIA FUNCIONALIDADE PARA IMPORTAR ARQUIVO CALCULADORA PHY NO SIMULADOR-PRODUTO-API
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (4003, 'Importar calculadora phy simulador', 'SPR_4003', 5);

--ADICIONA FUNCIONALIDADE Importar calculadora phy simulador PARA O CARGO USUARIO ADMIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 4003);
