INSERT INTO ORGANIZACAO (ID, CODIGO, NOME) VALUES (9, 'CLARO', 'Claro');

INSERT INTO ORGANIZACAO_NIVEL (FK_NIVEL, FK_ORGANIZACAO) VALUES ((SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'), 9);

INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (122, 'BACKOFFICE_ANALISTA_DE_TRATAMENTO_ANTI_FRAUDE', 'Analista de Tratamento de Anti Fraude', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (123, 'BACKOFFICE_ANALISTA_DE_TRATAMENTO_DE_CREDITO', 'Analista de Tratamento de Crédito', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (124, 'BACKOFFICE_ANALISTA_DE_TRATAMENTO_DE_ENDERECOS', 'Analista de Tratamento de Endereços', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16015, 'Tratar Pendências de Anti-Fraude', 'BKO_ANALISTA_TRATAMENTO_ANTI_FRAUDE', 24);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16016, 'Tratar Pendências de Crédito', 'BKO_ANALISTA_TRATAMENTO_CREDITO', 24);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16018, 'Tratar Pendências de Endereços', 'BKO_ANALISTA_TRATAMENTO_ENDERECOS', 24);

INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (78, 'ANTI_FRAUDE', 'Anti Fraude', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (79, 'CREDITO', 'Crédito', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (80, 'ENDERECOS', 'Endereços', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE'));

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 122, 78, 16015);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 123, 79, 16016);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 124, 80, 16018);