-- CRIA PERMISSAO PARA GERENCIAR LAYOUT MASSIVO DE MAILING --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20013, 'Gerenciar Layout Massivo de Mailing', 'CTR_GERENCIAR_LAYOUT_MASSIVO_MAILING', 20);

-- NIVEL: X-BRAIN | CARGO: ADMINISTRADOR | DEPARTAMENTO: ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20013);

-- NIVEL: MSO | CARGO: CONSULTOR | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 20013);

-- NIVEL: OPERACAO | CARGOS: GERENTE, COORDENADOR E EXECUTIVO | DEPARTAMENTO: COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 7, 3, 20013);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 20013);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 5, 3, 20013);