-- Adiciona funcionalidade 'Gerenciar Equipe Técnica' para o cargo de Supervisor da equipe tecnica.
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SUPERVISOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 6);