--ADICIONA PERMISSOES
--Detalhar Tratativa = 16004
--Trabalhar tratativas pendentes de análise externa = 16006
--PARA OS CARGOS E DEPARTAMENTOS

--CARGO: BACKOFFICE_ANALISTA_DE_TRATAMENTO_DE_ANTI_FRAUDE - DEPARTAMENTO: ANTIFRAUDE
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 122, 78, 16004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 122, 78, 16006);

--CARGO: BACKOFFICE_ANALISTA_DE_TRATAMENTO_DE_CREDITO - DEPARTAMENTO: CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 123, 79, 16004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 123, 79, 16006);

--CARGO: BACKOFFICE_ANALISTA_DE_TRATAMENTO_DE_ENDERECOS - DEPARTAMENTO: ENDERECOS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 124, 80, 16004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 124, 80, 16006);
