--- FUNCIONALIDADE ---
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16106, 'Gerenciar Tratativas do Técnico Vendedor', 'BKO_16106', 24);

-- ANALISTA TRATAMENTO VENDAS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 116,
(SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')),
16106);
