-- FUNCIONALIDADE --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
                    VALUES (16017, 'Gerenciar Cadastro de Mensagens', 'BKO_16017', 24);
-- PERMISSÕES --
--- Administrador ---
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
                       VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 16017);
--- MSO Consultor ---
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
                       VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 16017);