CREATE SEQUENCE SEQ_IMPORTACAO_FERIADO START WITH 1 INCREMENT BY 1;
CREATE TABLE IMPORTACAO_FERIADO
(
 ID                        INTEGER NOT NULL,
 DATA_CADASTRO             TIMESTAMP NOT NULL,
 SITUACAO                  VARCHAR(80) NOT NULL,
 USUARIO_CADASTRO_ID       INTEGER,
 USUARIO_CADASTRO_NOME     VARCHAR (255),
 PRIMARY KEY (ID)
);

ALTER TABLE FERIADO ADD FK_IMPORTACAO INTEGER;
ALTER TABLE FERIADO ADD CONSTRAINT FK_FERIADO_IMPORTACAO
    FOREIGN KEY (FK_IMPORTACAO) REFERENCES IMPORTACAO_FERIADO;