--GERENTE SUPERIOR DO SUPERVISOR.
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR)
SELECT
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'),
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE')
FROM DUAL;

--SUPERVISOR SUPERIOR DO COORDENADOR.
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR)
SELECT
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'),
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR')
FROM DUAL;

--COORDENADOR SUPERIOR DO VENDEDOR.
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR)
SELECT
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_VENDEDOR'),
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR')
FROM DUAL;

--COORDENADOR SUPERIOR DO BACKOFFICE.
INSERT INTO CARGO_SUPERIOR (FK_CARGO, FK_CARGO_SUPERIOR)
SELECT
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_BACKOFFICE'),
    (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR')
FROM DUAL;


----INSERT FK_SUPERIOR TABELA CARGO

UPDATE CARGO
SET FK_CARGO_SUPERIOR = (
    SELECT ID
    FROM CARGO
    WHERE CODIGO = 'INTERNET_GERENTE'
)
WHERE CODIGO = 'INTERNET_SUPERVISOR';

UPDATE CARGO
SET FK_CARGO_SUPERIOR = (
    SELECT ID
    FROM CARGO
    WHERE CODIGO = 'INTERNET_SUPERVISOR'
)
WHERE CODIGO = 'INTERNET_COORDENADOR';

UPDATE CARGO
SET FK_CARGO_SUPERIOR = (
    SELECT ID
    FROM CARGO
    WHERE CODIGO = 'INTERNET_COORDENADOR'
)
WHERE CODIGO = 'INTERNET_VENDEDOR';

UPDATE CARGO
SET FK_CARGO_SUPERIOR = (
    SELECT ID
    FROM CARGO
    WHERE CODIGO = 'INTERNET_COORDENADOR'
)
WHERE CODIGO = 'INTERNET_BACKOFFICE';