INSERT INTO NIVEL (ID, CODIGO, EXIBIR_CAD_USUARIO, NOME, SITUACAO) VALUES (SEQ_NIVEL.nextval, 'BACKOFFICE_CENTRALIZADO', 'V', 'Backoffice Centralizado', 'A');

INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_DEPARTAMENTO.nextval, 'COMERCIAL', 'Comercial', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO'));

UPDATE ORGANIZACAO_EMPRESA SET FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO') WHERE RAZAO_SOCIAL = 'TEL TELEMÁTICA';

UPDATE CARGO SET FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO') WHERE ID IN (115, 116, 117, 118, 119);

UPDATE CARGO_DEPART_FUNC SET FK_DEPARTAMENTO = (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')) WHERE FK_CARGO IN (115, 116, 117, 118, 119);