CREATE SEQUENCE SEQ_USUARIO_SENHA_INC START WITH 1 INCREMENT BY 1;

CREATE TABLE USUARIO_HIST_LOGIN_SENHA (
    ID INTEGER NOT NULL PRIMARY KEY,
    DATA_TENTATIVA DATE NOT NULL,
    FK_USUARIO INTEGER NOT NULL,
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO (ID)
);