-- CARGO ASSISTENTE OPERACAO -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 2, 3, 20015);

-- CARGO SUPERVISOR OPERACAO -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 10, 3, 20015);

-- CARGO DIRETOR OPERACAO -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 6, 3, 20015);