-- FUNCIONALIDADE: ADICIONAR NOVOS USUARIOS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 20010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 20010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 20010);

-- CRIA PERMISSAO/FUNCIONALIDADE VISUALIZAR CARTEIRA/HIERARQUIA CANAL INTERNET--
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20050, 'Visualizar Carteira/Hierarquia Canal Internet', 'AUT_20050', 1);

-- FUNCIONALIDADE: VISUALIZAR CARTEIRA/HIERARQUIA CANAL INTERNET --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 20050);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 20050);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 20050);