UPDATE ORGANIZACAO_NIVEL SET FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')
WHERE FK_ORGANIZACAO = (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'TELEMATICA')
AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE');

UPDATE USUARIO
SET FK_ORGANIZACAO = (SELECT ID FROM ORGANIZACAO WHERE CODIGO = 'TELEMATICA')
WHERE FK_CARGO in (115, 116, 117, 118, 119)
AND FK_DEPARTAMENTO = (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL'
    AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO'));