UPDATE USUARIO
SET FK_DEPARTAMENTO = (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO'))
WHERE FK_DEPARTAMENTO = 69 and FK_CARGO in (115, 116, 117, 118, 119);