-- Cria usuario de Integração para o App Tecnico Nota 10 --
INSERT INTO USUARIO
    (
        ID,
        ALTERAR_SENHA,
        DATA_CADASTRO,
        EMAIL_01,
        NASCIMENTO,
        NOME,
        SENHA,
        SITUACAO,
        FK_CARGO,
        FK_DEPARTAMENTO,
        RECUPERAR_SENHA_TENTATIVA
    )
    VALUES
    (
        SEQ_USUARIO.NEXTVAL,
        'F',
        CURRENT_DATE,
        'INTEGRACAOAPPTECNICONOTA10@XBRAIN.COM.BR',
        CURRENT_DATE,
        'INTEGRAÇÃO APP TÉCNICO NOTA 10',
        '$2a$10$Df7LabgBcSGfKG.DayB3quo.kASSLx.rKjb3aB8fPtuMg1N7zzhCy',
        'A',
        (SELECT ID FROM CARGO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO = 'A'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO ='A'),
        0
    );

INSERT INTO USUARIO_UNIDADE_NEGOCIO (FK_USUARIO, FK_UNIDADE_NEGOCIO)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOAPPTECNICONOTA10@XBRAIN.COM.BR'), 3);

INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOAPPTECNICONOTA10@XBRAIN.COM.BR'), 4);

-- Cria funcionalidade --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (7012, 'Cadastrar indicacoes do tecnico vendedor pelo App Nota 10', 'INT_7012', 8);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 7012);

-- Adiciona permissão especial para o usuario de INTEGRACAO --
INSERT INTO PERMISSAO_ESPECIAL
    (
        ID,
        DATA_CADASTRO,
        FK_FUNCIONALIDADE,
        FK_USUARIO,
        FK_USUARIO_CADASTRO
    )
VALUES
    (
        SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        7012,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOAPPTECNICONOTA10@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'GABRIELMOTTA@XBRAIN.COM.BR')
    )