-- REMOVE PERMISSAO DO CARGO MSO CONSULTOR E DEPARTAMENTO COMERCIAL INCORRETO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 22 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 20024;

-- ADICIONA PERMISSAO DE VISUALIZAR STATUS DO HORARIO DE ACESSO AO MSO CONSULTOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 20024);
