-- FUNCIONALIDADE: VISUALIZAR ATUALIZAR SITUAÇÃO DO USUARIO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 2010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 2010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 2010);

-- FUNCIONALIDADE: VISUALIZAR MENU QUALIDADE --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 21010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 21010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 21010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_BACKOFFICE'), 3, 21010);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_VENDEDOR'), 3, 21010);