INSERT INTO NIVEL(ID, CODIGO, EXIBIR_CAD_USUARIO, NOME, SITUACAO) VALUES(19, 'BACKOFFICE_CENTRALIZADO', 'V', 'Backoffice Centralizado', 'A');

INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (71, 'COMERCIAL', 'Comercial', 'A', 19);

UPDATE ORGANIZACAO_EMPRESA SET FK_NIVEL = 19 WHERE ID = 8;

UPDATE CARGO SET FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO') WHERE ID IN (115, 116, 117, 118, 119);

UPDATE CARGO_DEPART_FUNC SET FK_DEPARTAMENTO = 71 WHERE FK_CARGO IN (115, 116, 117, 118, 119) AND FK_DEPARTAMENTO = 69;