-- CRIA NIVEL DE QUALIDADE --
INSERT INTO NIVEL (ID, CODIGO, EXIBIR_CAD_USUARIO, NOME, SITUACAO) VALUES (SEQ_NIVEL.nextval, 'BACKOFFICE_QUALIDADE', 'V', 'Backoffice Qualidade', 'A');

-- CRIA DEPARTAMENTO NOVO NIVEL DE QUALIDADE --
INSERT INTO DEPARTAMENTO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (1042, 'COMERCIAL', 'Comercial', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_QUALIDADE'));

-- CRIA CARGOS NOVO NIVEL DE QUALIDADE --
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'BACKOFFICE_ANALISTA_QUALIDADE', 'Analista de Qualidade de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_QUALIDADE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'BACKOFFICE_SUPERVISOR_QUALIDADE', 'Supervisor de Qualidade de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_QUALIDADE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'BACKOFFICE_COORDENADOR_QUALIDADE', 'Coordenador de Qualidade de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_QUALIDADE'));
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'BACKOFFICE_GERENTE_QUALIDADE', 'Gerente de Qualidade de Vendas', 'A', (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_QUALIDADE'));

-- CRIA PERMISSAO/FUNCIONALIDADE PARA VISUALIZAR E DETALHAR VENDAS DO PARCEIRO OFENSOR --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (21007, 'Acompanhamento de Vendas do Parceiro Ofensor', 'BKO_21007', 24);

-- CRIA PERMISSAO/FUNCIONALIDADE PARA TRATAR VENDAS DO PARCEIRO OFENSOR --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (21008, 'Tratamento de Vendas do Parceiro Ofensor', 'BKO_21008', 24);

-- NIVEL: X-BRAIN | CARGO: ADMINISTRADOR | DEPARTAMENTO: ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 21007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 21008);

-- FUNCIONALIDADE: ACOMPANHAMENTO DE VENDAS DO PARCEIRO OFENSOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'BACKOFFICE_ANALISTA_QUALIDADE'), 1042, 21007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'BACKOFFICE_SUPERVISOR_QUALIDADE'), 1042, 21007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'BACKOFFICE_COORDENADOR_QUALIDADE'), 1042, 21007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'BACKOFFICE_GERENTE_QUALIDADE'), 1042, 21007);

-- FUNCIONALIDADE: TRATAMENTO DE VENDAS DO PARCEIRO OFENSOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'BACKOFFICE_ANALISTA_QUALIDADE'), 1042, 21008);
