-- SOCIO PRINCIPAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
(SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_SOCIO' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'AGENTE_AUTORIZADO')),
(SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'AGENTE_AUTORIZADO' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'AGENTE_AUTORIZADO')),
(SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'BKO_16107'));

-- SOCIO SECUNDARIO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
(SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_SOCIO_SECUNDARIO' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'AGENTE_AUTORIZADO')),
(SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'AGENTE_AUTORIZADO' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'AGENTE_AUTORIZADO')),
(SELECT ID FROM FUNCIONALIDADE WHERE ROLE = 'BKO_16107'));