--- FUNCIONALIDADE ---

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (18003, 'Gerenciar Motivo de Análise', 'CTR_18003', 22);

--- PERMISSÕES ---

-- X-Brain | Cargo: Administrador | Departamento: Administrador --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 18003);

-- MSO | Cargo: Consultor | Departamento: Comercial --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 18003);
