--CRIA PERMISSAO PARA VISUALIZAR CALCULADORA PHY NO SIMULADOR-PRODUTO
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (4002, 'Visualizar calculadora phy simulador', 'SPR_4002', 5);

--NIVEL: AGENTE_AUTORIZADO_TECNICO_VENDEDOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_VENDEDOR'),
       (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 4002);

--NIVEL: AGENTE_AUTORIZADO_TECNICO_SUPERVISOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SUPERVISOR'),
       (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 4002);

--NIVEL: AGENTE_AUTORIZADO_TECNICO_COORDENADOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_COORDENADOR'),
       (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 4002);

--NIVEL: AGENTE_AUTORIZADO_TECNICO_GERENTE
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_GERENTE'),
       (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 4002);
