INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16110, 'Visualizar Acompanhamento de Indicações Técnico Pendentes', 'BKO_VISUALIZAR_INDICACOES_PENDENTES', 24);

-- ADD FUNCIONALIDADE NO CARGO XBRAIN -- DEPARTAMENTO ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 50, 16110);

-- ADD FUNCIONALIDADE NO CARGO TECNICO SUPERVISOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_VENDEDOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 16110);

-- ADD FUNCIONALIDADE NO CARGO TECNICO SUPERVISOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SUPERVISOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 16110);

-- ADD FUNCIONALIDADE NO CARGO TECNICO COORDENADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_COORDENADOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 16110);

-- ADD FUNCIONALIDADE NO CARGO TECNICO GERENTE --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_GERENTE'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 16110);
