-- Adiciona funcionalidade 'Gerenciar Equipe Técnica' para os cargos de gerencia e coordenacao da equipe tecnica.
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_COORDENADOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 6);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_GERENTE'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'), 6);
