-- CRIA PERMISSAO PARA TABULAR HP TECNICO INDICADOR
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (253, 'Tabular Indicações do Técnico indicador', 'POL_TABULAR_TECNICO_INDICADOR', 2);

-- ADICIONAR PERMISSAO AO ADMINISTRADOR (XBRAIN)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE, DATA_CADASTRO)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 253, SYSDATE);
