INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (20016, 'Importar Script e Checklist de Vendas', 'CTR_20016', 3);

--CARGO XBRAIN -- DEPARTAMENTO ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 50, 20016);

--CARGO XBRAIN -- DEPARTAMENTO HELPDESK --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 51, 20016);

-- CARGO MSO COLSULTOR -- DEPARTAMENTO COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 22, 21, 20016);