-- CRIA PERMISSAO PARA GERENCIAR WORKFLOW BKO
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16108, 'Gerenciar Workflow', 'BKO_16108', 24);

-- NIVEL: X-BRAIN | CARGO: ADMINISTRADOR | DEPARTAMENTO: ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 16108);
