-- CRIA CARGOS NOVO NIVEL DE QUALIDADE --
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'INTERNET_GERENTE', 'Gerente Internet', 'A', 1);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'INTERNET_SUPERVISOR', 'Supervisor Internet', 'A', 1);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'INTERNET_COORDENADOR', 'Coordenador Internet', 'A', 1);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'INTERNET_BACKOFFICE', 'Backoffice Internet', 'A', 1);
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'INTERNET_VENDEDOR', 'Vendedor Internet', 'A', 1);

--CRIAR CARGO_CANAL
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'INTERNET' FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE';
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'INTERNET' FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR';
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'INTERNET' FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR';
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'INTERNET' FROM CARGO WHERE CODIGO = 'INTERNET_BACKOFFICE';
INSERT INTO CARGO_CANAL (FK_CARGO, CANAL) SELECT ID, 'INTERNET' FROM CARGO WHERE CODIGO = 'INTERNET_VENDEDOR';


--GERENTE INTERNET
-- FUNCIONALIDADE: VISUALIZAR TODOS OS PROTOCOLOS ABERTOS POR TODAS AS ORGANIZACOES NO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 3051);
-- FUNCIONALIDADE: CRIAR PROTOCOLOS PARA TODAS ORGANIZACOES NO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 3052);
-- FUNCIONALIDADE: CRIAR NOVOS USUARIOS DENTRO DO SEU NIVEL E CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 2001);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE ENDERECO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 3003);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_GERENTE'), 3, 3014);

--SUPERVISOR INTERNET
-- FUNCIONALIDADE: VISUALIZAR PROTOCOLOS DA SUA ORGANIZACAO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 3051);
-- FUNCIONALIDADE: ABRIR PROTOCOLOS PARA SUA ORGANIZACOES NO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 3052);
-- FUNCIONALIDADE: CRIAR NOVOS USUARIOS DENTRO DO SEU NIVEL E CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 2001);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE ENDERECO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 3003);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_SUPERVISOR'), 3, 3014);

--COORDENADOR INTERNET
-- FUNCIONALIDADE: VISUALIZAR PROTOCOLOS DA SUA ORGANIZACAO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 3051);
-- FUNCIONALIDADE: ABRIR PROTOCOLOS PARA SUA ORGANIZACOES NO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 3052);
-- FUNCIONALIDADE: CRIAR NOVOS USUARIOS DENTRO DO SEU NIVEL E CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 2001);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE ENDERECO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 3003);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_COORDENADOR'), 3, 3014);

--BACKOFFICE INTERNET
-- FUNCIONALIDADE: VISUALIZAR PROTOCOLOS DA SUA ORGANIZACAO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_BACKOFFICE'), 3, 3051);
-- FUNCIONALIDADE: ABRIR PROTOCOLOS PARA SUA ORGANIZACAO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_BACKOFFICE'), 3, 3052);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE ENDERECO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_BACKOFFICE'), 3, 3003);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_BACKOFFICE'), 3, 3014);

--VENDEDOR INTERNET
-- FUNCIONALIDADE: VISUALIZAR PROTOCOLOS DA SUA ORGANIZACAO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_VENDEDOR'), 3, 3051);
-- FUNCIONALIDADE: ABRIR PROTOCOLOS PARA SUA ORGANIZACAO CANAL INTERNET
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_VENDEDOR'), 3, 3052);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE ENDERECO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_VENDEDOR'), 3, 3003);
-- FUNCIONALIDADE: VISUALIZAR VIABILIDADE CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'INTERNET_VENDEDOR'), 3, 3014);