-- REMOVE PERMISSOES DOS SOCIOS PRINCIPAIS E SECUNDARIOS
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 20018 AND FK_CARGO = 41;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 20018 AND FK_CARGO = 42;