INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (21010, 'Visualizar Menu Qualidade', 'VDS_21010', 3);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
SELECT SEQ_CARGO_DEPART_FUNC.nextval, FK_CARGO, FK_DEPARTAMENTO, 21010
FROM (
    SELECT DISTINCT FK_CARGO, FK_DEPARTAMENTO
    FROM CARGO_DEPART_FUNC
    WHERE FK_CARGO <> 201
);