--CRIA FUNCIONALIDADE PARA NOVO CANAL MSO MODULO CONTROLE
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (2059, 'Visualizar ramais canal Mso', 'CTR_VISUALIZAR_RAMAIS_CANAL_MSO', 20);
VALUES (2060, 'Gerenciar configuracao ramal Mso', 'CTR_GERENCIAR_CONFIGURACAO_MSO', 20);

--ADICIONA FUNCIONALIDADE Visualizar e Gerenciar ramais canal Mso PARA OS CARGOS MSO CONSULTOR E ANALISTA
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 2059);
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 20, 21, 2059);
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 2060);
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 20, 21, 2060);
--ADICIONA FUNCIONALIDADE Selecionar Ramais na Modal PARA OS CARGOS MSO CONSULTOR E ANALISTA
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 20, 21, 3029);
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 3029);

