-- Adiciona a nova funcionalidade de 'Criar Correção de Vendas pelo Técnico'
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (16111, 'Criar Correção de Vendas pelo Técnico', 'BKO_16111', 24);

-- Adiciona a funcionalidade 'Criar Correção de Vendas pelo Técnico' para os novos cargos.

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SUPERVISOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16111);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_COORDENADOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16111);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_GERENTE'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16111);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_VENDEDOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16111);
