-- CRIA PERMISSAO PARA LAYOUT
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (20019, 'Gerenciar Layout de Alarme', 'FDR_20019', 23);
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (20020, 'Vizualizar Layout de Alarme', 'FDR_20020', 23);

-- ADICIONA PERMISSAO PARA USUARIO XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20019);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20020);

-- ADICIONA PERMISSAO PARA USUARIO MSO RESIDENCIAL

INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
SELECT
    SEQ_PERMISSAO_ESPECIAL.nextval,
    CURRENT_DATE,
    20020,
    USUARIO_ID.*,
    1
FROM    (
            SELECT FK_USUARIO
            FROM USUARIO U JOIN  USUARIO_TIPO_FEEDER UTF ON U.ID = UTF.FK_USUARIO
            WHERE UTF.TIPO_FEEDER_MSO = 'RESIDENCIAL' AND U.FK_CARGO = 22 AND U.FK_DEPARTAMENTO = 21
            GROUP BY FK_USUARIO
        ) USUARIO_ID;

INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
SELECT
    SEQ_PERMISSAO_ESPECIAL.nextval,
    CURRENT_DATE,
    20019,
    USUARIO_ID.*,
    1
FROM    (
            SELECT FK_USUARIO
            FROM USUARIO U JOIN  USUARIO_TIPO_FEEDER UTF ON U.ID = UTF.FK_USUARIO
            WHERE UTF.TIPO_FEEDER_MSO = 'RESIDENCIAL' AND U.FK_CARGO = 22 AND U.FK_DEPARTAMENTO = 21
            GROUP BY FK_USUARIO
        ) USUARIO_ID;