-- CRIA PERMISSAO PARA PRIORIZAR INDICACOES TECNICO
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (16113, 'Priorizar Indicações Técnico', 'BKO_PRIORIZAR_INDICACOES', 24);

-- ADICIONA PERMISSAO PARA MSO(CONSULTOR)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 16113);

-- ADICIONA PERMISSAO PARA XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 16113);
