-- Adiciona a funcionalidade 'Gerenciar Tratativas do Técnico Vendedor' para os cargos técnicos.
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SUPERVISOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16106);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_COORDENADOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16106);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_GERENTE'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16106);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
    (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_VENDEDOR'),
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
    16106);
