-- REMOVE PERMISSOES DOS MSO'S CONSULTORES
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 20018 AND FK_CARGO = 22;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 20008 AND FK_CARGO = 22;

-- ADICIONA PERMISSAO DE VISUALIZAR CARGA DE ALARME PARA MSO CONSULTOR FEEDER RESIDENCIAL
INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
SELECT SEQ_PERMISSAO_ESPECIAL.nextval,
       CURRENT_DATE,
       20018,
       USUARIO_ID.*,
       1
FROM (SELECT FK_USUARIO
      FROM USUARIO U
               JOIN USUARIO_TIPO_FEEDER UTF ON U.ID = UTF.FK_USUARIO
      WHERE UTF.TIPO_FEEDER_MSO = 'RESIDENCIAL'
        AND U.FK_CARGO = 22
        AND U.FK_DEPARTAMENTO = 21
      GROUP BY FK_USUARIO) USUARIO_ID;

-- ADICIONA PERMISSAO DE IMPORTAR CARGA DE ALARME PARA MSO CONSULTOR FEEDER RESIDENCIAL
INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
SELECT SEQ_PERMISSAO_ESPECIAL.nextval,
       CURRENT_DATE,
       20008,
       USUARIO_ID.*,
       1
FROM (SELECT FK_USUARIO
      FROM USUARIO U
               JOIN USUARIO_TIPO_FEEDER UTF ON U.ID = UTF.FK_USUARIO
      WHERE UTF.TIPO_FEEDER_MSO = 'RESIDENCIAL'
        AND U.FK_CARGO = 22
        AND U.FK_DEPARTAMENTO = 21
      GROUP BY FK_USUARIO) USUARIO_ID;
