-- VINCULA CARGO OPERACAO_ANALISTA E FUNCIONALIDADE VDS_3061
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1, 3, 3061);

-- VINCULA CARGO VENDEDOR_OPERACAO E FUNCIONALIDADE VDS_3061
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 8, 3, 3061);