INSERT INTO APLICACAO (ID, CODIGO, NOME)
VALUES (SEQ_APLICACAO.nextval, 'CHC', 'CHECAGEM CREDITO');

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (21000, 'Gerenciar nova checagem crédito', 'CHC_21000', (SELECT ID FROM APLICACAO WHERE CODIGO = 'CHC'));