-- REMOVE PERMISSAO COORDENADOR OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 4 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3001;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 4 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3002;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 4 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3013;

-- REMOVE PERMISSAO GERENTE OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 7 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3001;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 7 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3002;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 7 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3005;

-- REMOVE PERMISSAO SUPERVISOR OPERACAO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 10 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3001;
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 10 AND FK_DEPARTAMENTO = 3 AND FK_FUNCIONALIDADE = 3002;