INSERT INTO APLICACAO (ID, CODIGO, NOME)
VALUES (SEQ_APLICACAO.nextval, 'CHC', 'CHECAGEM CREDITO');

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (22500, 'Gerenciar nova checagem crédito', 'CHC_22500', (SELECT ID FROM APLICACAO WHERE CODIGO = 'CHC'));