-- CRIA PERMISSAO PARA TRABALHAR ALARMES
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20100, 'Trabalhar Alarmes', 'VDS_20100', 3);

-- CRIA PERMISSAO PARA DESBLOQUEAR ALARMES
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20101, 'Desbloquear Alarmes', 'VDS_20101', 3);

-- ADICIONA PERMISSOES PARA USUARIOS XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20100);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20101);

-- ADICIONA PERMISSOES PARA USUARIOS MSO CONSULTOR FEEDER RESIDENCIAL
INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
SELECT SEQ_PERMISSAO_ESPECIAL.nextval,
       CURRENT_DATE,
       20100,
       USUARIO_ID.*,
       1
FROM (SELECT FK_USUARIO
      FROM USUARIO U
               JOIN USUARIO_TIPO_FEEDER UTF ON U.ID = UTF.FK_USUARIO
      WHERE UTF.TIPO_FEEDER_MSO = 'RESIDENCIAL'
        AND U.FK_CARGO = 22
        AND U.FK_DEPARTAMENTO = 21
      GROUP BY FK_USUARIO) USUARIO_ID;

INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
SELECT SEQ_PERMISSAO_ESPECIAL.nextval,
       CURRENT_DATE,
       20101,
       USUARIO_ID.*,
       1
FROM (SELECT FK_USUARIO
      FROM USUARIO U
               JOIN USUARIO_TIPO_FEEDER UTF ON U.ID = UTF.FK_USUARIO
      WHERE UTF.TIPO_FEEDER_MSO = 'RESIDENCIAL'
        AND U.FK_CARGO = 22
        AND U.FK_DEPARTAMENTO = 21
      GROUP BY FK_USUARIO) USUARIO_ID;