ALTER TABLE USUARIO ADD NOME_EQUIPE_VENDA_NET_SALES VARCHAR2(120 CHAR);
ALTER TABLE USUARIO ADD CODIGO_EQUIPE_VENDA_NET_SALES VARCHAR2(120 CHAR);

ALTER TABLE USUARIO_AUD ADD NOME_EQUIPE_VENDA_NET_SALES VARCHAR2(120 CHAR);
ALTER TABLE USUARIO_AUD ADD CODIGO_EQUIPE_VENDA_NET_SALES VARCHAR2(120 CHAR);

