ALTER TABLE ORGANIZACAO_EMPRESA RENAME COLUMN NOME TO DESCRICAO;

ALTER TABLE ORGANIZACAO_EMPRESA RENAME COLUMN CODIGO TO NOME;

ALTER TABLE ORGANIZACAO_EMPRESA
    ADD CODIGO VARCHAR2(80);

UPDATE ORGANIZACAO_EMPRESA
SET CODIGO = 'BC14234'
WHERE FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE')
  AND DESCRICAO = 'BRASIL CENTER';

UPDATE ORGANIZACAO_EMPRESA
SET CODIGO = 'MO1234'
WHERE FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE')
  AND DESCRICAO = 'MOTIVA';

