-- PERMISSAO PARA  UNIFICACAR AGENTES AUTORIZADOS--
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (21019, 'Unificar agentes autorizados', 'POL_21019', 2);

-- CARGO XBRAIN -- DEPARTAMENTO ADMINISTRADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 50, 21019);

-- CARGO XBRAIN -- DEPARTAMENTO HELPDESK --
INSERT INTO CARGO_DEPART_FUNC (ID, DATA_CADASTRO, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, current_date, 50, 51, 21019);