-- Cria usuario de Integração para o App Minha Claro --
INSERT INTO USUARIO
    (
        ID,
        ALTERAR_SENHA,
        DATA_CADASTRO,
        EMAIL_01,
        NASCIMENTO,
        NOME,
        SENHA,
        SITUACAO,
        FK_CARGO,
        FK_DEPARTAMENTO,
        RECUPERAR_SENHA_TENTATIVA
    )
    VALUES
    (
        SEQ_USUARIO.NEXTVAL,
        'F',
        CURRENT_DATE,
        'INTEGRACAOMINHACLAROAPP@XBRAIN.COM.BR',
        CURRENT_DATE,
        'INTEGRAÇÃO APP MINHA CLARO',
        '$2y$10$ijb2fdPiD.Aa0le.KTbQ7OfpJnj9tG9gFi89gOyaERmlRjuln9NZG',
        'A',
        (SELECT ID FROM CARGO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO = 'A'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO ='A'),
        0
    );

INSERT INTO USUARIO_UNIDADE_NEGOCIO (FK_USUARIO, FK_UNIDADE_NEGOCIO)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOMINHACLAROAPP@XBRAIN.COM.BR'), 3);

INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOMINHACLAROAPP@XBRAIN.COM.BR'), 4);

-- Cria funcionalidade --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (7014, 'Visualizer Status da Venda pelo App Minha Claro', 'INT_APP_MINHA_CLARO', 8);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 7014);

-- Adiciona permissão especial para o usuario de INTEGRACAO --
INSERT INTO PERMISSAO_ESPECIAL
    (
        ID,
        DATA_CADASTRO,
        FK_FUNCIONALIDADE,
        FK_USUARIO,
        FK_USUARIO_CADASTRO
    )
VALUES
    (
        SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        7014,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOMINHACLAROAPP@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'VALCIRBELLO@XBRAIN.COM.BR')
    )