-- FUNCIONALIDADE --
--------------------

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (9011, 'Visualizar números Loja Futuro Regional', 'DSH_9011', 10);

-- PERMISSÕES --
----------------

-- ADMINISTRADOR XBRAIN

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 9011);

-- MSO CONSULTOR

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 9011);
