-- INSERE MOTIVO INATIVACAO PARA ORGANIZA EMPRESA INATIVADA
INSERT INTO MOTIVO_INATIVACAO (ID, CODIGO, DESCRICAO, SITUACAO)
VALUES (11, 'ORGANIZACAO_EMPRESA_INATIVA', 'INATIVADO POR ORGANIZAÇÃO EMPRESA INATIVA', 'A');
