-- CRIA FUNCIONALIDADE GERENCIAR CANAL NETSALES
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (20017, 'Gerenciar Canal Net Sales', 'CRT_GERENCIAR_CANAL_NET_SALES', 20);

-- INSERIR FUNCIONALIDADE PARA USUARIOS XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20017);
