-- ALTERA HORAS ADICIONAIS DA CONFIGURAÇÃO PADRAO PARA 12 HORAS
UPDATE CONFIGURACAO_AGENDA_REAL
SET QTD_HORAS = 12
WHERE ID = 1;

-- REMOVE PERMISSÃO DE PARAMETRIZAÇÃO PARA USUARIOS MSO
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 22 AND FK_DEPARTAMENTO = 21 AND FK_FUNCIONALIDADE = 21615;
