ALTER TABLE CONFIGURACAO_AGENDA_REAL ADD USUARIO_CADASTRO_NOME VARCHAR(255);
ALTER TABLE CONFIGURACAO_AGENDA_REAL ADD USUARIO_CADASTRO_ID INTEGER;
ALTER TABLE CONFIGURACAO_AGENDA_REAL ADD DATA_CADASTRO TIMESTAMP;