UPDATE (SELECT CDF.FK_DEPARTAMENTO AS DEPARTAMENTO_ID
        FROM CARGO_DEPART_FUNC CDF
                 INNER JOIN FUNCIONALIDADE F ON CDF.FK_FUNCIONALIDADE = F.ID
                 INNER JOIN CARGO C ON CDF.FK_CARGO = C.ID
                 INNER JOIN NIVEL N ON C.FK_NIVEL = N.ID
                 INNER JOIN DEPARTAMENTO D ON D.ID = CDF.FK_DEPARTAMENTO
        WHERE C.FK_NIVEL = 2
          AND FK_DEPARTAMENTO = 3
          AND F.ROLE = 'POL_239')
SET DEPARTAMENTO_ID = 21;