CREATE SEQUENCE SEQ_CONFIGURACAO_AGENDA START WITH 1 INCREMENT BY 1;

CREATE TABLE CONFIGURACAO_AGENDA
(
    ID           INTEGER       NOT NULL,
    QTD_HORAS    INTEGER       NOT NULL,
    DESCRICAO    VARCHAR2(255) NOT NULL,
    NIVEL        VARCHAR2(255),
    CANAL        VARCHAR2(255),
    SUBCANAL     VARCHAR2(255),
    ESTRUTURA_AA VARCHAR2(255),
    PRIMARY KEY (ID)
);