RENAME CONFIGURACAO_AGENDA TO CONFIGURACAO_AGENDA_REAL;
DROP SEQUENCE SEQ_CONFIGURACAO_AGENDA;
CREATE SEQUENCE SEQ_CONFIGURACAO_AGENDA_REAL START WITH 1 INCREMENT BY 1;
ALTER TABLE CONFIGURACAO_AGENDA_REAL DROP COLUMN SUBCANAL;
ALTER TABLE CONFIGURACAO_AGENDA_REAL ADD SUBCANAL_ID INTEGER;