-- Adiciona permissão para priorizar hp suporte de vendas --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (22011, 'Priorizar Hp Suporte Vendas', 'BKO_22011', 24);

-- Atribui permissão a usuários XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 22011);

-- Atribui permissão a usuários MSO CONSULTOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 22011);
