-- CRIA PERMISSAO PARA TIPO CAMPANHA
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (22007, 'Gerenciar Tipo Campanha Suporte Vendas', 'BKO_22007', 24);

-- CRIA PERMISSAO PARA TRATAMENTO TABULACAO
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (22009, 'Gerenciar Tratamento Tabulacoes Suporte Vendas', 'BKO_22009', 24);

-- ADICIONA PERMISSAO TIPO CAMPANHA PARA USUARIO XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 22007);

-- ADICIONA PERMISSAO TRATAMENTO TABULACAO PARA USUARIO XBRAIN E MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 22009);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 22009);
