-- CRIA APLICACAO REDE SOCIAL CONEXAO --
INSERT INTO APLICACAO (ID, NOME, CODIGO) VALUES (SEQ_APLICACAO.nextval, 'SOCIAL HUB', 'SHB');

-- CRIA PERMISSAO PARA ACESSAR REDE SOCIAL CONEXAO --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (30000, 'Acessar Social Hub', 'SHB_30000', SEQ_APLICACAO.CURRVAL);
