-- Criacao de Cargo Tecnico Segmentado
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL) VALUES (SEQ_CARGO.nextval, 'AGENTE_AUTORIZADO_TECNICO_SEGMENTADO', 'Técnico Segmentado', 'A', 3);

-- Adiciona funcionalidade 'Criar Correção de Vendas pelo Técnico' para o Cargo Tecnico Segmentado.
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
        (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SEGMENTADO'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
        16111);