-- Atribui Permissao VISUALIZAR SCRIPT SUPORTE DE VENDAS para usuarios MSO CONSULTOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 22012);
