-- FUNCIONALIDADE PARA GERENCIAR MOTIVOS DE REPROVAÇÃO DE PROJETOS
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (10017, 'Reprovar Solitações de Projetos', 'BRF_10017', 19);

-- ADMINSTRADOR / Departamento ADMINISTRADOR
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 10017);

-- ADMINSTRADOR / Departamento HELPDESK
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 51, 10017);