-- Adiciona a funcionalidade 'Técnico Cria Tratativa' para o cargo de Técnico Segmentado.
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
        (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SEGMENTADO'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
        16112);

-- Adiciona a funcionalidade 'Gerenciar Tratativas do Técnico Vendedor' para o cargo de Técnico Segmentado.
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval,
        (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SEGMENTADO'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'TECNICO'),
        16106);