-- Cria funcionalidade --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (10023, 'Desbloqueio de solicitação de projetos', 'BRF_10023', 19);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 10023);

-- Adiciona permissão especial para o usuario do caio --
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM USUARIO WHERE EMAIL_01 = 'CAIO.SOARES@CLARO.COM.BR';
    IF QTD > 0 THEN
        INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
        VALUES (
            SEQ_PERMISSAO_ESPECIAL.nextval,
            CURRENT_DATE,
            10023,
            (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'CAIO.SOARES@CLARO.COM.BR'),
            (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'JOAO.BANCI@XBRAIN.COM.BR')
            );
    END IF;
END;
