-- CRIA PERMISSAO PARA GERENCIAR CONFIGURACOES DE AGENDA
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (21615, 'Gerenciar Configurações de Agenda', 'AUT_21615', 1);

-- ADICIONA PERMISSAO PARA USUARIOS XBRAIN E MSO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 21615);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 21615);
