-- Adiciona permissão para Vizsualizar script suporte de vendas --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (22012, 'Visualizar Script Suporte Vendas', 'BKO_22012', 24);

-- Atribui permissão a usuários XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 22012);

-- Atribui permissão a usuários OPERADOR SUPORTE DE VENDAS --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 401, 800, 22012);
