--- FUNCIONALIDADE GERENCIAR TERRITORIOS PME---
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (5021, 'Gerenciar Territorios Pme', 'MLG_GERENCIAR_TERRITORIOS_PME', 4);

-- INSERIR FUNCIONALIDADE PARA USUARIOS XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 5021);
