ALTER TABLE SUB_CANAL ADD NOVA_CHECAGEM_VIABILIDADE VARCHAR2(1 CHAR) DEFAULT ON NULL 'F';

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (20026, 'Editar nova checagem de viabilidade - Sub-canais','AUT_20026', 1);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 20026);