-- INSERIR FUNCIONALIDADE 'POL 243' --
-- PARA USUÁRIOS QUE PODEM CADASTRAR TRATATIVAS --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
SELECT
	SEQ_CARGO_DEPART_FUNC.nextval,
	fk_cargo,
	fk_departamento,
	248
FROM (
		SELECT DISTINCT fk_cargo, fk_departamento
		FROM cargo_depart_func
		WHERE fk_funcionalidade = 3052
);
