-- CRIA PERMISSAO PARA REPROCESSAR GERAL NO PAINEL DE VENDAS
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (21880, 'Reprocessar Geral Painel de Vendas', 'VDS_21880', 3);

-- ADICIONA PERMISSAO PARA USUARIO XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 21880);