INSERT INTO USUARIO_CANAL (FK_USUARIO, CANAL)
SELECT U.ID, 'AGENTE_AUTORIZADO'
FROM USUARIO U
         INNER JOIN CARGO C ON U.FK_CARGO = C.ID
WHERE U.ID NOT IN (SELECT FK_USUARIO FROM USUARIO_CANAL WHERE CANAL = 'AGENTE_AUTORIZADO')
  AND C.CODIGO LIKE '%AGENTE_AUTORIZADO%'
  AND DATA_CADASTRO > TO_DATE('13/02/2024', 'DD/MM/YYYY');
