-- Cria nova funcinalidade --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (16019, 'Detalhar Tratativa sem Mascara', 'BKO_DETALHAR_TRATATIVA_SEM_MASCARA', 24);

-- Adiciona funcionalidade em XBRAIN --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 16019);

-- Adiciona funcionalidade em MSO ASSISTENTE --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 21, 21, 16019);

-- Adiciona funcionalidade em MSO ANALISTA --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 20, 21, 16019);

-- Adiciona funcionalidade em MSO CONSULTOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 16019);

-- Adiciona funcionalidade em MSO COORDENADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 23, 21, 16019);

-- Adiciona funcionalidade em BACKOFFICE SUPERVISOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 112, 69, 16019);

-- Adiciona funcionalidade em BACKOFFICE COORDENADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 113, 69, 16019);

-- Adiciona funcionalidade em BKO CENTRALIZADO SUPERVISOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (
    SEQ_CARGO_DEPART_FUNC.nextval,
    117,
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')),
    16019
);

-- Adiciona funcionalidade em BKO CENTRALIZADO COORDENADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (
    SEQ_CARGO_DEPART_FUNC.nextval,
    118,
    (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')),
    16019
);
