-- Remove funcionalidade trabalhar para xbrain
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 22001 AND FK_CARGO = 21 AND FK_DEPARTAMENTO = 21;

-- Remove funcionalidade trabalhar para mso
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 22001 AND FK_CARGO = 50 AND FK_DEPARTAMENTO = 50;