-- Criar usuário Para Uso da claro para visualizar a checagem de credito por RPA e pela checagem-credito-api --
INSERT INTO USUARIO
    (
        ID,
        ALTERAR_SENHA,
        DATA_CADASTRO,
        EMAIL_01,
        NASCIMENTO,
        NOME,
        SENHA,
        SITUACAO,
        FK_CARGO,
        FK_DEPARTAMENTO,
        RECUPERAR_SENHA_TENTATIVA
    )
    VALUES
    (
        SEQ_USUARIO.NEXTVAL,
        'F',
        CURRENT_DATE,
        'USUARIOCHECAGEMCREDITOAPIRPAINTEGRACAO@XBRAIN.COM.BR',
        CURRENT_DATE,
        'USUARIO CHECAGEM DE CREDITO API RPA INTEGRACAO',
        '$2a$12$5CVRc4UzmJsIYdFK6hXa2udndLZF271gxPz3kHtMag5b2fYp632cy',
        'A',
        (SELECT ID FROM CARGO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO = 'A'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO ='A'),
        0
    );

INSERT INTO USUARIO_UNIDADE_NEGOCIO (FK_USUARIO, FK_UNIDADE_NEGOCIO)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'USUARIOCHECAGEMCREDITOAPIRPAINTEGRACAO@XBRAIN.COM.BR'), 3);

INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'USUARIOCHECAGEMCREDITOAPIRPAINTEGRACAO@XBRAIN.COM.BR'), 4);

-- Criar funcionalidade --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (7017, 'visualizacao checagem credito api rpa integracao', 'INT_7017', 8);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 7017);

-- Adicionar permissão especial para o usuário cadastrado --
INSERT INTO PERMISSAO_ESPECIAL
    (
        ID,
        DATA_CADASTRO,
        FK_FUNCIONALIDADE,
        FK_USUARIO,
        FK_USUARIO_CADASTRO
    )
VALUES
    (
        SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        7017,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'USUARIOCHECAGEMCREDITOAPIRPAINTEGRACAO@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'THIAGO.GLOOR@XBRAIN.COM.BR')
    )
