UPDATE USUARIO
SET EMAIL_01 = 'INTEGRACAOECOMMERCE@XBRAIN.COM.BR',
    SENHA    = '$2a$12$lAs7x3QE3/cv0sHhdKAN0uuYr8uAJEEIZVuVBuGMGSKf6ZDOEtSS2'
WHERE EMAIL_01 = 'INTEGRACAOCADASTROTRATATIVAECOMMERCE@XBRAIN.COM.BR';
