-- Remove funcionalidade trabalhar para xbrain
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 22001 AND FK_CARGO = 21 AND FK_DEPARTAMENTO = 21;

    IF QTD = 1 THEN
        DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 22001 AND FK_CARGO = 21 AND FK_DEPARTAMENTO = 21;
    END IF;
END;

-- Remove funcionalidade trabalhar para mso
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 22001 AND FK_CARGO = 50 AND FK_DEPARTAMENTO = 50;

    IF QTD = 1 THEN
        DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 22001 AND FK_CARGO = 50 AND FK_DEPARTAMENTO = 50;
    END IF;
END;