-- Deleta funcionalidade em BKO CENTRALIZADO SUPERVISOR --
DELETE FROM CARGO_DEPART_FUNC
WHERE FK_CARGO = 117
AND FK_DEPARTAMENTO = (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO'))
AND FK_FUNCIONALIDADE = 16019;

-- Deleta funcionalidade em BKO CENTRALIZADO COORDENADOR --
DELETE FROM CARGO_DEPART_FUNC
WHERE FK_CARGO = 118
AND FK_DEPARTAMENTO = (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO'))
AND FK_FUNCIONALIDADE = 16019;