-- Linkar as permissões do Backoffice de qualidade ao SubNivel quando existirem
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 21007;

    IF QTD = 1 THEN
        INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
        VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 21007, 3);
    END IF;
END;
/

DECLARE
BEGIN
    FOR usuario IN (
        SELECT * FROM USUARIO
        WHERE FK_CARGO in (20, 21, 22, 23, 1161)
          AND SITUACAO = 'A'
    )
    LOOP
        INSERT INTO USUARIO_SUBNIVEL (FK_USUARIO, FK_SUBNIVEL)
        VALUES (usuario.ID, 1);

        INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
        SELECT SEQ_PERMISSAO_ESPECIAL.nextval, sysdate, FUNC.ID, usuario.ID, 1
        FROM FUNCIONALIDADE FUNC
        WHERE FUNC.ID IN (16001, 16002, 16003, 16004, 16007, 16008,
                          16010, 16014, 16017, 16019, 16109, 22662);

        IF usuario.FK_CARGO = 23 THEN
            INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
            VALUES (SEQ_PERMISSAO_ESPECIAL.nextval, sysdate, 22662, usuario.ID, 1);
        END IF;
    END LOOP;
END;
/
