-- Linkar as permissões do Backoffice ao SubNivel quando existirem
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 22015;

    IF QTD = 1 THEN
        INSERT INTO FUNCIONALIDADE_SUBNIVEL (FK_FUNCIONALIDADE, FK_SUBNIVEL) VALUES (22015 , 1);
    END IF;
END;

-- Linkar as permissões do Backoffice de qualidade ao SubNivel quando existirem
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 21007;

    IF QTD = 1 THEN
        INSERT INTO FUNCIONALIDADE_SUBNIVEL (FK_FUNCIONALIDADE, FK_SUBNIVEL) VALUES (21007, 3);
    END IF;
END;

DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 21008;

    IF QTD = 1 THEN
        INSERT INTO FUNCIONALIDADE_SUBNIVEL (FK_FUNCIONALIDADE, FK_SUBNIVEL) VALUES (21008 , 3);
    END IF;
END;
