ALTER TABLE USUARIO ADD CANAL_NETSALES_ID INTEGER;

ALTER TABLE USUARIO RENAME COLUMN CANAL_NETSALES TO CANAL_NETSALES_CODIGO;

ALTER TABLE USUARIO_AUD ADD CANAL_NETSALES_ID INTEGER;

ALTER TABLE USUARIO_AUD RENAME COLUMN CANAL_NETSALES TO CANAL_NETSALES_CODIGO;