--FUNCIONALIDADE GERENCIAR CONFIGURACAO TRATATIVAS
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (22015, 'Gerenciar Configuração Tratativas', 'BKO_GERENCIAR_CONFIGURACAO_TRATATIVA', 24);

--INSERIR FUNCIONALIDADE PARA USUARIOS XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 22015);
