-- Criacao da sequence SUB_NIVEL
CREATE SEQUENCE SEQ_SUB_NIVEL START WITH 1 INCREMENT BY 1;

-- Criacao da tabela SUB_NIVEL
create table SUB_NIVEL(
    ID          INTEGER     PRIMARY KEY NOT NULL,
    NOME        VARCHAR2(100),
    CODIGO      VARCHAR2(50),
    SITUACAO    VARCHAR2(1),
    FK_NIVEL    INTEGER,
    FOREIGN KEY (FK_NIVEL) REFERENCES NIVEL (ID)
);

-- Adicao de dados do SUB_NIVEL
INSERT INTO SUB_NIVEL (ID, NOME, CODIGO, SITUACAO, FK_NIVEL)
VALUES (1, 'BACKOFFICE', 'BACKOFFICE', 'A', 2);
INSERT INTO SUB_NIVEL (ID, NOME, CODIGO, SITUACAO, FK_NIVEL)
VALUES (2, 'BACKOFFICE CENTRALIZADO', 'BACKOFFICE_CENTRALIZADO', 'A', 2);
INSERT INTO SUB_NIVEL (ID, NOME, CODIGO, SITUACAO, FK_NIVEL)
VALUES (3, 'BACKOFFICE DE QUALIDADE', 'BACKOFFICE_QUALIDADE', 'A', 2);
INSERT INTO SUB_NIVEL (ID, NOME, CODIGO, SITUACAO, FK_NIVEL)
VALUES (4, 'BACKOFFICE SUPORTE DE VENDAS', 'BACKOFFICE_SUPORTE_VENDAS', 'A', 2);

-- Adicao de tabela USUARIO_SUBNIVEL
CREATE TABLE USUARIO_SUBNIVEL(
    FK_USUARIO INTEGER,
    FK_SUBNIVEL INTEGER,
    PRIMARY KEY (FK_USUARIO, FK_SUBNIVEL),
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_SUBNIVEL) REFERENCES SUB_NIVEL(ID)
);

-- Criar tabela de relacionamento CARGO_FUNC_SUBNIVEL
CREATE SEQUENCE SEQ_CARGO_FUNC_SUBNIVEL START WITH 1 INCREMENT BY 1;

CREATE TABLE CARGO_FUNC_SUBNIVEL(
    ID                  INTEGER     PRIMARY KEY NOT NULL,
    FK_CARGO            INTEGER,
    FK_FUNCIONALIDADE   INTEGER     NOT NULL,
    FK_SUBNIVEL         INTEGER     NOT NULL,
    FOREIGN KEY (FK_CARGO) REFERENCES  CARGO(ID),
    FOREIGN KEY (FK_FUNCIONALIDADE) REFERENCES FUNCIONALIDADE(ID),
    FOREIGN KEY (FK_SUBNIVEL) REFERENCES SUB_NIVEL(ID)
);

-- LINKAR FUNCIONALIDADES BACKOFFICE AO SUB_NIVEL: BACKOFFICE
-- (16001, 16002, 16003, 16004, 16007, 16008,
--  16010, 16014, 16017, 16019, 16109, 22662);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16001, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16002, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16003, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16004, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16007, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16008, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16010, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16014, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16017, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16019, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16109, 1);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_CARGO, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 23, 22662, 1);

-- LINKAR FUNCIONALIDADES BACKOFFICE CENTRALIZADO AO SUB_NIVEL: BACKOFFICE_CENTRALIZADO
-- (16101, 16104, 16110, 16113);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16101, 2);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16104, 2);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16110, 2);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 16113, 2);

-- LINKAR FUNCIONALIDADES BACKOFFICE_SUPORTE_VENDAS AO TIPO_BACKOFFICE
-- (21292, 21420, 22002, 22003, 22004, 22005, 22006,
--  22007, 22009, 22010, 22011, 22012, 22013, 22014);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 21292, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 21420, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22002, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22003, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22004, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22005, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22006, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22007, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22009, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22010, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22011, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22012, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22013, 4);
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22014, 4);
