INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
SELECT SEQ_PERMISSAO_ESPECIAL.nextval, CURRENT_DATE, 22122, CV.USUARIO_ID, 1
FROM AGENTE_AUTORIZADO@LINK_PARCEIROS AA
         JOIN GESTAO_COLAB.COLABORADOR_VENDAS CV ON AA.ID = CV.AGENTE_AUTORIZADO_ID
         JOIN USUARIO AU ON CV.USUARIO_ID = AU.ID
WHERE AA.TRABALHAR_HP_TECNICO_INDICADOR = 'V'
  AND AU.FK_CARGO IN (40, 43, 44, 78, 56, 88, 84, 45, 46, 47, 91, 82, 41, 42, 48, 90, 81, 1254, 1255, 1361, 1253, 121, 79, 80, 89, 85, 57, 49, 58, 87, 83)
  AND AU.FK_DEPARTAMENTO = 40;

INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
SELECT SEQ_PERMISSAO_ESPECIAL.nextval, CURRENT_DATE, 22122, AA.USUARIO_PROPRIETARIO_ID, 1
FROM AGENTE_AUTORIZADO@LINK_PARCEIROS AA
         JOIN USUARIO AU ON AA.USUARIO_PROPRIETARIO_ID = AU.ID
WHERE AA.TRABALHAR_HP_TECNICO_INDICADOR = 'V'
  AND AU.FK_CARGO IN 41
  AND AU.FK_DEPARTAMENTO = 40;