INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
VALUES (SEQ_PERMISSAO_ESPECIAL.nextval,
        SYSDATE,
        248,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOECOMMERCE@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'GABRIELTONHATTI@XBRAIN.COM.BR'));
