--Adiciona cargo Supervisor de Tratamento de Anti Fraude
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL)
VALUES (125,
        'BACKOFFICE_SUPERVISOR_DE_TRATAMENTO_DE_ANTI_FRAUDE',
        'Supervisor de Tratamento de Anti Fraude',
        'A',
        (SELECT ID
         FROM NIVEL
         WHERE CODIGO = 'BACKOFFICE'));

--Adiciona cargo Supervisor de Tratamento de Crédito
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL)
VALUES (126,
        'BACKOFFICE_SUPERVISOR_DE_TRATAMENTO_DE_CREDITO',
        'Supervisor de Tratamento de Crédito',
        'A',
        (SELECT ID
         FROM NIVEL
         WHERE CODIGO = 'BACKOFFICE'));

--Adiciona cargo Supervisor de Tratamento de Endereços
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL)
VALUES (127,
        'BACKOFFICE_SUPERVISOR_DE_TRATAMENTO_DE_ENDERECOS',
        'Supervisor de Tratamento de Endereços',
        'A',
        (SELECT ID
         FROM NIVEL
         WHERE CODIGO = 'BACKOFFICE'));

--Adicioa permissões para o cargo Supervisor de Tratamento de Anti Fraude
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 125, 78, 16002);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 125, 78, 16004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 125, 78, 16007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 125, 78, 16003);

--Adicioa permissões para o cargo Supervisor de Tratamento de Crédito
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 126, 79, 16002);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 126, 79, 16004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 126, 79, 16007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 126, 79, 16003);

--Adicioa permissões para o cargo Supervisor de Tratamento de Endereços
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 127, 80, 16002);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 127, 80, 16004);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 127, 80, 16007);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 127, 80, 16003);