UPDATE USUARIO u
SET u.CANAL_NETSALES_ID = (
    SELECT ID
    FROM CANAL_NETSALES@LINK_PARCEIROS pc
    WHERE pc.CODIGO = u.CANAL_NETSALES_CODIGO
)
WHERE u.CANAL_NETSALES_CODIGO = (SELECT pc.CODIGO
                                 FROM CANAL_NETSALES@LINK_PARCEIROS pc
                                 WHERE pc.CODIGO = u.CANAL_NETSALES_CODIGO)
AND EXISTS (
    SELECT 1
    FROM CANAL_NETSALES@LINK_PARCEIROS pc
    WHERE pc.CODIGO = u.CANAL_NETSALES_CODIGO)
AND u.CANAL_NETSALES_CODIGO IS NOT NULL
AND u.CANAL_NETSALES_ID IS NULL;