-- Criar usuário criação de tratativa e-commerce
INSERT INTO USUARIO
(ID,
 ALTERAR_SENHA,
 DATA_CADASTRO,
 EMAIL_01,
 NASCIMENTO,
 NOME,
 SENHA,
 SITUACAO,
 FK_CARGO,
 FK_DEPARTAMENTO,
 RECUPERAR_SENHA_TENTATIVA)
VALUES (SEQ_USUARIO.NEXTVAL,
        'F',
        CURRENT_DATE,
        'INTEGRACAOCADASTROTRATATIVAECOMMERCE@XBRAIN.COM.BR',
        CURRENT_DATE,
        'INTEGRACAO CADASTRO TRATATIVA ECOMMERCE',
        '$2a$12$5CVRc4UzmJsIYdFK6hXa2udndLZF271gxPz3kHtMag5b2fYp632cy',
        'A',
        (SELECT ID FROM CARGO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO = 'A'),
        (SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'INTEGRACAO' AND SITUACAO = 'A'),
        0);

INSERT INTO USUARIO_UNIDADE_NEGOCIO (FK_USUARIO, FK_UNIDADE_NEGOCIO)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOCADASTROTRATATIVAECOMMERCE@XBRAIN.COM.BR'), 3);

INSERT INTO USUARIO_EMPRESA (FK_USUARIO, FK_EMPRESA)
VALUES ((SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOCADASTROTRATATIVAECOMMERCE@XBRAIN.COM.BR'), 4);

-- Criar funcionalidades --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (30002, 'CADASTRAR TRATATIVAS ECOMMERCE', 'INT_30002', 8);

INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (30003, 'CONSULTAR TRATATIVAS ECOMMERCE', 'INT_30003', 8);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 30002);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 30003);

-- Adicionar permissões especiais para o usuário cadastrado --
INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
VALUES (SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        30002,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOCADASTROTRATATIVAECOMMERCE@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'GABRIELTONHATTI@XBRAIN.COM.BR'));

INSERT INTO PERMISSAO_ESPECIAL
(ID,
 DATA_CADASTRO,
 FK_FUNCIONALIDADE,
 FK_USUARIO,
 FK_USUARIO_CADASTRO)
VALUES (SEQ_PERMISSAO_ESPECIAL.nextval,
        CURRENT_DATE,
        30003,
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'INTEGRACAOCADASTROTRATATIVAECOMMERCE@XBRAIN.COM.BR'),
        (SELECT ID FROM USUARIO WHERE EMAIL_01 = 'GABRIELTONHATTI@XBRAIN.COM.BR'));
