-- Cria nova funcinalidade Visualizar Dados Cliente Relatorio --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (22662, 'Visualizar Dados Cliente Relatorio', 'BKO_VISUALIZAR_DADOS_CLIENTE_RELATORIO', 24);

-- Adiciona funcionalidade em XBRAIN --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 22662);

-- Adiciona funcionalidade em MSO COORDENADOR --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 23, 21, 22662);

-- Adiciona funcionalidade em SUPERVISOR TRATAMENTO ANTI FRAUDE
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 125, 78, 22662);

-- Adiciona funcionalidade em SUPERVISOR TRATAMENTO CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 126, 79, 22662);

-- Adiciona funcionalidade em SUPERVISOR TRATAMENTO ENDERECOS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 127, 80, 22662);

-- Adiciona funcionalidade em ANALISTA TRATAMENTO ANTI FRAUDE
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 122, 78, 22662);

-- Adiciona funcionalidade em ANALISTA TRATAMENTO CREDITO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 123, 79, 22662);

-- Adiciona funcionalidade em ANALISTA TRATAMENTO ENDERECOS
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 124, 80, 22662);
