-- Linkar as permissões do Backoffice ao SubNivel quando existirem
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 22015;

    IF QTD = 1 THEN
        INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
        VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 22015 , 1);
    END IF;
END;
/

DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 22662;

    IF QTD = 1 THEN
        INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_CARGO, FK_FUNCIONALIDADE, FK_SUBNIVEL)
        VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 23, 22662 , 1);
    END IF;
END;
/

-- Linkar as permissões do Backoffice de qualidade ao SubNivel quando existirem
DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 21007;

    IF QTD = 1 THEN
        INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
        VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 21007, 3);
    END IF;
END;
/

DECLARE
    QTD INT;
BEGIN
    SELECT COUNT(*) INTO QTD FROM FUNCIONALIDADE WHERE ID = 21008;

    IF QTD = 1 THEN
        INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL)
        VALUES (SEQ_CARGO_FUNC_SUBNIVEL.nextval, 21008 , 3);
    END IF;
END;
/
