-- ADICIONA PERMISSAO DE GERENCIAR FILAS DE TRATAMENTO DO TECNICO VENDEDOR PARA
-- COORDENADOR, GERENTE E SUPERVISOR DE TRATAMENTO DE VENDAS DO BACKOFFICE CENTRALIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, 117, 1041, 22663);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, 118, 1041, 22663);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, 119, 1041, 22663);

-- ADICIONA PERMISSAO PARA SUB-NIVEL BACKOFFICE CENTRALIZADO
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL) VALUES (SEQ_CARGO_FUNC_SUBNIVEL.NEXTVAL, 22663, 2);

-- ADICIONA PERMISSAO PARA USUARIOS JÁ CADASTRADOS PARA O NIVEL MSO E SUB-NIVEL BACKOFFICE CENTRALIZADO
DECLARE
BEGIN
    FOR usuario IN (
        select * from USUARIO U
        INNER JOIN USUARIO_SUBNIVEL US
        ON U.ID = US.FK_USUARIO
        WHERE US.FK_SUBNIVEL = 2
    )
    LOOP
        INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
        VALUES (SEQ_PERMISSAO_ESPECIAL.NEXTVAL, SYSDATE, 22663, usuario.ID, 1);
    END LOOP;
END;
