-- ALTERA ID DO CARGO AGENTE_AUTORIZADO_SUPERVISOR_BACKOFFICE PARA ALINHAR EM TODOS OS AMBIENTES COM O ID 1423
UPDATE CARGO_DEPART_FUNC
SET FK_CARGO = 1423
WHERE FK_CARGO = (
    SELECT ID
    FROM CARGO
    WHERE CODIGO = 'AGENTE_AUTORIZADO_SUPERVISOR_BACKOFFICE'
);

UPDATE CARGO SET ID = 1423 WHERE CODIGO = 'AGENTE_AUTORIZADO_SUPERVISOR_BACKOFFICE';
