-- CRIA PERMISSAO PARA ACESSAR DADOS DA CONFIGURAÇÃO DE FILA DE TRATAMENTO
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (22663, 'Gerenciar configuração de fila de tratamento', 'BKO_22663', 24);

-- VINCULA PERMISSÃO AO XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, 50, 50, 22663);
