INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (21021, 'Ativar Chip', 'VDS_ATIVAR_CHIP', 3);

BEGIN
	FOR F IN (
		-- Busca todos cargos_dep_funcionalidades cuja funcionalidade seja VDS_VISUALIZAR_TRAT_VENDA
		SELECT FK_CARGO, FK_DEPARTAMENTO
		FROM CARGO_DEPART_FUNC
		WHERE FK_FUNCIONALIDADE = (
			SELECT ID
			FROM FUNCIONALIDADE
			WHERE ROLE = 'VDS_VISUALIZAR_TRAT_VENDA')
	) LOOP
		INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
		VALUES (SEQ_CARGO_DEPART_FUNC.nextval, F.FK_CARGO, F.FK_DEPARTAMENTO, 21021);
	END LOOP;
END;
