-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - SÓCIO SECUNDARIO - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, (SELECT ID FROM CARGO WHERE CODIGO = 'AGENTE_AUTORIZADO_SOCIO_SECUNDARIO'), 40, 9011);

-- REMOVER PERMISSAO AGENTE AUTORIZADO - COORDENADOR TÉCNICO - AGENTE AUTORIZADO --
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 1253 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 9011;

-- REMOVER PERMISSÃO AGENTE AUTORIZADO - SUPERVISOR TÉCNICO - AGENTE AUTORIZADO --
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 1254 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 9011;

-- REMOVER PERMISSÃO AGENTE AUTORIZADO - AGENTE AUTORIZADO APRENDIZ - AGENTE AUTORIZADO --
DELETE FROM CARGO_DEPART_FUNC WHERE FK_CARGO = 43 AND FK_DEPARTAMENTO = 40 AND FK_FUNCIONALIDADE = 9011;
