-- ADICIONA NOVO CARGO PARA SUPERVISOR BACKOFFICE PARA USUARIO AGENTE AUTORIZADO

-- CRIA CARGO NO AUTENTICACAO
INSERT INTO CARGO (ID, CODIGO, NOME, SITUACAO, FK_NIVEL, QUANTIDADE_SUPERIOR) VALUES (1423, 'AGENTE_AUTORIZADO_SUPERVISOR_BACKOFFICE', 'Supervisor BackOffice', 'A', 3, 50);

-- ADICIONA AS MESMAS PERMISSOES DO CARGO AGENTE_AUTORIZADO_SUPERVISOR
BEGIN
    FOR C IN (
        SELECT DISTINCT FK_FUNCIONALIDADE, FK_DEPARTAMENTO
        FROM CARGO_DEPART_FUNC
        WHERE FK_CARGO = (
            SELECT ID
            FROM CARGO
            WHERE CODIGO = 'AGENTE_AUTORIZADO_SUPERVISOR'
        )
    ) LOOP
        INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_FUNCIONALIDADE, FK_DEPARTAMENTO) VALUES (SEQ_CARGO_DEPART_FUNC.NEXTVAL, 1423, C.FK_FUNCIONALIDADE, C.FK_DEPARTAMENTO);
    END LOOP;
END;