DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 13002 AND FK_CARGO IN (57, 58, 79, 80);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 79, 40, 13001);
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 80, 40, 13001);

DELETE FROM FUNCIONALIDADE_CANAL WHERE FK_FUNCIONALIDADE = 13003;

DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 13003;