-- FUNCIONALIDADE --
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO) VALUES (9011, 'Visualizar dashboard zerados', 'DSH_9011', 10);

-- FUNCIONALIDADE POR CANAL --
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (9011, 'AGENTE_AUTORIZADO');

-- NIVEL AGENTE AUTORIZADO --
-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - SÓCIO PRINCIPAL - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 41, 40, 9011);

-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - SÓCIO SECUNDÁRIO - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 43, 40, 9011);

-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - GERENTE - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 47, 40, 9011);

-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - COORDENADOR - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 45, 40, 9011);

-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - COORDENADOR TÉCNICO - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1254, 40, 9011);

-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - SUPERVISOR - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 48, 40, 9011);

-- ADICIONAR PERMISSÃO AGENTE AUTORIZADO - SUPERVISOR TÉCNICO - AGENTE AUTORIZADO --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 1253, 40, 9011);

-- NIVEL OPERAÇÃO --
-- ADICIONAR PERMISSÃO OPERAÇÃO - DIRETOR - COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 6, 3, 9011);

-- ADICIONAR PERMISSÃO OPERAÇÃO - GERENTE - COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 7, 3, 9011);

-- ADICIONAR PERMISSÃO OPERAÇÃO - COORDENADOR - COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 4, 3, 9011);

-- ADICIONAR PERMISSÃO OPERAÇÃO - EXECUTIVO - COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 5, 3, 9011);

-- ADICIONAR PERMISSÃO OPERAÇÃO - ASSISTENTE - COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 2, 3, 9011);

-- NIVEL MSO --
-- ADICIONAR PERMISSAO MSO - CONSULTOR - COMERCIAL --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 22, 21, 9011);

-- Administrador (X-Brain) --
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE) VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 9011);