-- ADICIONA PERMISSAO DE GERENCIAR FILAS DE TRATAMENTO DO TECNICO VENDEDOR PARA
-- COORDENADOR, GERENTE E SUPERVISOR DE TRATAMENTO DE VENDAS DO BACKOFFICE CENTRALIZADO
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (
    SEQ_CARGO_DEPART_FUNC.NEXTVAL,
    (
        SELECT ID
        FROM CARGO
        WHERE CODIGO = 'BACKOFFICE_SUPERVISOR_TRATAMENTO_VENDAS'
            AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')
    ),
    (
        SELECT ID
        FROM DEPARTAMENTO
        WHERE FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')
    ),
    22663
);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (
    SEQ_CARGO_DEPART_FUNC.NEXTVAL,
    (
        SELECT ID
        FROM CARGO
        WHERE CODIGO = 'BACKOFFICE_COORDENADOR_TRATAMENTO_VENDAS'
            AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')
    ),
    (
        SELECT ID
        FROM DEPARTAMENTO
        WHERE FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')
    ),
    22663
);

INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (
    SEQ_CARGO_DEPART_FUNC.NEXTVAL,
    (
        SELECT ID
        FROM CARGO
        WHERE CODIGO = 'BACKOFFICE_GERENTE_TRATAMENTO_VENDAS'
            AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')
    ),
    (
        SELECT ID
        FROM DEPARTAMENTO
        WHERE FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')
    ),
    22663
);

-- ADICIONA PERMISSAO PARA SUB-NIVEL BACKOFFICE CENTRALIZADO
INSERT INTO CARGO_FUNC_SUBNIVEL (ID, FK_FUNCIONALIDADE, FK_SUBNIVEL) VALUES (SEQ_CARGO_FUNC_SUBNIVEL.NEXTVAL, 22663, 2);

-- ADICIONA PERMISSAO PARA USUARIOS JÁ CADASTRADOS PARA O NIVEL MSO E SUB-NIVEL BACKOFFICE CENTRALIZADO
DECLARE
BEGIN
    FOR usuario IN (
        SELECT * FROM USUARIO U
        INNER JOIN USUARIO_SUBNIVEL US
        ON U.ID = US.FK_USUARIO
        WHERE US.FK_SUBNIVEL = 2
    )
    LOOP
        INSERT INTO PERMISSAO_ESPECIAL (ID, DATA_CADASTRO, FK_FUNCIONALIDADE, FK_USUARIO, FK_USUARIO_CADASTRO)
        VALUES (SEQ_PERMISSAO_ESPECIAL.NEXTVAL, SYSDATE, 22663, usuario.ID, 1);
    END LOOP;
END;
