-- ATUALIZA CODIGO_EQUIPE_VENDA_NET_SALES DO USUARIO COM DADOS DO COLABORADOR_VENDAS
UPDATE USUARIO U
SET U.CODIGO_EQUIPE_VENDA_NET_SALES = (
    SELECT CV.CODIGO_EQUIPE_VENDA_NETSALES
    FROM GESTAO_COLAB.COLABORADOR_VENDAS CV
    WHERE U.ID = CV.USUARIO_ID
      AND ROWNUM = 1
  )
WHERE
 U.CODIGO_EQUIPE_VENDA_NET_SALES IS NULL
  AND U.SITUACAO = 'A'
  AND (
    SELECT COUNT(CV.USUARIO_ID)
    FROM GESTAO_COLAB.COLABORADOR_VENDAS CV
    WHERE U.ID = CV.USUARIO_ID
      AND CV.CODIGO_EQUIPE_VENDA_NETSALES IS NOT NULL
      AND CV.FK_SITUACAO = 5
  ) = 1;

-- ATUALIZA NOME_EQUIPE_VENDA_NET_SALES DO USUARIO COM DADOS DO COLABORADOR_VENDAS
UPDATE USUARIO U
SET U.NOME_EQUIPE_VENDA_NET_SALES = (
    SELECT CV.NOME_EQUIPE_VENDA_NETSALES
    FROM GESTAO_COLAB.COLABORADOR_VENDAS CV
    WHERE U.ID = CV.USUARIO_ID
      AND ROWNUM = 1
  )
WHERE
  U.NOME_EQUIPE_VENDA_NET_SALES IS NULL
  AND U.SITUACAO = 'A'
  AND (
    SELECT COUNT(CV.USUARIO_ID)
    FROM GESTAO_COLAB.COLABORADOR_VENDAS CV
    WHERE U.ID = CV.USUARIO_ID
      AND CV.NOME_EQUIPE_VENDA_NETSALES IS NOT NULL
      AND CV.FK_SITUACAO = 5
  ) = 1;

-- ATUALIZA CODIGO_EQUIPE_VENDA_NET_SALES DO USUARIO COM DADOS DO COLABORADOR_TECNICO
UPDATE USUARIO U
SET U.CODIGO_EQUIPE_VENDA_NET_SALES = (
    SELECT CT.CODIGO_EQUIPE_VENDA_NETSALES
    FROM GESTAO_COLAB.COLABORADOR_TECNICO CT
    WHERE U.ID = CT.USUARIO_ID
      AND ROWNUM = 1
  )
WHERE
  U.CODIGO_EQUIPE_VENDA_NET_SALES IS NULL
  AND U.SITUACAO = 'A'
  AND (
    SELECT COUNT(CT.USUARIO_ID)
    FROM GESTAO_COLAB.COLABORADOR_TECNICO CT
    WHERE U.ID = CT.USUARIO_ID
      AND CT.CODIGO_EQUIPE_VENDA_NETSALES IS NOT NULL
      AND CT.SITUACAO = 'ATIVO'
  ) = 1;

-- ATUALIZA NOME_EQUIPE_VENDA_NET_SALES DO USUARIO COM DADOS DO COLABORADOR_TECNICO
UPDATE USUARIO U
SET U.NOME_EQUIPE_VENDA_NET_SALES = (
    SELECT CT.NOME_EQUIPE_VENDA_NETSALES
    FROM GESTAO_COLAB.COLABORADOR_TECNICO CT
    WHERE U.ID = CT.USUARIO_ID
      AND ROWNUM = 1
  )
WHERE
  U.NOME_EQUIPE_VENDA_NET_SALES IS NULL
  AND U.SITUACAO = 'A'
  AND (
    SELECT COUNT(CT.USUARIO_ID)
    FROM GESTAO_COLAB.COLABORADOR_TECNICO CT
    WHERE U.ID = CT.USUARIO_ID
      AND CT.NOME_EQUIPE_VENDA_NETSALES IS NOT NULL
      AND CT.SITUACAO = 'ATIVO'
  ) = 1;
