-- ADICIONA FUNCIONALIDADES DO CONTATO CRN PARA O CANAL AGENTE AUTORIZADO
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (13000, 'AGENTE_AUTORIZADO');
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (13001, 'AGENTE_AUTORIZADO');
INSERT INTO FUNCIONALIDADE_CANAL (FK_FUNCIONALIDADE, CANAL) VALUES (13002, 'AGENTE_AUTORIZADO');

-- REMOVE PERMISSAO GERENCIAR CHAMADO DO VENDEDOR BACKOFFICE AA
DELETE FROM CARGO_DEPART_FUNC WHERE FK_FUNCIONALIDADE = 13001 AND FK_CARGO IN (79, 80);