-- REMOVER PERMISSAO AGENTE AUTORIZADO - COORDENADOR TÉCNICO - E - SUPERVISOR TÉCNICO - AGENTE AUTORIZADO --
DELETE FROM CARGO_DEPART_FUNC
WHERE FK_FUNCIONALIDADE = 9011
AND FK_DEPARTAMENTO = 40
AND FK_CARGO IN
(SELECT CG.ID FROM CARGO CG
WHERE CG.CODIGO = 'AGENTE_AUTORIZADO_TECNICO_COORDENADOR'
OR CG.CODIGO = 'AGENTE_AUTORIZADO_TECNICO_SUPERVISOR');
