-- Adiciona Permissão GERENCIAR_CARTEIRA
INSERT INTO FUNCIONALIDADE (ID, NOME, ROLE, FK_APLICACAO)
VALUES (23216, 'Gerenciar Carteira', 'POL_GERENCIAR_CARTEIRA', 2);

-- Atribui Permissão GERENCIAR_CARTEIRA ao cargo XBRAIN
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 50, 50, 23216);

