-- Adiciona permissão BKO_VISUALIZAR_TRATATIVA_TECNICO para Supervisor de Tratamento de Vendas (Backoffice Centralizado)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 117,
(SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')), 16107);

-- Adiciona permissão BKO_VISUALIZAR_TRATATIVA_TECNICO para Coordenador de Tratamento de Vendas (Backoffice Centralizado)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 118,
(SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')), 16107);

-- Adiciona permissão BKO_VISUALIZAR_TRATATIVA_TECNICO para Gerente de Tratamento de Vendas (Backoffice Centralizado)
INSERT INTO CARGO_DEPART_FUNC (ID, FK_CARGO, FK_DEPARTAMENTO, FK_FUNCIONALIDADE)
VALUES (SEQ_CARGO_DEPART_FUNC.nextval, 119,
(SELECT ID FROM DEPARTAMENTO WHERE CODIGO = 'COMERCIAL' AND FK_NIVEL = (SELECT ID FROM NIVEL WHERE CODIGO = 'BACKOFFICE_CENTRALIZADO')), 16107);